stanfordnlp/dspy

dsp/evaluation/utils.py
If notebook is set to False, it will return a string instead of displaying a styled dataframe.
=> No longer assume we are always running in a notebook

dsp/modules/sentence_vectorizer.py, dsp/primitives/demonstrate.py, dsp/utils/__init__.py
@okhat resolves last comments in #12
=> Resolve import issues for FAISS

dsp/modules/colbertv2.py, dsp/modules/gpt3.py, dsp/primitives/demonstrate.py, dsp/primitives/predict.py, dsp/primitives/primitives.py, dsp/primitives/search.py, dsp/templates/template_v2.py, dsp/templates/template_v3.py, dsp/templates/utils.py, dsp/utils/settings.py, dsp/utils/utils.py
- documentation: adding type hints and doc-strings 
- GPT turbo model integration with simple single-turn user prompting strategy.
=> feature(new-LM): GPT turbo integration

dsp/modules/cohere.py, dsp/modules/gpt3.py, dsp/modules/hf.py, dsp/modules/lm.py
- Cohere uses the abstracted LM class (newly added) for consistency. 
- Base LM class breaks gpt3 module due to mismatch in abstracted class signature
- minor refactoring and bug fixes
=> refactor(cohere): cohere module abstraction & few bug fixes

dsp/modules/gpt3.py
Adds support for Azure OpenAI API Service.
=> enhancement(GPT-LLM): azure API support

dsp/modules/gpt3.py
=> bug(chatgpt-lm): remove unnecessary param passing

dsp/utils/settings.py
=> Revert "Making the DSP context window thread safe"

dsp/modules/azurecognitivesearch.py, setup.py
added wrapper class to support retrieval model from Azure cognitive search.
=> added wrapper for azure cognitive search retrieval

dsp/modules/__init__.py, dsp/modules/pyserini.py, dspy/__init__.py, pyserini.ipynb
Integrate pyserini to enable users to use their own data for retrieval in dspy. I've added a small notebook to demo how it works.
=> Integrate Pyserini into DSPy

README.md
links added for LM clients, RM clients, relevant Modules and Teleprompters.
also updated PR link for dspy.ProgramOfThought
=> linked module docs onto README

dsp/modules/pyserini.py
retrieval when using your own data should be faster now, let me know if you have any other ideas/changes in mind
=> Change PyseriniRetriever linear index search to lookup table

dspy/teleprompt/random_search.py
added stop_at_score per [issue request ](https://github.com/stanfordnlp/dspy/issues/128)
=> added stop_at_score kwarg to random_search

dsp/modules/__init__.py, dsp/modules/hf_client.py, dspy/__init__.py
-integrated Anyscale endpoint within DSPy
=> added client integrations for Anyscale

dsp/modules/hf_client.py
follows #3 within [Anyscale OpenAI endpoint handling](https://github.com/anyscale/endpoint-cookbook/blob/main/combine_anyscale_openai.ipynb)
allows for string prompting to models
=> added support for OpenAI completion API string prompting

dspy/evaluate/__init__.py, dspy/evaluate/auto_evaluation.py, dspy/signatures/signature.py
AnswerCorrectness - verifies if predicted answer is correct for question based on gold answer and outputs True/False
AnswerFaithfulness - verifies if predicted answer is based off context/reasoning/rationale for question and outputs True/False
(corrects faulty [PR](https://github.com/stanfordnlp/dspy/pull/173))
=> added AnswerCorrectness and AnswerFaithfulness auto-eval modules

README.md, dspy/retrieve/chromadb_rm.py, setup.py
This PR adds [chromadb](https://docs.trychroma.com/getting-started) to the RM.
The PR uses [openai embedding](https://platform.openai.com/docs/guides/embeddings).
This PR is based on existing RM code:
- dspy/retrieve/pinecone_rm.py
- dspy/retrieve/qdrant_rm.py
=> feat: Add chromadb support for retrieval 

README.md, dspy/retrieve/marqo_rm.py, setup.py
**Description**: This PR adds [marqo](https://github.com/marqo-ai/marqo) as a supported retrieval mechanism.
=> feat: Add Marqo for retrieval

dsp/modules/sentence_vectorizer.py, dspy/teleprompt/knn_fewshot.py
-fixed sentence vectorizer for string formatting
-updated KNNFewShot teleprompter with correct args handling
=> updated knn_fewshot with fixes

dsp/modules/hf_client.py, dspy/__init__.py
We had already a PR for vLLM support (https://github.com/stanfordnlp/dspy/pull/93), from which this small patch was adapted to work for the current vLLM version. Feel free to merge this or use it just as a reference to improve the other. Thanks!
=> add minimum working support for vLLM

examples/knn.ipynb
This change illustrates how to use the KNNFewShot teleprompter in an example `.ipynb`
=> Add KNNFewShot Example

dsp/templates/template_v2.py, dspy/teleprompt/__init__.py, dspy/teleprompt/signature_opt.py
Adds SignatureOptimizer, a teleprompter which optimizes a program's prompt signatures using iterative feedback on replacement signatures, generated by a teacher language model.
```python
teleprompter = SignatureOptimizer(metric=metric, breadth=BREADTH, depth=DEPTH, init_temperature=INIT_TEMPERATURE, prompt_model=prompt_model, output_dir=optimizedV1_output_dir)
kwargs = dict(num_threads=NUM_THREADS, display_progress=True, display_table=0)
compiled_prompt_opt = teleprompter.compile(program.deepcopy(), devset=devset[:DEV_NUM], eval_kwargs=kwargs)
eval_score = evaluate(compiled_prompt_opt, devset=evalset[:EVAL_NUM], **kwargs)
```
The below diagram demonstrates the algorithm for optimization, in this case with GPT 3.5 as the prompt model, and Llama2 as the task model:
Collaboration with …
=> Add SignatureOptimizer Teleprompter

dsp/evaluation/utils.py, dsp/modules/gpt3.py, dsp/modules/sentence_vectorizer.py, dspy/retrieve/chromadb_rm.py, dspy/retrieve/pinecone_rm.py, requirements.txt
#223 and I think that it can help with #180 , allowing the use of [LiteLLM](https://github.com/BerriAI/litellm) with [Ollama](https://github.com/jmorganca/ollama), I tested the changes with this
=> Update for compatibility with openai ^1.0

dspy/retrieve/chromadb_rm.py, dspy/retrieve/pinecone_rm.py
Hi @okhat, sorry for the late response, I think this changes should fix the compatibility with 0.28
=> openai 0.28 backwards compatibility for pinecone and chromadb

.pre-commit-config.yaml, pyproject.toml
Some files were deleted after last merge -> so adding them back
=> feat(dspy): adding missing precommit files

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Adding the pull request template to standardize the way we describe changes (to be refined based on needs)
=> ops(dspy): Adding pull request template

dspy/teleprompt/__init__.py, dspy/teleprompt/signature_opt_bayesian.py
This new optimizer utilizes optuna to jointly optimize fewshot examples and the instruction for a prompt, over a specified number of trials.
Work done in collaboration with @XenonMolecule (Michael Ryan).
=> Adding BayesianSignatureOptimizer

dspy/teleprompt/signature_opt_bayesian.py
- fixes bug that called an experimental version of inspect_history
- makes optuna runs deterministic
=> bug fix to teleprompter, making runs deterministic

dspy/teleprompt/signature_opt_bayesian.py, testing/README.md, testing/optimizer_tester.py, testing/tasks/__init__.py, testing/tasks/base_task.py, testing/tasks/biodex.py, testing/tasks/gsm8k.py, testing/tasks/hotpotqa.py, testing/tasks/scone.py, testing/tasks/tweet.py, testing/tasks/tweet_metric.py
Optimizer Tester is intended to allow simple and repeatable testing of DSPy Optimizers.  This is a development tool for the creation of more optimizers and the verification that they work across tasks.  This is still under development and subject to change.
```python
task_model = dspy.HFClientTGI(...)
prompt_model = dspy.OpenAI(...)
tester = OptimizerTester(prompt_model=prompt_model, task_model=task_model)
tester.test_baseline(datasets=["HotPotQA", "GSM8K", "Scone"])
def your_optimizer_caller(default_program, trainset, devset, test_name, dataset_name, kwargs):
teleprompter = my_custom_optimizer(metric=kwargs["metric"], ...)
compiled_program = teleprompter.compile(default_program.deepcopy(), trainset=trainset, ...)
output = {
"test_name": "my_optimizer-" + dataset_name + "-" + test_name
} …
```
=> Add Optimizer Testing Framework and Data-Aware Bayesian Signature Optimization

CONTRIBUTING.md
Add a bounty board to CONTRIBUTING.md to track desired features
Fixes small typos in CONTRIBUTING.md
N/A
=> docs(dspy): Update CONTRIBUTING.md file with bounty board

dspy/retrieve/vectara_rm.py
Implementation of a Vectara retirever
=> Vectara retriever

dspy/retrieve/weaviate_rm.py
This should fix it, accidentally wrapped the return in a `dspy.Prediction`.
Sorry for the back and forth with this, pretty sure it is in good shape now.
=> [Bug Fix] WeaviateRM

dsp/modules/__init__.py, dsp/modules/hf_client.py, dspy/__init__.py
- sameple code
```
lm = dspy.Together(model="mistralai/Mistral-7B-Instruct-v0.2")
```
- registration $25 free credit on registration
Register: https://api.together.xyz/
- models: https://api.together.xyz/playground
We recommend to start with mistral, llama2.
- api usage
- document
https://docs.together.ai/docs/quickstart
=> Adding code to access together APIs

dspy/predict/chain_of_thought.py, dspy/predict/predict.py, dspy/predict/retry.py
=> Add retry capabilities to Predict

dspy/retrieve/chromadb_rm.py
- testing tested with chroma==0.4.17
*Note*: this change is not related to the new cohort.
Thank you and let me know your feedback, @okhat
=> Minor update on chroma rm init

dsp/modules/aws_lm.py, dsp/modules/bedrock.py, dsp/modules/hf_client.py
Update together model prompt and stop sequence
- update prompt based on the model name
- update stop sequence
*TEST*:
- the following models are tested using `intro.ipynb`
- completion model
```
model="mistralai/Mistral-7B-v0.1"
turbo = dspy.Together(model=model)
```
- instruction mode
```
model="mistralai/Mistral-7B-Instruct-v0.2"
turbo = dspy.Together(model=model)
```
=> Update together model prompt and stop sequence

dspy/teleprompt/signature_opt_bayesian.py
Previously the prompt and task models were defaulting to "None". Now they are defaulting to `dspy.settings.lm`.
=> Fixing bayesian optimizer bug with prompt / task model

dspy/retrieve/qdrant_rm.py
This PR adds the `long_text` key to the `passages` returned by the QdrantRM.
In dsp/primitives/search line 10: `passages = [psg.long_text for psg in passages]` throws an error without this.
I'm not aware of the full context, but this PR will patch the QdrantRM for now.
=> [BugFix] QdrantRM Patch, add  long_text key to passages

docs/assertions.md, examples/longformqa/longformqa_assertions.ipynb, examples/quiz/quiz_assertions.ipynb, examples/tweets/tweets_assertions.ipynb
-documentation for DSPy Assertions
-example notebooks for the QuizGen and TweetGen tasks
=> documentation and QuizGen+TweetGen notebooks

dsp/modules/hf_client.py
Hi,
I've noticed that `dsp.modules.hf_client.Anyscale` fails to produce multiple completions when a `dspy.predict.predict.Predict` object using it has `n>1`. The LLM provider itself does not support this option for now, so I was thinking this may be something DSPy could handle instead.
The following code snippet reproduces the issue:
```python
import os
import dspy
os.environ["ANYSCALE_API_BASE"] = 'https://api.endpoints.anyscale.com/v1'
os.environ["ANYSCALE_API_KEY"] = 'esecret_123'  # set to match your anyscale endpoints key
llm = dspy.Anyscale(model='mistralai/Mistral-7B-Instruct-v0.1', max_tokens=1000)
dspy.configure(lm=llm)
N = 3
generate_answer = dspy.Predict('question -> answer', n=N)
r = generate_answer(question='Why did the chicken cross the road?')
assert …
```
=> fix: manually iterate kwargs['n'] in anyscale

setup.py
Updates the dependencies of the `qdrant` extra to latest.
=> chore: Bump Qdrant dependencies

examples/tweets/tweet_metric.py, testing/tasks/tweet.py, testing/tasks/tweet_metric.py
=> [MINOR] Typo Correction

dsp/modules/hf.py
Quick fix https://github.com/stanfordnlp/dspy/issues/188
I think this minor fix could be very helpful for Mac beginners as well as CPU beginners who just get started using the library.
=> Allow HFModel to use CPU

dspy/predict/react.py
=> fix react.py #276 

dsp/modules/hf.py
Currently, when using the HF model backend, the `hf_device_map` parameter may not propagate to the `AutoModel*`. This PR solves that, by passing the `hf_device_map` to the underlying `AutoModel*`.
Ultimately, this allows for splitting models across multiple GPUs/accelerators.
=> Propagate device_map to hf model

docs/retrieval_models_client.md, dspy/retrieve/faiss_rm.py, setup.py
Please note that this Pull Request is just an update to the top of the tree and was already discussed in PR #423
=> feat(retrieve): add support for faiss retriever, update setup.md, docs

dspy/evaluate/evaluate.py
Minor changes to enable the evaluator to accept any callable objects as metrics.
=> feat(Evaluate): callable objects can be used as metric for Evaluate

dsp/modules/databricks.py, dspy/__init__.py
-moved OpenAI dependencies within local functions to avoid OpenAI version incompatibilities in build: `from openai import OpenAI` is compatible with >1.11.1
=> migrated latest OpenAI version import

docs-page/docs/tutorials/simplified-baleen.md
=> from dspy.teleprompt import BootstrapFewShot

examples/integrations/clarifai/clarifai_llm_retriever_example.ipynb
Objective :
1. Modified notebook example with 2 more models.
=> DSPy-Clarifai integration - modified example notebook

dspy/teleprompt/signature_opt.py
The changes made to SignatureOptimizer seem like they need to be applied also when verbose=True.
=> Fixed verbose for signature_opt

dspy/datasets/dataloader.py, dspy/functional/functional.py, dspy/signatures/signature.py, tests/functional/test_functional.py
Also created a test, and made sure tests run with python 3.9.
Slightly contaminated by reformatting.
=> Fixed some issues with generics like list[str]

dspy/functional/functional.py, dspy/signatures/signature.py, examples/functional/functional.ipynb, tests/functional/test_functional.py
Cleans up some type stuff (no more pydantic version in error messages),
Removes make_example (now it happens automatically, only if there's actually an error),
Fixes some some issues with generics like List[str]
=> Type improvements

dspy/teleprompt/random_search.py
Fixed spelling error and added option to not shuffle labeled data.
=> Fixed spelling error

dspy/teleprompt/random_search.py
Apologies. Better tested this time.
=> fixed bug in previous commit

docs/docs/deep-dive/teleprompter/signature-optimizer.mdx
1. use the HotPotQA dataset instead of gsm8k
2. result.rationale instead of result.reason
3. process devset to include input_keys
=> Fix code issues in signature-optimizer.mdx

dspy/retrieve/faiss_rm.py
add 'k' as argument to FaissRM.forward()
=> add 'k' as argument to FaissRM.forward()

dspy/evaluate/evaluate.py
Remade version of https://github.com/stanfordnlp/dspy/pull/555 as requested by @isaacbmiller.
=> Fix return_all_scores in evaluate

dsp/modules/anthropic.py
This is a quick fix for unexpected print statement, and also includes linting.
=> fix(dspy): remove debug print statement (minor)

dspy/functional/functional.py, dspy/signatures/field.py, tests/functional/test_functional.py
Also added some more tests for demos.
=> Fixed issue with boolean outputs.

dsp/modules/cache_utils.py
Ran `ruff check . --fix-only`
Lint error comes from #581 being merged without passing 4/4 CI. Everything working as intended.
=> bug(dspy): Ran ruff check . --fix-only

dspy/functional/functional.py, dspy/signatures/signature.py, tests/functional/test_functional.py
Main improvement: Self explaining errors, ReACT prompting style. This is an optional feature that sometimes help the LLM learn from past errors.
=> TypedPredictor improvements

tests/functional/test_functional.py
=> Test for model_validator

docs/docs/quick-start/installation.mdx
Minor change, adding Weaviate pip install guide (it was missing).
=> Added Weaviate installation guide

docs/api/retrieval_model_clients/AzureCognitiveSearch.md, docs/docs/deep-dive/retrieval_models_clients/Azure.mdx, dsp/modules/azurecognitivesearch.py, dspy/retrieve/azureaisearch_rm.py
**Feature Addition: Introducing AzureAISearchRM Class**
This pull request introduces the AzureAISearchRM class, designed as a retrieval module utilizing Azure AI Search to retrieve top passages for a given query. Below are the details of this new class:
Key Features:
Integration with Azure AI Search: The class enables seamless integration with Azure AI Search service, facilitating the retrieval of top passages based on user queries.
Flexible Configuration: Users can configure various parameters such as the Azure AI Search service name, API key, search index name, and other optional settings like semantic ranking, filter queries, and speller mode.
Ease of Use: The class provides an intuitive interface for interacting with Azure AI Search, making it straightforward for developers to …
=> feat(dspy): add support for azure ai search

dspy/retrieve/weaviate_rm.py, poetry.lock, pyproject.toml
I upgraded the client version in the poetry project configuration. I changed the contract of the init method to pass a few additional parameters important for configuring the hybrid query. 
I did not commit the poetry.lock file, as this is giving regular merge problems. I hope that is done before creating a release.
=> fix for weaviate outdated client version. Issue 699

docs/docs/building-blocks/6-optimizers.md, docs/docs/cheatsheet.md
* A new section in the Optimizers Building Blocks page about saving and loading an optimized program
* A new section in the Cheat Sheet about saving and loading modules
=> docs: examples for saving and loading modules after optimizing

docs/api/retrieval_model_clients/RAGatouilleRM.md, dspy/retrieve/ragatouille_rm.py
Adding custom RM client for RAGatouille based index.
Related to #631
=> Custom RM client for RAGatouille

README.md, docs/api/retrieval_model_clients/MilvusRM.md, docs/docs/deep-dive/retrieval_models_clients/MilvusRM.mdx, docs/docs/quick-start/installation.mdx, dspy/retrieve/milvus_rm.py, examples/integrations/readme.md, poetry.lock, pyproject.toml, setup.py
Add MilvusRM to support retrieval for Milvus or Zilliz Cloud:
- milvus: https://github.com/milvus-io/milvus
- Zilliz Cloud: https://zilliz.com
=> feature(dspy): Add Milvus in Retrieve

dsp/modules/lm.py
This was triggering an unhandled exception when calling
=> Add missing provider condition for groq in inspect_history in LM class

dspy/primitives/assertions.py, examples/longformqa/longformqa_assertions.ipynb, examples/quiz/quiz_assertions.ipynb, examples/tweets/tweets_assertions.ipynb
-updated logic to handle previously-observed error `WARNING: Not all input fields were provided to module`
-updated notebooks and caches respectively
=> updated assertions logic + notebook/caches

docs/docs/building-blocks/1-language_models.md
=> Switch 1-language_models.md to non gated models

README.md
**Description**
I've added a demonstration of how DSPy and vLLM work together, showing the use of an open source language model for Text-to-SQL. This example is added to the README.md file.
**Discord Issue**
https://discord.com/channels/1161519468141355160/1229209497411649537
=> Added dspy + vllm example to README.md

README.md, docs/docs/tutorials/other_tutorial.md
There are a couple of "DSPy Crash Course" videos available from AI Bites. 
This PR is to add the links to those videos in the README and docs.
=> AI Bites resources links

dspy/predict/react.py, tests/predict/test_react.py
Implements the suggested fix [here](https://github.com/stanfordnlp/dspy/issues/804#issuecomment-2054110487)
=> fix(dspy) fix issue 804

docs/docs/faqs.md
I found this confusing, wanted to help others with a small FAQ addition.
=> Update FAQ about Multi-line Strings

dspy/retrieve/databricks_rm.py
- This change allows passing different filters to the same instance of a DatabricksRM object
=> Passing the "filters_json" param in the "forward" method

docs/docs/tutorials/other_tutorial.md
A tutorial on:
- defining a DSPy RAG program
- tracing its execution steps to debug performance
- comparing different DSPy programs & their optimizations
- performing an ablation study on how many samples are needed to achieve best performance
=> docs: add tutorial on dspy program tracing & optimization tracking

dsp/modules/__init__.py, dsp/modules/lm.py, dsp/modules/watsonx.py, dspy/__init__.py
Added support for IBM Watsonx.ai LLMs
=> feature(dspy): Added support for IBM Watsonx.ai

docs/api/language_model_clients/Groq.md
=> Update Groq.md, fix typos

docs/api/language_model_clients/Cloudflare.md, dsp/modules/__init__.py, dsp/modules/cloudflare.py, dsp/modules/lm.py, dspy/__init__.py, tests/modules/test_cloudflare_models.py
This feature adds support for using [Cloudflare Workers AI](https://developers.cloudflare.com/workers-ai/).
Using Cloudflare gives support for a wide variety of open source [models](https://developers.cloudflare.com/workers-ai/models/#text-generation).
`CLOUDFLARE_ACCOUNT_ID`
`CLOUDFLARE_API_KEY`
```python
lm = dspy.CloudflareAI(model="@cf/meta/llama-3-8b-instruct", 
account_id="", # optional, will check env
api_key="" # optional, will check env
)
dspy.settings.configure(lm=lm)
```
=> feat: adds Cloudflare Workers AI

dspy/predict/knn.py, dspy/teleprompt/knn_fewshot.py, examples/knn.ipynb, tests/teleprompt/test_knn_fewshot.py
Clean up `predict/knn` and `teleprompt/knn_fewshot`:
* Added a optional `vectorizer` instead of using hardcoded `SentenceTransformer` one
* Clean up constructor a bit
=> Clean up knn related functionalities a bit

docs/docs/quick-start/installation.mdx
Closes https://github.com/stanfordnlp/dspy/issues/1033
=> Add quotes around package names

dspy/retrieve/qdrant_rm.py, examples/integrations/qdrant/qdrant_retriever_example.ipynb
Adds a notebook example to demonstrate the `QdrantRM` integration.
=> docs: Qdrant RM example

docs/docusaurus.config.ts
This PR adds the RunLLM AI chat widget to DSPy's docs page.
=> Add RunLLM chat widget

docs/api/language_model_clients/PremAI.md, docs/docs/deep-dive/language_model_clients/remote_models/PremAI.mdx, dsp/modules/premai.py
This PR adds the support for native RAG support in premai dspy module. Docs are also updated with the latest improvements. 
Also, it removes some deprecated parameters and handles edge cases related to those.
=> Improvement: Add support for Prem Repositories in dspy prem module

docs/docs/cheatsheet.md, docs/docs/faqs.md
Spotted a couple of small typos while working through the docs.
=> fix(docs): minor typos

dspy/predict/multi_chain_comparison.py
Closes #1103
I didn't test this since it's just adding the message for the assert. 
Do I need to test it or is MultiChainComparison covered well enough by tests anyway?
=> Add message for assert

dspy/retrieve/epsilla_rm.py, poetry.lock, pyproject.toml
This PR adds a retriever for [epsilla](https://epsilla-inc.gitbook.io/epsilladb/)
=> feat(dspy): Add epsilla retriever

dspy/experimental/__init__.py, dspy/experimental/module_graph.py
The ModuleGraph class is a utility for generating visual representations of Python modules and their components using the graphviz library. It enables users to visualize the structure and interactions of modules, making it easier to understand complex systems.
**Dynamic Graph Generation:** The ModuleGraph class dynamically generates a graph representation of Python modules, including their submodules and components.
**Dependency Visualization:** It visualizes dependencies between modules, submodules, and components, helping users understand how different parts of the system interact with each other.
**Graphviz Integration:** Uses the graphviz library to create and render graphs in various formats (e.g., PNG), allowing for customization and easy sharing of visualizations.
**Error …
=> feature(dspy): generate a graphical representation of modules

dsp/modules/hf_client.py
This should fix the bug specified in https://github.com/stanfordnlp/dspy/issues/626. It looks like there was a potential fix with https://github.com/stanfordnlp/dspy/pull/627, but it was never merged in.
It also adds `api_base` and `api_key` to the constructor, matching the pattern for `Anyscale`.
=> fix(dspy): together client response parsing

dspy/retrieve/weaviate_rm.py
Maintain backward compatibility with v3 client.
Fix #787
=> feat(compatibility): Add compatibility with Weaviate client v4.

docs/api/retrieval_model_clients/WatsonDiscovery.md, dspy/retrieve/watson_discovery_rm.py
This feature allow to search and retrieve documents stored in Watson Discovery
=> feature(dspy): added retrieval module for Watson Discovery

docs/api/language_model_clients/PremAI.md, dsp/modules/premai.py
This PR adds an improvement to `dsp.modules.prem.PremAI` by introducing using Prem Prompt Templates throughout dspy calls.
=> Improvement: Prem Templates

docs/api/language_model_clients/AzureOpenAI.md, dsp/modules/azure_openai.py, dummy.csv
Added support for using Azure AD to connect to Azure OpenAI model.
https://github.com/stanfordnlp/dspy/issues/1051
=> feat(dspy): added support for managed identity in AzureOpenAI

dsp/modules/sentence_vectorizer.py, dspy/datasets/dataloader.py
This PR adds support for Prem AI Embeddings in DSPy `modules.sentence_vectorizer`
=> Prem AI Vectorizer support

docs/api/retrieval_model_clients/MyScaleRM.md, dspy/retrieve/MyScaleRM.py
There were some issues related to the cache. Now, I have updated the code a little and tested it. The cache running as expected.
There were also some bugs in the retriever but Now I have resolved these and tested.
=> fix: Remove cache issue and retriever bugs

dsp/utils/utils.py, examples/longformqa/utils.py, pyproject.toml, setup.py
@isaacbmiller It seems like the ruff restrictions are pretty strict and we can we more lenient with them so adding an updated ruff config. Let me know if something needs to be added or removed.
=> Relax ruff requirements and patch import positions

dsp/modules/hf_client.py
Solves issue: https://github.com/stanfordnlp/dspy/issues/1254
=> hotfix(dspy): update Together client self.kwargs to include "model"

dsp/modules/gpt3.py
Add base_url alias for api_base in OpenAI LM interface.
base_url takes priority.
=> add base_url alias for OpenAI LM

dspy/predict/langchain.py
patch for #1265 . Change suggested by @drmwilke and @rhamnett!
=> patch metaclass conflict

docs/docs/deep-dive/retrieval_models_clients/QdrantRM.mdx
=> docs: Added QdrantRM to the retrieval model docs

dspy/predict/avatar/avatar.py, dspy/predict/avatar/models.py, dspy/predict/avatar/signatures.py, dspy/teleprompt/__init__.py, dspy/teleprompt/avatar_optimizer.py, examples/agents/avatar_langchain_tools.ipynb
Adding support for Avatar Actor optimization for optimal tool usage using comparator based optimization that [Avatar](https://arxiv.org/abs/2406.11200) proposes. 
This also comes with thread-safe evaluator for module like Avatar that keep modifying their signature during execution. Using `dspy.Evaluate` doesn't work for such modules because it works on evaluating the pass argument and not the deepcopy of it. We do not want to change that so added a separate implementation as part of optimizer class.
Adding a step by step guide for Avatar Optimizer module for user to navigate with.
Evals for Arxiv QA:
Evals for Search QA:
=> Add support for Langchain Tool use Optimization via Avatar

dsp/modules/gpt3.py
Set http_client on openai to support http_proxy
=> http client added to GPT3

dspy/predict/react.py
- Fixes issue where model responds with literally `Finish[answer]`, instead of having the `answer` be the answer. 
- Fixes issue where the model generates more than one thought, action, or observation.
=> Fixed some bugs in the ReAct module

docs/docs/deep-dive/retrieval_models_clients/ChromadbRM.mdx
Some links in documentation are broken, here is a small PR to update one of them.
An update of the reference to the page about ChromaDB embeddings.
=> docs(ChromadbRM): change reference to chromadb embeddings

dspy/retrieve/chromadb_rm.py
Fix #1353
Remove the import from `dspy` to directly import required classes.
=> fix(dspy): chromadb_rm import error (#1353)

docs/api/local_language_model_clients/LlamaCpp.md, dsp/modules/__init__.py, dsp/modules/llama.py, dsp/modules/lm.py, dspy/__init__.py, pyproject.toml
A continuation of these two:
https://github.com/stanfordnlp/dspy/pull/862
https://github.com/stanfordnlp/dspy/pull/1154
Addressing their pr comments
=> Llama CPP Support - Addressed some PR Comments - Extending 2 other PRs

docs/api/language_model_clients/MultiOpenAI.md, dsp/modules/__init__.py, dsp/modules/multi_openai.py, dsp/modules/openai_compatible.py, dspy/__init__.py
Add OpenAICompatible, likes GPT3, but each instance uses a separate cache.
Allow to use multi OpenAICompatible LLM service with different base_url
related #744, #915
=> add OpenAICompatible

docs/docs/building-blocks/6-optimizers.md, dspy/predict/langchain.py, dspy/predict/predict.py, dspy/primitives/module.py, dspy/retrieve/retrieve.py
Adds save_field_meta default to `Retrieve`, debugging issue #1386.
=> Debugging Issue #1386

dsp/modules/mistral.py, dummy.csv
Removing unused imports and updating the imports in the mistral module file to make sure it can be run successfully after the current mistral migration updates.
=> fix(dsp): update imports after mistral migration update

README.md, dspy-production-usecases.md
...
- [] Title of your PR / MR corresponds to the required format
=> docs(dspy): add production usecases md

README.md
Changing the subchapters from 5.a - 5.c to 6.a - 6.c
=> Chore: Adjust subchapters in readme, they were wrong.

docs/docs/dspy-usecases.md
...
- [] Title of your PR / MR corresponds to the required format
=> docs(dspy): Make usecase page formatting easier to read and add usecases

docs/docs/dspy-usecases.md
...
- [] Title of your PR / MR corresponds to the required format
=> chore: Update dspy-usecases.md

docs/docs/cheatsheet.md, dspy/predict/retry.py, dspy/primitives/assertions.py, examples/longformqa/longformqa_assertions.ipynb, examples/qa/hotpot/hotpotqa_with_assertions.ipynb, examples/quiz/quiz_assertions.ipynb, examples/tweets/tweets_assertions.ipynb
DSPy Assertions updates
combines PRs #1085  and #1372 and patches #1470 , #514 , #1319
DSPy Assertions are compatible with MIPROv2 optimizer and dspy experimental mode
=> Assertions patches

dspy/evaluate/evaluate.py, tests/evaluate/test_evaluate.py
Fix rendering of evaluation results Pandas DataFrames in console environments
Fixes #1449
=> Fix rendering of evaluation results Pandas DataFrames in console environments

dsp/modules/gpt3.py
Did not test or think about this exhaustively, but it was enough to get it to work.
=> feat(dspy): support o1 parameters

docs/docs/dspy-usecases.md
Add https://raw.sh/posts/chess_puzzles
=> Add DSPy+finetuning blog post to use cases

docs/api/language_model_clients/Snowflake.md, docs/api/retrieval_model_clients/SnowflakeRM.md, dsp/modules/snowflake.py, dspy/retrieve/snowflake_rm.py, dummy.csv
Refactoring the Snowflake integration:
- Authentication: now takes authenticated session object instead of user credentials
- LM Models: support for additional models and fine-tuned models by removing strict error handling
- RM Internals: updated RM implementation to use Cortex Search hybrid retrieval service instead of basic similarity functions
=> refactor(dspy): updating snowflake LM and RM implementations

README.md
Added the link to the Replit Blog on LLM Code Repair which uses DSPy
=> Add Replit LLM Code Repair link

dspy/experimental/__init__.py
=> Patch synthesizer import typo

dspy/predict/program_of_thought.py, dspy/primitives/python_interpreter.py
adds more comprehensive support for PythonInterpreter for dspy.ProgramOfThought
patches #1530 , #1534, #1535
=> patches python interpreter to support additional syntax

docs/api/language_model_clients/langfuse.md
- Updated links and descriptions
- Added link to DSPy cookbook in Langfuse docs
=> docs: update langfuse.md

docs/docs/dspy-usecases.md
Added Pretrain to the list of company usecases
=> Add pretrain to the list of companies using DSPy

docs/docs/faqs.md
=> Update faq docs with new cache info

README.md
Thought this resource is useful to be linked to the README.
=> Add Berkeley LLM Agents class lecture to the README

docs/docs/tutorials/examples.md, docs/docs/tutorials/summarization.md
This PR adds a tutorial for the summarization task that is built by composing a Metric program and a Summarization program.
=> Add a tutorial for summarization task

dspy/predict/multi_chain_comparison.py
=> add support for reasoning/rationale

pyproject.toml, setup.py
Bump version to be consistent with pypi release.
=> Bump version

docs/docs/js/runllm-widget.js, docs/mkdocs.yml
Add support for AI Search via Ask AI
=> Add support for Ask AI in mkdocs

docs/docs/deep-dive/optimizers/bootstrap-fewshot.md
Minor updates to the BootstrapFewShot docs with the goal of improving the clarity.
=> Update BootstrapFewShot docs

docs/docs/tutorials/other_tutorial.md
Resources that cover the integration of custom metrics to ensure that the application’s outputs meet tighter standards, addressing critical aspects like bias detection and coherence.
The new resources include:
- Article on Medium
- Repository
- Youtube video
=> Added new resources on prompt optimization leveraging G-Eval metrics

dspy/clients/databricks.py
=> Minor lint fixes to dspy/clients/databricks.py

docs/mkdocs.yml
Add suppport for google analytics
=> Add suppport for google analytics

docs/mkdocs.yml
=> added the changes for site description

dspy/datasets/dataset.py
A few minor fixes:
- Use `or` syntax instead of long if ... else
- Using double qoute instead of single quote
- Deleting dead code
- Deleting non-interpretable comment
=> Minor style fix on dataset

dspy/datasets/gsm8k.py
A few minor fixes:
- Double quote instead of single quote.
- No dead code should be preserved.
- The constructor doesn't need to have `-> None` type hint, and `super().__init__()` is redundant because it is not inheriting from anything.
=> Minor style fixes to gsm8k

dspy/predict/react.py
A few minor style fixes for better readability:
- No mix use of single and double quote.
- Avoid trailing `_` at variable name.
- No space on empty lines.
=> Minor dspy react style fixes

examples/multi-input-output/beginner-multi-input-output.ipynb
the original url shows "404 - Not found"
update with the new one
=> fix the 404 issues of "cheatsheet" urls

dspy/utils/asyncify.py
=> Add a docstring for asyncify

dspy/datasets/hotpotqa.py, dspy/datasets/math.py
Minor lint fixes, no logic change involved.
=> Minor style fixes on hotpotQA and math dataset

docs/docs/tutorials/saving/index.md, docs/mkdocs.yml
Add saving tutorial for the reworked DSPy saving. This PR depends on #1889
=> Add dspy saving tutorial

dspy/evaluate/evaluate.py
Many public classes/functions are missing decent docstring, as we are improving the developer experience, we should add those. 
We may want to get community help on docstring efforts.
=> Add docstring for dspy evaluate

docs/docs/community/community-resources.md, docs/docs/community/use-cases.md
This fork broadens DSPy's use cases and community-driven content, specifically improving access for non-technical users through a streamlined, low-code environment. Customer feedback highlights DSPy's strong adoption within the Relevance platform, prompting the creation of a tutorial which demonstrates its application in building production-ready agents—evaluation results show implementations achieving 80% human-level email quality and reducing agent development time by 50%. Sharing this tutorial also shows users how to build their own self-improving agents using DSPy.
=> Extend use-cases and community content with Relevance AI DSPy blogs and tutorials

poetry.lock, pyproject.toml, requirements-dev.txt
This PR is to update litellm dev dependencies
cc @CyrusNuevoDia
=> update: update litellm

dspy/adapters/chat_adapter.py, dspy/adapters/json_adapter.py, dspy/adapters/utils.py, dspy/evaluate/metrics.py
Closes #7815 and #2825 and #7742
Fixes a bug from #7679
=> Improve Adapters (parse_value) and fix bugs & typos

dspy/teleprompt/infer_rules.py
Some minor styles fixes:
- Replace usage of `print` by `logger.info`
- Break long string into multiple lines
- sort the imports
=> Fix lint of the InferRules optimizer

docs/docs/api/modules/ReAct.md, docs/docs/api/optimizers/InferRules.md, docs/mkdocs.yml, docs/scripts/generate_api_docs.py
It's not reflected in docsite before this PR
=> Expose InferRules

dspy/adapters/base.py
Style fix in order to enable style check:
1. no relative imports
2. explicitly raise error instead of using `assert`
3. Better error message
4. indent correctly
=> Style fix for base adapter

dspy/clients/lm_local.py, dspy/dsp/colbertv2.py, dspy/predict/multi_chain_comparison.py, dspy/predict/parallel.py, dspy/predict/program_of_thought.py, dspy/retrieve/chromadb_rm.py, dspy/retrieve/deeplake_rm.py
Fix TID252 and F401 violations
https://docs.astral.sh/ruff/rules/relative-imports/
https://docs.astral.sh/ruff/rules/unused-import/
=> Fix TID252 and F401 violation

dspy/propose/dataset_summary_generator.py, dspy/propose/grounded_proposer.py, examples/outdated_v2.4_examples/tweets/tweet_metric.py
Fixes violations of https://docs.astral.sh/ruff/rules/multiple-statements-on-one-line-colon/
=> Fix E701 rule

dspy/clients/lm.py, dspy/predict/predict.py, tests/clients/test_lm.py, tests/predict/test_predict.py
This PR enables the serialization of dspy.LM to fix the issue of model saving.
Resolve #7852
=> Fix save predict model with LM

docs/docs/api/adapters/Adapter.md, docs/docs/api/adapters/ChatAdapter.md, docs/docs/api/adapters/JSONAdapter.md, docs/docs/api/primitives/History.md, docs/docs/api/signatures/Signature.md, docs/mkdocs.yml, docs/scripts/generate_api_docs.py
Expose `dspy.History` in API documentation, and also some other API changes
=> Expose `dspy.History` in API documentation, along with some other API changes

dspy/adapters/base.py, dspy/adapters/chat_adapter.py, dspy/adapters/json_adapter.py, dspy/clients/lm.py, dspy/predict/predict.py
This PR updates type hints as well as some fixes
- Add type hints to public methods of Adapter
- Fix inversed dependency of BaseAdapter; BaseAdapter should not know anything about JsonAdapter
- Removed unused utils
=> Enhance type hints of adapters

dspy/teleprompt/utils.py
=> Fix saving issue

dspy/dsp/utils/dpr.py
Methods in dpr.py is still in use but the file has some import errors. This PR fixes the errors.
=> Fix undefined variables in dsp/utils/dpr.py

dspy/teleprompt/mipro_optimizer_v2.py, dspy/utils/callback.py
Removed mlflow log_metrics calls and fix signature for evaluation callback
=> Fix unnecessary mlflow calls

poetry.lock, pyproject.toml
Move required dependencies higher and remove litellm from optional dependencies.
=> Reorder dependencies

dspy/evaluate/evaluate.py, dspy/teleprompt/utils.py, tests/teleprompt/test_utils.py
Add optional argument callback_metadata to Evaluate.__call__ that will be used by evaluate callback
=> Add callback_metadata to evaluate

dspy/teleprompt/teleprompt.py, tests/teleprompt/test_teleprompt.py
Define following common interfaces to the Base Teleprompter
- compile: optimize DSPy program using trainset, childset and teacher program etc
- get_params: return hyperparameters of the teleprompter
=> Define compile and get_params to Teleprompter

poetry.lock, pyproject.toml, tests/primitives/test_python_interpreter.py
CVE "CWE-863: Incorrect Authorization" is applicable in litellm<1.60.3. Updating the minimal version of litellm to 1.60.3 would take care of this CVE and take the trouble out of the hands of the users.
Closes #7976
=> Maintenance: Update dependency LiteLLM for CVE

dspy/adapters/base.py, dspy/adapters/utils.py
To reduce noise for the incoming Adapter refactoring.
In a week, our adapter will be highly customizable, stay tuned!
=> Format adapters/base.py and adapters/utils.py

docs/docs/api/adapters/Adapter.md, docs/docs/api/models/LM.md, docs/docs/api/modules/ProgramOfThought.md, docs/docs/api/optimizers/BetterTogether.md, docs/docs/api/optimizers/BootstrapFewShot.md, docs/docs/api/optimizers/BootstrapFewShotWithRandomSearch.md, docs/docs/api/optimizers/BootstrapFinetune.md, docs/docs/api/optimizers/BootstrapRS.md, docs/docs/api/optimizers/COPRO.md, docs/docs/api/optimizers/Ensemble.md, docs/docs/api/optimizers/InferRules.md, docs/docs/api/optimizers/KNNFewShot.md, docs/docs/api/optimizers/LabeledFewShot.md, docs/docs/api/optimizers/MIPROv2.md
Include our recent API changes in the API reference doc.
=> Update api reference to reflect recent chagnes

poetry.lock, pyproject.toml
Revert the pin on numpy version
=> Fix numpy version issue

dspy/utils/usage_tracker.py
Model like `gemini` can have `usage.completion_tokens_details=None`, we need to handle this case.
=> Fix usage tracking error when some fields are None

dspy/adapters/base.py
Fix the output type hint for Adapter.format_demos
=> Fix the type of format_demos

tests/clients/test_lm.py
To reduce noise for the incoming PR. 
We will standardize and enable the strict style check by the end of April.
=> Small style fix for test_lm.py

dspy/clients/base_lm.py
=> Add max size for global history

dspy/dsp/utils/settings.py, dspy/evaluate/evaluate.py, dspy/predict/parallel.py, dspy/primitives/program.py, dspy/teleprompt/mipro_optimizer_v2.py, dspy/utils/parallelizer.py
=> Move provide_traceback into global settings

dspy/adapters/json_adapter.py
Extracts the json in the answer
=> Add regex to match json object - fixes issues caused by Azure OpenAI response structure

docs/docs/api/adapters/ChatAdapter.md, docs/docs/api/adapters/JSONAdapter.md, docs/docs/api/adapters/TwoStepAdapter.md, docs/docs/api/utils/StatusMessageProvider.md, docs/docs/api/utils/StreamListener.md, docs/mkdocs.yml, docs/scripts/generate_api_docs.py
=> Update documentation site

dspy/primitives/tool.py, tests/primitives/test_tool.py
Support async path in dspy.Tool
=> Support async in dspy.Tool

tests/clients/test_lm.py
We were not covering the test of the `logprobs` field, which is important while not commonly used.
=> Add missing test for logprob field in dspy.LM

docs/docs/learn/programming/language_models.md
Reference: https://docs.litellm.ai/docs/providers/gemini
=> Update language_models.md - Add Gemini (AIS) instructions

dspy/predict/react.py, dspy/primitives/tool.py, tests/predict/test_react.py
With this PR we are supporting async path in the ReAct module. 
Also fixed an issue that async tool path cannot execute sync tool, which should be allowed.
=> Support async path in dspy.ReAct

docs/docs/tutorials/mcp/index.md, docs/mkdocs.yml
=> MCP tutorial

dspy/predict/predict.py, tests/predict/test_predict.py
To make that even more actionable.
=> Improve the positional args error message for dspy.Predict

tests/signatures/test_signature.py
This small PR removes the duplicate unused signature test `test_signature_from_dict()`.
=> Remove duplicate unused signature test

docs/docs/tutorials/index.md, docs/docs/tutorials/streaming/index.md, docs/mkdocs.yml
Add a guide on how to enable streaming in DSPy.
=> Add streaming guide

docs/docs/tutorials/rl_papillon/index.ipynb
Remove unnecessary comma in `arbor.yaml`
=> Tutorial Fix

dspy/predict/react.py
This fixes a spelling mistake in the React module.
=> fix spelling typo in react module

dspy/clients/lm.py
=> Remove `LM.forward()`'s callback

docs/docs/tutorials/rl_multihop/index.ipynb, docs/docs/tutorials/rl_papillon/index.ipynb
Changes docs to show correct package name to fix install
- [] Title of your PR / MR corresponds to the required format
=> docs(dspy): Update installation instructions in RL tutorials to use 'arbor-ai' package

dspy/streaming/streamify.py, dspy/streaming/streaming_listener.py
Based on rule: https://github.com/stanfordnlp/dspy/pull/7885
=> Fix style errors of dspy/streaming

dspy/predict/__init__.py, dspy/predict/aggregation.py, dspy/predict/avatar/avatar.py, dspy/predict/avatar/models.py, dspy/predict/avatar/signatures.py, dspy/predict/best_of_n.py, dspy/predict/chain_of_thought_with_hint.py, dspy/predict/multi_chain_comparison.py, dspy/predict/parallel.py, dspy/predict/parameter.py, dspy/predict/program_of_thought.py, dspy/predict/react.py, dspy/predict/refine.py, pyproject.toml
=> Fix coding style in dspy/predict

dspy/dsp/colbertv2.py, dspy/dsp/utils/dpr.py, dspy/dsp/utils/metrics.py, dspy/dsp/utils/settings.py, dspy/dsp/utils/utils.py, pyproject.toml
=> Fix code style in dspy/dsp

docs/docs/api/optimizers/SIMBA.md, docs/mkdocs.yml, dspy/teleprompt/simba.py
Add api reference for dspy.SIMBA and update the docstring format of SIMBA
=> Add api reference for dspy.SIMBA

pyproject.toml, tests/adapters/test_json_adapter.py, tests/adapters/test_two_step_adapter.py, tests/caching/test_litellm_cache.py, tests/clients/test_cache.py, tests/clients/test_databricks.py, tests/clients/test_embedding.py, tests/clients/test_inspect_global_history.py, tests/clients/test_lm.py, tests/conftest.py, tests/docs/test_mkdocs_links.py
Fixes:
- tests/adapters
- tests/caching
- tests/callback
- tests/clients
- tests/datasets
- tests/docs
Based on rule #7885
=> Style fixing for tests/

pyproject.toml, tests/evaluate/test_evaluate.py, tests/evaluate/test_metrics.py, tests/examples/test_baleen.py, tests/metadata/test_metadata.py, tests/predict/test_aggregation.py, tests/predict/test_best_of_n.py, tests/predict/test_chain_of_thought.py, tests/predict/test_parallel.py, tests/predict/test_predict.py, tests/predict/test_program_of_thought.py, tests/predict/test_react.py, tests/predict/test_refine.py, tests/primitives/test_example.py, tests/primitives/test_module.py, tests/primitives/test_program.py, tests/primitives/test_python_interpreter.py, tests/primitives/test_tool.py, tests/propose/test_grounded_proposer.py
Style fixes for:
- tests/evaluate
- tests/examples
- tests/metadata
- tests/predict
- tests/primitives
- tests/propose
Based on rule defined in #7885
=> Style fixing for tests/ (part 2)

dspy/datasets/hotpotqa.py
=> fix: use forked hotpotqa to bring dataset alive #8233

dspy/teleprompt/mipro_optimizer_v2.py, dspy/teleprompt/teleprompt_optuna.py
Optuna will be moved to an optional dependency. Move optuna inside methods
```python
import dspy
import sys
"optuna" in sys.modules # False
```
=> Avoid importing optuna in dspy import

docs/docs/api/modules/CodeAct.md, docs/mkdocs.yml, dspy/predict/code_act.py
=> Add api doc for CodeAct

dspy/primitives/module.py
=> Fixes utf-8 formatting issues in optimization saves

docs/docs/api/modules/CodeAct.md
Add developer guide for CodeAct
=> Add developer guide for CodeAct

dspy/primitives/program.py
Convert docstring of Module.batch into google docstring style
=> Convert docstring for Module.batch

dspy/predict/code_act.py, dspy/predict/program_of_thought.py, dspy/primitives/python_interpreter.py, dspy/teleprompt/mipro_optimizer_v2.py, tests/adapters/test_base_type.py, tests/primitives/test_python_interpreter.py
=> Fix lint failures

tests/streaming/test_streaming.py
the test was broken because PR was up before checking in the async settings PR.
=> Fix the streaming test

dspy/primitives/program.py, tests/primitives/test_module.py
Show a warning if users directly call forward method of dspy Module
=> Show warning if forward is directly called

pyproject.toml
=> Add missing rule comment

dspy/dsp/utils/utils.py
Remove unused dotdict implementation
=> Remove commented out old dotdict

dspy/predict/chain_of_thought.py, dspy/predict/multi_chain_comparison.py, dspy/predict/predict.py, dspy/predict/program_of_thought.py, dspy/predict/react.py, dspy/primitives/__init__.py, dspy/primitives/module.py, dspy/streaming/streamify.py, dspy/streaming/streaming_listener.py, dspy/teleprompt/bettertogether.py, dspy/teleprompt/bootstrap_finetune.py, dspy/teleprompt/grpo.py, dspy/utils/asyncify.py, tests/primitives/test_module.py
Rename modules.py to module.py
=> Rename modules to module

dspy/predict/chain_of_thought.py, dspy/predict/code_act.py, dspy/predict/predict.py
=> Fix signature input type

.gitignore
Add CLAUDE.local.md to .gitignore
=> Add CLAUDE.local.md to .gitignore

dspy/streaming/messages.py, tests/streaming/test_streaming.py
resolve #8424 
The old status communication was somehow blocking the event loop, which resulted in the status start/end message to come at the same time.
=> Fix the error that status message streaming was blocking 

docs/docs/tutorials/email_extraction/index.md, docs/mkdocs.yml
This PR introduces a new real-world tutorial for extracting information from emails.
=> Add real world tutorial for email extraction

dspy/primitives/prediction.py
Update the docstring of dspy.Prediction and explain the behavior of comparison operations
=> Document comparison operations of dspy.Prediction

docs/docs/tutorials/real_world_examples/index.md, docs/mkdocs.yml
This PR introduces an overview page for "Real-World Examples"
=> Add real-world example overview page

docs/docs/index.md
Currently we are using a mixed style of single and double quote, we should be consistent.
=> Consistently use double quotes in DSPy docsite landing page

dspy/predict/program_of_thought.py
Saw it in the API docs here: https://dspy.ai/api/modules/ProgramOfThought/
Thank you for your work
=> Fix typo: "reuires" → "requires" in program_of_thought.py

dspy/signatures/signature.py
=> PR for issue #8487

docs/docs/cheatsheet.md
I believe this cheatsheet is a great resource for LLMs to learn the newest DSPy syntax.
To bring it up to date, I removed all deprecated stuff from it and added a little snippet for the new-ish SIMBA optimizer. I also refactored the LLM-as-a-judge example to use type annotations, since this makes sense there, in my opinion.
=> Updated Cheatsheet

docs/docs/community/use-cases.md
We recently officially released **MedVAL**, where we use **DSPy's CoT** and **bootstrap fine-tuning** for training LMs (self-supervised) to validate AI-generated medical text, achieving **near physician-level reliability**.
**Paper:** [Expert-level validation of AI-generated medical text with scalable language models](https://www.arxiv.org/abs/2507.03152)
**Code:** [GitHub](https://github.com/StanfordMIMI/MedVAL)
**MedVAL-Bench Dataset:** [HuggingFace](https://huggingface.co/datasets/stanfordmimi/MedVAL-Bench)
**MedVAL-4B model:** [HuggingFace](https://huggingface.co/stanfordmimi/MedVAL-4B)
=> Included MedVAL references to DSPy Use Cases

docs/docs/tutorials/conversation_history/index.md, docs/docs/tutorials/core_development/index.md, docs/docs/tutorials/index.md, docs/mkdocs.yml
Add tutorial around `dspy.History`
=> Add tutorial on managing conversation history

docs/docs/tutorials/conversation_history/index.md
"What is the capital of France?" missmatched with the actual question demonstrated and was a bit confusing to me.
I suggest this instead.
=> change paris str to question variable for first message index.md

dspy/primitives/base_module.py, dspy/primitives/python_interpreter.py
to support utf-8 on loading saved optimizations and dspy.ProgramOfThought
=> fix UnicodeDecodeError: 'gbk' codec can't decode

dspy/adapters/types/base_type.py
This fixes the issue I shared in https://github.com/stanfordnlp/dspy/issues/8570
=> faster json parsing for images in chatadapter

docs/docs/api/optimizers/SIMBA.md
Add link for https://blog.mariusvach.com/posts/dspy-simba to the SIMBA API reference
=> Add SIMBA blog link

dspy/clients/lm.py
Add openai/gpt-5 as reasoning model that requires max_tokens >=20,000 and temperature 1.0
=> Add gpt-5 as reasoning model

docs/docs/api/models/LM.md, docs/docs/api/optimizers/GEPA.md, docs/mkdocs.yml, docs/requirements.txt, dspy/teleprompt/__init__.py, dspy/teleprompt/gepa/__init__.py, uv.lock
=> Add API ref for GEPA

dspy/teleprompt/simba.py
Current code had inconsistent type hints and doc string
=> Add type hints and fix doc string of SIMBA

dspy/teleprompt/gepa/gepa.py
Fix incorrect docstring style of GEPA class
=> Fix GEPA docstring format

docs/docs/tutorials/index.md
Fix unrecognized tutorial links
=> Fix unrecognized links

dspy/evaluate/evaluate.py
This addresses issue 8688. 
With these changes we add support for saving files locally to csv or json. 
Some code to merge predictions and results is extracted to be reused.
=> 8688 csv output

docs/docs/learn/programming/language_models.md, docs/docs/learn/programming/signatures.md
Started working on Dspy. So started raising PR and added commits for the changes I think will make it clean.
1. In the "https://dspy.ai/learn/programming/language_models/" I saw the lm.history different than what was given so added those.
2. In the "https://dspy.ai/learn/programming/signatures/" , I have added simple lines in toxicity to show how to use that feature, with output too.
=> Minor document changes

docs/docs/community/use-cases.md
Infinitus leverages DSPy to build and optimize healthcare AI agents.
=> Infinitus AI agents

dspy/teleprompt/gepa/gepa.py
Clarified warning about using trainset as valset and added guidance on valset size.
=> Enhance logging for valset usage in GEPA

docs/docs/learn/programming/tools.md
=> Style fix for tool page

docs/docs/learn/programming/language_models.md
Add guide on how to use responses API
=> Update documentation to include responses api

docs/docs/tutorials/email_extraction/index.md
Removed EmailInsight class definition from the tutorial.
=> Remove EmailInsight class from email extraction tutorial

dspy/evaluate/evaluate.py, tests/evaluate/test_evaluate.py
=> Display metric=0 in eval table

dspy/adapters/types/citation.py
=> Fix example code for Citations

dspy/clients/lm.py, tests/adapters/test_json_adapter.py
=> Fix the issue of response_format for responses api
