stanfordnlp/dspy

- dsp/templates/template_v2.py
- dsp/templates/template_v3.py
> Fix typo in template_v2.py

- dsp/modules/__init__.py
- dsp/modules/hf.py
- dsp/modules/hf_client.py
Addresses #40 and our previous issues of not wanting hf transformers to be a dependency for dsp.
minor bug fix on using hf models on cpu.
> refactor(hf-models): export hf module without the need for deps

- dsp/utils/ann_utils.py
addresses #41 
reference: https://github.com/facebookresearch/faiss/blob/main/faiss/IndexScalarQuantizer.cpp
> bug(faiss): mismatch in types & args instead of kwargs

- .gitignore
- dsp/modules/__init__.py
- dsp/modules/sbert.py
- dsp/primitives/search.py
- dsp/utils/settings.py
- intro.ipynb
The PR does the below
- Introduces re-ranker that couples with existing retrieval. 
- updated the intro notebook for usage
```
sbert_reranker = dsp.SentenceTransformersCrossEncoder("cross-encoder/ms-marco-MiniLM-L-12-v2")
dsp.settings.configure(lm=lm, rm=rm, reranker=sbert_reranker)
reranked_passages = dsp.retrieve("When was the creator of Hadoop given an award?", k=3)
```
> feature(search): sbert re-ranker

- docs/language_models_client.md
- docs/modules.md
- docs/retrieval_models_client.md
- docs/teleprompters.md
- docs/using_local_models.md
Minor standardization changes:
- Add ToCs for quick navigations
- `Arguments` -> `Parameters`
- parameter type hints are in italic to improve readability
- `GPT3(...)` constructor -> `OpenAI(...)`
- add links to references for quick nav
- define `Quickstart` and `Usage` snippets at the top of doc modules and `Examples` at the end of doc modules.
> enhancement(documentation): Minor fixes

- README.md
- dspy/retrieve/pinecone_rm.py
- setup.py
Firstly thank you for the great library. I was interested in using the Pinecone retrieval component and ran into several issues, including:
* Hardcoded api/env placeholders
* Undeclared dependency (reasonably to not force pinecone install for other users)
* Lack of support for multiple queries (used only results of first embedding)
* Deprecated openai embedding kwargs
etc.
This aims to address these issues by overhauling the pinecone retrieval class in many ways: fixing the hardcoded keys, including the dependency as optional so you can use `pip install dspy-ai[pinecone]`, and implementing similar behaviour to `dsp.retrieveEnsemble` to allow search against a query list, along with other code quality improvements.
> Pinecone retrieval improvements

- .gitignore
- dspy/retrieve/you_rm.py
- requirements.txt
So I wasn't entirely sure on the difference between the modules in `dsp` vs the retriever module example of pinecone in `dspy`. I went ahead and followed what seemed to be the newer pattern. One thing to note about this implementation is if multiple queries are indeed passed into the new retriever we do not have the ability to rerank the results across queries so we return the passages from query 1 then the passages from query 2. I could also just raise a runtime error if that is a more desirable pattern. Let me know!
> add you retriever module

- dsp/utils/settings.py
handling multithreading within dsp.settings in setting config
modified relevant methods that involve thread->stack dictionary
refers to this [issue](https://github.com/stanfordnlp/dspy/issues/105)
> modified threading handling in config for multithreaded flask

- dsp/modules/hf_client.py
This PR lets the user specify what arguments are provided to the HTTP call to the TGI server. My use case is HTTP basic auth, so I need to pass the relevant kwarg through.
> Allow passing of kwargs for HF TGI request

- dsp/modules/cache_utils.py
Fixes the error mentioned here https://github.com/stanfordnlp/dspy/issues/181#issuecomment-1776250172
i.e. 
```
File "<snip>/dspy/dsp/modules/hf_client.py", line 93, in <module>
@NotebookCacheMemory.cache(ignore=['arg'])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: noop_decorator() got an unexpected keyword argument 'ignore'
```
Now, if `NotebookCacheMemory.cache` is a `noop_decorator`, it can be called either with or without args/kwargs (i.e. `@NotebookCacheMemory.cache(ignore=["arg"])` or `@NotebookCacheMemory.cache`).
> Allow no-op decorator to take arguments

- dspy/signatures/signature.py
-supports new DSPy signature declarations (`dspy.Signature("{inputs}-> {outputs}"`)
methods added:
-`attach()`: defining field with prefix and description 
-`add_field()`: supports pretending and appending InputFields and OutputFields
(note for reference - currently, modifies signature in-place as the `attach()` functionality supports chaining)
> modified signatures to handle new DSPy signature format

- dspy/evaluate/evaluate.py
- dspy/teleprompt/bootstrap.py
-permits up to 5 errors during 1) evaluation and 2) bootstrapping and then raises actual error, halting program for user to fix the error
> added proper error handling within evaluate and bootstrap

- README.md
- dspy/retrieve/qdrant_rm.py
- setup.py
This PR intends to add Qdrant as a supported retrieval mechanism.
[Qdrant](https://qdrant.tech/) is a high-performance vector database & vector similarity search engine.
The [Qdrant client library](https://github.com/qdrant/qdrant-client) has built in support for generating sentence embeddings using [FastEmbed](https://github.com/qdrant/fastembed). 
This implementation uses the `query_batch` mechanism to perform similarity searches in a batch and return the relevant docs.
> feat: Add Qdrant support for retrieval

- dsp/modules/gpt3.py
- requirements.txt
Have had this happen for multiple 3.5 trials where openai just craps out for a couple requests. Thought this may help. 
```
80     self._interpret_response_line(
81   File "/home/dakisho/.pyenv/versions/3.11.6/lib/python3.11/site-packages/openai/api_requestor.py", line 775, in _interpret_response_line
82     raise self.handle_error_response(
83 openai.error.APIError: Bad gateway. {"error":{"code":502,"message":"Bad gateway.","param":null,"type":"cf_bad_gateway"}} 502 {'error': {'code': 502, 'message': 'Bad gateway.', 'param': None, 'type': 'cf_bad_gateway'}} {'Date': 'Wed, 01 Nov 2023 09:23:59 GMT', 'Content-Type': 'application/json', 'Content-Length': '84', 'Connection': 'keep-alive', 'X-Frame-Options': 'SAMEORIGIN', 'Referrer-Policy': 'same-origin', 'Cache-Control': 'private, max-age=0, …
```
> fix 502 openai error

- dsp/templates/template_v2.py
This change removes the `---` that are added between every KNN example in a prompt. These dashes were not present in prompts generated by DSP programs implementing KNN few shot, but are present in prompts generated by DSPy programs implementing KNN few shot.
Previously with DSP (and with this change), KNN fewshot demos would (and will) look like:
```
Answer questions with short factoid answers.
---
Follow the following format.
Question: ${question}
Answer: often between 1 and 5 words
---
Question: On the coast of what ocean is the birthplace of Diogal Sakho?
Answer: Atlantic Ocean
Question: Which is taller, the Empire State Building or the Bank of America Tower?
Answer: Empire State Building
Question: Samantha Cristoforetti and Mark Shuttleworth are both best known for being first in …
```
> Remove --- between examples in KNN few-shot prompts

- README.md
This is a trivial change– I just reversed the chronological order of the list of links to references. Previously, it was: oldest -> newest, and I just swapped it: newest -> oldest.
Reason: people often click the first link in a list to read more something. So it probably makes sense to have the thing we'd actually want folks to read listed first (the most recent preprint).
> README tweak, update order of links out to references

- dspy/retrieve/qdrant_rm.py
TL;DR: Fixed Qdrant integration by simply adding a k argument to the forward function QdrantRM class
Currently, the Qdrant integration fails to work, throwing a TypeError when using Qdrant as retriever model.
In dspy/retrieve/retrieve.py, passages are retrieved using a retriever model (in this case Qdrant) with a list of queries, and with the argument `k=self.k`. 
```
def forward(self, query_or_queries):
queries = [query_or_queries] if isinstance(query_or_queries, str) else query_or_queries
queries = [query.strip().split('\n')[0].strip() for query in queries]
passages = dsp.retrieveEnsemble(queries, k=self.k)
return Prediction(passages=passages)
```
In dspy/retrieve/qdrant_rm.py, the following forward function was implemented previously.
```
def forward(self, query_or_queries: Union[str, …
```
> Fixed Qdrant integration by adding "k" as an optional argument in Qdrant forward method

- examples/nli/scone/scone-cot_fewshot-turbo-gpt4-demos.json
- examples/nli/scone/scone.ipynb
Hi @okhat!
This is a simple example showing how to use a different (and presumably more powerful) model for bootstrapping examples than the one being used for the central predictions.
The example task is the ScoNe "one scoping negation" category, which is one of the hardest categories in ScoNe. Zero-shot, turbo is at chance, and using turbo to bootstrap full CoT examples seemed not to work well, but using GPT-4 for bootstrapping (a possibility you made me aware of!) took performance all the way north of 85% accuracy (and one of my runs was at 93%). This extremely high, but everything seems to be set up correctly, so this seems like a nice illustration of the power of this strategy.
Do let me know if I should make an adjustments to the way the notebook is set up. The hope is that this is …
> Bootstrapping ScoNe CoT demos with a separate LLM from the main one

- dsp/modules/gpt3.py
Issues:
After the change to support `openai==1.x` (#258), https://github.com/stanfordnlp/dspy/blob/main/dsp/modules/gpt3.py#L70 will always trigger assert when `api_provider == 'azure'`.
Changes:
- Fix this nit.
- Move `openai.api_type = api_provider` to better support switching api providers.
Remaining issues:
- `openai==1.x` suggests using client to manage configurations. It seems that the global configurations do not work for OpenAI Azure service any more. #258 is not fully solved.
> Fix a nit for openai azure support.

- .github/workflows/build_package.yml
- pyproject.toml
Addresses issue: https://github.com/stanfordnlp/dspy/issues/154
Goals: Allow poetry integration. Setup documentation dependencies, allow dev dependencies to be added in future. PEP-compliant. 
Also adds github action to ensure project can compile/build, dependencies are installed properly.
> Add `pyproject.toml`, github action for compiling. 

- README.md
- dspy/retrieve/mongodb_atlas_rm.py
- setup.py
Added MongoDB Atlas Retrieval Model. Currently only supports OpenAI embedding provider.
> (250) - Add MongoDB Atlas Retrieval Model

- .pre-commit-config.yaml
- CONTRIBUTING.md
- pyproject.toml
- Adding base configurationfor the new advanced pre-commit hook (.toml + pre-commit.yaml)
- Adding base config for pytests coverage reporting (.toml)
- Adding `CONTRIBUTE.md` to start explaining the basic process for setting up the pre-commit hook
> ops(dspy): adding pre-commit + contrib.md initialization

- .github/workflows/precommits_check.yml
- .pre-commit-config.yaml
- pyproject.toml
- aligning pre-commit version to py3.9 (do we need this version or can we start with >=3.10, which is x10 faster) and has lot's of nice features for typing etc
- activating pre-commit checks in the repo (you shall not pass principle)
> ops(dspy): activating pre-commit global check (and aligning to py3.9)

- dspy/teleprompt/signature_opt_bayesian.py
This PR makes the following changes:
1. Adds support for example aware metaprompting. Now users have the choice of using both data aware and example aware metaprompting, either together or separately. These choices can be specified with the `view_data` and `view_examples` flags.
2. Adds in a summarization step on top of data observations in order to condense observations into a 2-3 sentence summary. We've found that this helps to make suggested instructions better, potentially because the metaprompt is less bogged down by extra text. (thanks @XenonMolecule for this solution!)
> Adding example awareness to bayesian teleprompter

- dsp/evaluation/utils.py
This modification replaces the IPython import with a try-except block. If IPython is not available, it sets ipython_display to the built-in print function.
Related: https://github.com/stanfordnlp/dspy/pull/269
> Make the IPython dependency optional

- dspy/retrieve/weaviate_rm.py
This PR adds the `long_text` key to the `passages` returned by the WeaviateRM.
In dsp/primitives/search line 10: `passages = [psg.long_text for psg in passages]` throws an error without this -- maybe worth making a note of removing this. 
Not aware of the full context, but this PR will patch the WeaviateRM for the time being.
> [Bug Fix] WeaviateRM Patch, add `long_text` key to `passages`

- README.md
It seems more correct to describe the function flow this way, first we retrieve the context then we use it and the question to generate an answer, but I'm not sure, I'm reading the docs for the first time and may have misunderstood how DSPy works.. :-)
> Update README.md -> the `class RAG(dspy.Module)` section of the Docs

- dspy/evaluate/evaluate.py
- dspy/predict/predict.py
- dspy/predict/retry.py
- dspy/primitives/assertions.py
- dspy/teleprompt/bootstrap.py
- dspy/teleprompt/random_search.py
- examples/qa/hotpot/hotpotqa_with_assertions.ipynb
- examples/tweets/compiling_langchain.ipynb
**Tasks**
`dspy.Suggest(constraint, msg, is_metric)`
> Assertion-aware metrics and optimization

- dsp/modules/__init__.py
- dsp/modules/aws_lm.py
- dsp/modules/bedrock.py
- dspy/__init__.py
- pyproject.toml
Created two new LM classes:
- Bedrock
- AWSLM
Bedrock can be used with any Bedrock model once you have configured your AWS credentials with the AWS CLI. AWSLM exists so that we can add support for AWS Sagemaker in the future, which has a very similar API with minor parameter differences.
> feat(bedrock-lm): Added a LM for Bedrock and a base AWS LM class

- docs/guides/language_model_details/launching_vllm.md
- docs/using_local_models.md
The current documentation for running vLLM with DSPy suggests that the user start an API server via ```python -m vllm.entrypoints.api_server```. However, this leads to errors since the DSPy code assumes an OpenAI-Compatible API server. So the user should instead launch the server via ```python -m vllm.entrypoints.openai.api_server```.
> Small Fix to vLLM Launch Documentation

- dsp/modules/hf.py
- dspy/predict/chain_of_thought.py
Very cool project 💯 
This PR fixes a typo introduced in [#333](https://github.com/stanfordnlp/dspy/pull/333). The signature is undefined in this context.
Additionally, I moved the torch dependency to only be required when running the model locally through hf and not when a vllm endpoint is called.
> CoT fix + move torch dependeny when using vllm

- dspy/primitives/assertions.py
- dspy/primitives/program.py
Now, it is possible to write `assert_transform_module(module)` to transform a module to handle suggestions and assertions. The default behavior is implemented by the `backtrack_handler`, which automatically backtracks for failing assertions and suggestions.
> Easier api for transforming modules with assertions

- dsp/modules/cohere.py
Discussed on Discord. Removed `return_likelihoods` argument, per error @erika-cardenas found.
> Fix CohereAPIError

- dspy/datasets/__init__.py
- dspy/datasets/dataloader.py
Code Snippet:
```python
dl = DataLoader(
train_size = 0.5,
dev_size = 0.2,
test_size = 0.3   
)
dl.from_huggingface("databricks/databricks-dolly-15k")
print(len(dl.train))
print(len(dl.dev))
print(len(dl.test))
```
> Add support to load from any HF dataset and CSV

- docs/retrieval_models_client.md
- dspy/retrieve/chromadb_rm.py
I've updated the ChromadbRM retriever to be more flexible and fix a bug:
- **Flexibility with Embeddings**: Removed the direct dependency on OpenAI, allowing for the use of various embedding functions from [Chroma](https://docs.trychroma.com/embeddings). This change makes the retriever more adaptable to different needs.
- **Bug Fix**: Fixed issue #389 where `_get_embeddings` threw a TypeError due to an unexpected keyword argument 'engine'. This ensures smoother functionality.
This revision enhances ChromadbRM by introducing flexibility in embedding selection and resolving a critical error.
> Refactored ChromadbRM to use generic EmbeddingFunction

- dsp/modules/google.py
Followed the Cohere LM template. It doesn't look like you can sample multiple generations in one call to the API (linked the Google API docs I'm following in the code). Outside of that, I think it is a pretty standard implementation in sync with the other LMs.
Comment:
- Cool to get a better understanding of how `history` is stored as internal state to the LMs as a `list[dict[str, Any]]`. I would like to explore adding functionality around inspect_history next.
> Create Google LM

- dsp/modules/aws_lm.py
- dsp/modules/bedrock.py
Fixing bugs mentioned here where `n` and `max_tokens` throw errors when passed as `kwargs`:
https://github.com/stanfordnlp/dspy/issues/365
> Bedrock args hotfix

- pyproject.toml
If you try and add dspy with poetry to an existing project with existing datasets version already installed you may get poetry errors. For example, I tried installing into a project that depended on datasets > 2.15 and so I couldn't install dspy. This was recently fixed for openai version constraint in a similar  [PR](https://github.com/stanfordnlp/dspy/pull/347). Can we do the same for datasets? Im not sure if there was a reason it was pinned to 2.14. A better solution might even be > 2.14 but let me know.
PS: Is there a way to build the environment and run a series of unit tests? I did not see anything about that in the CONTRIBUTING.md. The pre-commit config just does linting/formatting as far a I can tell.
> fix(datasets): relax datasets version constraint

- dspy/retrieve/weaviate_rm.py
Lets you specify which text key to return from a call to `dspy.Retrieve`
This does not incur a breaking change thanks to the `Optional` typing and default argument value.
This will resolve https://github.com/stanfordnlp/dspy/issues/359.
> Allow custom text key to WeaviateRM - resolve issue #359

- dspy/teleprompt/signature_opt_bayesian.py
BUG FIX: Switching suggest_int --> suggest_categorical for suggesting the indices to use for our instruction / demo set in each optuna trial. This is because Optuna's suggest_int assumes that the performance of each selected number is related, which is not the case in our application. suggest_categorical does not have this built in assumption, which is what our application requires.
> [BUG FIX] Switching trial.suggest_int --> trial.suggest_categorical

- dspy/predict/chain_of_thought.py
- dspy/predict/predict.py
After the optimizers change the instruction we need to be able to save/load the optimized instructions.  Currently the original (unoptimized) instructions are loaded and only the demos are saved.
This is a quick fix that adds this change for Predict and Chain of Thought.  If more modules are added for instruction optimization then this fix will need to be added to those modules as well.
Thanks to @klopsahlong for help with testing/validating the changes!
> Added saving/loading instructions to Predict and Chain_Of_Thought

- dsp/modules/sentence_vectorizer.py
Adds a new vectorizer for [Cohere's Embed models](https://docs.cohere.com/reference/embed) analogous to OpenAIVectorizer. Details on the performance of the Embed 3 model can be found [here](https://txt.cohere.com/introducing-embed-v3/)
Of note, the Vectorizer interface doesn't specify whether a query versus a document is being embedded, but Cohere's embedding models produce different embeddings depending on the content you want to embed. The different options are in the docs, but taking this into account can product a fairly dramatic boost to performance.
> Add CohereVectorizer for Embed 3

- dspy/retrieve/retrieve.py
- dspy/retrieve/you_rm.py
The following code (snippet) follow the setup idiom currently used by dspy:
```python
class WebRag(dspy.Module):
NL_SEP = "\n----------\n"
super().__init__()
self.you_rm = dspy.Retrieve(k=5)
self.chain_of_thought = dspy.ChainOfThought(...irrelevant_signature...)
def forward(self, question: str):
web_context = self.NL_SEP.join(self.you_rm(question).passages)
out = self.chain_of_thought(web_context=web_context, question=question)
return out.answer
...
rm = YouRM(ydc_api_key=settings.YDC_API_KEY.get_secret_value())
lm = dspy.OpenAI(model=settings.LLM_MODEL, api_key=settings.OPENAI_API_KEY.get_secret_value())
dspy.settings.configure(lm=lm, rm=rm)
```
However, invoking this with a question string raises the following error:
```python
web_rag = WebRag()
out = web_rag("What …
```
> Bring YouRM .forward signature in-line with Retrieve child class .forward methods (add K kwarg)

- dsp/primitives/search.py
- dspy/retrieve/you_rm.py
This brings it in line with the behavior of other retriever implementations in `/retrieve`.
Related - we probably want to make dspy.Retrieve a Protocol or AbstractMethod so Pycharm and co can highlight/catch these errors ahead of time.
> Further Update YouRM to return an Iterable of Predictions

- dspy/retrieve/chromadb_rm.py
The previous PR #400 opened by @animtel set `chromadb.utils.embedding_functions.DefaultEmbeddingFunction` as the default query embedding function. This calls `ONNXMiniLM_L6_V2` , which uses `all-MiniLM-L6-v2` as the base embedding model.
This introduced unintended behavior where queries could be embedded using a different model than documents unless the embedding function was explicitly provided. If a model other than `all-MiniLM-L6-v2` embeds queries, and the embedding function is not specified, the query and document embeddings will use different models. While this may be desired in some cases, this should not be the default behavior.
This PR changes the default query embedding method to use the collection's embedding function, accessed via the class. Users can still provide a custom …
> Refactor ChromadbRM to use collection's default embedding function

- docs/language_models_client.md
- dsp/modules/__init__.py
- dsp/modules/databricks.py
- dspy/__init__.py
- dspy/retrieve/databricks_rm.py
integrated Databricks connectors for configuring LMs and RM in DSPy.
LMs - adapted from OpenAI Client SDK in [Databricks Model Serving endpoints](https://docs.databricks.com/en/machine-learning/model-serving/score-model-serving-endpoints.html#language-OpenAI%C2%A0client)
Supports chat, completions, and embeddings model formats.
RM - adapted from [querying Databricks Vector Search Endpoint](https://docs.databricks.com/en/generative-ai/create-query-vector-search.html#create-a-vector-search-index)
> added Databricks integrations for DSPy LMs/RM configurations

- dspy/teleprompt/bootstrap.py
In line 151 of `BootstrapFewShot` we currently check examples with:
`success = (self.metric is None) or self.metric(example, prediction, trace)`
If success == True, we then wrap the predictor, inputs, and outputs in an Example object and append it to `name2traces`.
This works great if you have a boolean metric, but maybe we want to extend this with a `metric_threshold` argument for float or int metric return types.
- `metric_threshold` is added as default `None`
Then line 151 is replaced with:
```
if self.metric:
metric_val = self.metric(example, prediction, trace)
if self.metric_threshold:
success = metric_val > self.metric_threshold
else:
success = metric_val
else:
success = True
```
We can now retain the float metrics like LLM rating metrics or what have you, but also add a little more …
> Add `metric_threshold` argument to BootstrapFewShot

- dspy/datasets/dataloader.py
```
from dspy.datasets import DataLoader
dl = DataLoader()
json_dataset = dl.from_json("/home/path-to/sample_responses.json", fields=["question", "answer", "context"])
```
> feature: add dl.from_json to support native json dataset formats

- dsp/utils/settings.py
- dspy/backends/lm/base.py
- dspy/backends/lm/litellm.py
I took a look into how we can integrate global joblib Memory caching into the `BaseLM` class.
It takes a little bit of misdirection, but the below `BaseLM` class will provide for global caching for all sub-classes that implement `BaseLM`.
```python
_cache_memory = Memory(cachedir, verbose=0)
class BaseLM(BaseModel, ABC):
def __init__(self, *args, **kwargs):
super().__init__(*args, **kwargs)
self._cached = _cache_memory.cache(self._call)
def __call__(self, prompt: str, **kwargs) -> list[str]:
"""Generates `n` predictions for the signature output."""
return self._cached(prompt, **kwargs)
@abstractmethod
def _call(
self,
prompt: str,
**kwargs,
) -> list[str]:
"""Generates `n` predictions for the signature output."""
...
@abstractmethod
def count_tokens(self, prompt: str) -> int:
"""Counts …
```
> feat: Exploring global caching for LM calls

- docs/guides/language_models.ipynb
Update the notebook. The Colab button is being redirected to signatures.ipynb (on Colab) instead of language_models.ipynb.
> Update language_models.ipynb Colab link

- dsp/modules/azure_openai.py
- dsp/modules/lm.py
BootstrapFewShot failing due to lm.copy for AzureOpenAI, likely due to positional argument issue from recent changes.
- Issue: https://github.com/stanfordnlp/dspy/issues/521
- code: 98304a2eb9d1dddaaa846e30258cd5d8fc6b5d8d
- model azure openai
- during `BootstrapFewShot` run, code errored out due to missing arguments, `api_version`
```
>[dspy/dsp/modules/lm.py](https://file+.vscode-resource.vscode-cdn.net/Users/insop/Projects/Github/NLP/dspy/dsp/modules/lm.py)(106)copy()
102         model = kwargs.pop('model')
105
--> 106         return self.__class__(model, **kwargs)
```
AzureOpenAI expects positional arguments, so it is failing. I am putting my change for review if that will impact other models.
```
class AzureOpenAI(LM):
...
def __init__(
self,
api_base: str,
api_version: str,
model: …
```
> BootstrapFewShot failing due to lm.copy for AzureOpenAI, #521

- dspy/backends/template.py
- dspy/primitives/__init__.py
- dspy/primitives/template.py
- tests/primitives/test_template.py
The original implementation of `TemplateBackend` relied upon the `signature_to_template` function. This would take in a `dspy.Signature` and return a `dsp.Template`. However, we would pass `dspy.Example` into the `dsp.Template` and the extract function would return `dsp.Example` a different type. Leaving us with two different types of `Example` within a single prediction. To combat this, a new `Template` primitive was introduced into `dspy` to mirror and replace the original `dsp.Template`.
I do not expect this current PR to achieve feature parity with the original class, but initial tests have been introduced to mock and mirror the current prompt structure used in `dsp`.
Let me know what you think @CyrusOfEden, the last piece I believe to start using the `TemplateBackend` is to fully …
> Introduce dspy.Template

- dspy/teleprompt/__init__.py
- tests/teleprompt/test_ensemble.py
Adds ensemble to the teleprompt imports. Solves #533
> bug(dspy): Move ensemble import to teleprompt

- dspy/teleprompt/signature_opt.py
#482 introduced _print_signature() for verbose mode in signature optimizer.
```python    
def _print_signature(self, predictor):
if self.verbose:
if (hasattr(predictor, 'extended_signature')):
signature = predictor.extended_signature
else:
signature = predictor.extended_signature1
print(f"i: {signature.instructions}")
print(f"p: {list(signature.fields().values())[-1].json_schema_extra['prefix']}")
print()
```
fields() is a property method in SignatureMeta class. 
```python
@property
def fields(cls):
return {**cls.input_fields, **cls.output_fields}`
```
"fields" method is being used incorrectly in _print_signature()
The current _print_signature() implementation is raising 'TypeError: 'dict' object is not callable' when trying to use signature optimizer as per the tutorial provided in …
> fix: printing signature fields in verbose mode for signature_opt

- docs/api/retrieval_model_clients/ChromadbRM.md
- docs/docs/deep-dive/retrieval_models_clients/ChromadbRM.mdx
> fix: import of ChromaRM

- docs/docs/quick-start/minimal-example.mdx
The new docs are awesome, and this is a 1 line change that I propose to improve `minimal-example`
> docs(dspy): add toy invocation of model to minimal-example

- dsp/modules/azure_openai.py
This commit is to remove unused kwargs that we include in the requests sent through `AzureOpenAI` class.
This seems to fix this issue: https://github.com/stanfordnlp/dspy/issues/543
> Remove unused kwargs passed to requests sent through `AzureOpenAI`

- dspy/teleprompt/random_search.py
*Change:*
- add `metric_threshold` parameter to `BootstrapFewShotWithRandomSearch` with default being `None`
*Reason:*
- when using a custom metric that are not 0 or 1, we need `metric_threshold` in `BootstrapFewShot`; however, when using `BootstrapFewShotWithRandomSearch` we don't have `metric_threshold` that can be passed to  `BootstrapFewShot`
@okhat
> Adding metric_threshold to BootstrapFewShotWithRandomSearch

- dspy/evaluate/evaluate.py
Addresses https://github.com/stanfordnlp/dspy/issues/477
> Fix return_all_scores in evaluate

- dspy/retrieve/chromadb_rm.py
The recent PR #449 opened by @smwitkowski  refactored ChromadbRM constructor to use collection default embedding function with the syntax "self._chromadb_collection.embedding_function". But ChromaDB collection object has no such attribute and raises attribute error if no embedding function is passed to the constructor. 
This PR modifies the constructor to use Chromadb collection's protected attribute "self._chromadb_collection._embedding_function" and the module now works as expected.
I could be wrong in my assumptions as I am relatively new to dspy and am open to possible better resolution.
> fix: default collection embedding function attribute in ChromadbRM constructor

- docs/api/retrieval_model_clients/Neo4jRM.md
- dspy/retrieve/neo4j_rm.py
Neo4j has a vector index that can be used for vector retrieval in RAG in other applications. It can be expanded with retrieval query, so that it can traverse through the graph after the initial vector search if needed.
> Add support for neo4j vector index

- docs/api/retrieval_model_clients/ChromadbRM.md
- dspy/retrieve/chromadb_rm.py
Returning metadata along long_text for ChromaDB.
Fixes #364 for ChromaDB
> feature(dspy): return metadata along long_text for ChromaDB retrieval

- dspy/evaluate/evaluate.py
As mentioned in https://github.com/stanfordnlp/dspy/pull/561#issuecomment-1994541167, older Pandas such as 1.5.3 (the default version on Colab) doesn't have `DataFrame.map` yet
> fix(dspy): use DataFrame.applymap in older pandas

- dspy/teleprompt/bootstrap.py
- dspy/teleprompt/copro_optimizer.py
- dspy/teleprompt/ensemble.py
- dspy/teleprompt/finetune.py
- dspy/teleprompt/knn_fewshot.py
- dspy/teleprompt/mipro_optimizer.py
- dspy/teleprompt/random_search.py
- dspy/teleprompt/signature_opt.py
- dspy/teleprompt/signature_opt_bayesian.py
- dspy/teleprompt/teleprompt.py
- dspy/teleprompt/teleprompt_optuna.py
- dspy/teleprompt/vanilla.py
I don't know why this didn't happen automatically
> Formatting for new optimizers

- .pre-commit-config.yaml
What is the change?
- ruff came back to the repo pre-commit
Why the change is important?
- it will bring lots of merge conflicts later on if the IDE doesn't have the same config.
How to test?
- test it with your IDE
Note:
This has been removed accidentally in https://github.com/stanfordnlp/dspy/pull/611 which I just reverted the file.
> fix(ruff) | Ruff accidentally has been deleted from pre-commit

- dsp/utils/settings.py
updated trace to now be configured as `[]` instead of `None` to avoid manual setting to enable assertions. 
Patch per comments from #434 #467. 
@okhat - feel free to confirm this does not break any existing caches/behavior (@Shangyint and I have checked to ensure this already!)
> trace patch

- dsp/primitives/predict.py
The google LM module has "max_output_tokens" in its kwargs dict, rather than "max_tokens". This causes `do_generate` to sometimes fail when trying to adjust the max tokens in the retry logic.
I considered updating the Google kwargs dict to also contain "max_tokens", but then the generation config object complains about extra keys, so it gets kind of annoying to keep track of as you switch back and forth.
It probably won't matter soon anyway, since I think the plan is to migrate to LiteLLM.
> Fix do_generate looking for max_tokens when using Google LM

- dspy/retrieve/pgvector_rm.py
* What is this PR for?
* This PR resolves #613, adding an option to choose whether use openai to get embeddings, or other embedding models like cloud embedding services(google, cohere, nomic, ...) or on-premise embedding models(huggingface).
Features:
* Now installing `openai` is not required. Move it into optional import.
* Now either `openai_client` or `embedding_func` should be specified, otherwise raises AssertionError.
This PR will not change the current behavior as it still accepts `openai_client` for openai embeddings.
> Add an option to choose embedding model in pgvector

- dsp/modules/hf_client.py
This PR adds support for multiple API endpoints being passed to `HFClientVLLM` via the `url` argument, in a backwards-compatible manner, as discussed in [this](https://github.com/stanfordnlp/dspy/issues/554) issue.
> Added support for multiple API endpoints to `HFClientVLLM`

- CONTRIBUTING.md
Signed-off-by: hsm207 <hsm207@users.noreply.github.com>
Fix typo to run tests.
This:
```bash
poetry install --with test
```
gives the following error:
```
Group(s) not found: test (via --with)
```
No
> docs(dspy): fix typo to run tests

- dspy/predict/predict.py
- tests/predict/test_predict.py
This simple PR aims to fix the `Pydantic model is not JSON serializable` error when saving the state of a compiled program that uses `TypedPredictors`.
However, this fix assumes that the demos of the predictors don't need to keep the same types after saving and loading their states. In older versions of DSPy the type was preserved, but after this commit it changed: https://github.com/stanfordnlp/dspy/commit/b9516c45dbcdedbed6b71dab7cd4a6c1024e0dcf
If that is not expected... then I don't how we would load the state to the pipeline. The JSON cannot know about the Pydantic models. A solution would be to pickle everything. Unfortunately I wasn't able to pickle the pipeline either, because it crashes on the dynamically created Pydantic models of the augmented TypedCoTs signatures.
> Fix save and load state of program with typed predictors

- docs/api/retrieval_model_clients/ChromadbRM.md
fixing a minor typo by replacing chroma_rm with chromadb_rm in demo import statement
> docs(api/retrieval_model_clients/ChromadbRM): fix typo in import statement

- dspy/predict/program_of_thought.py
While, the PythonInterpreter and CodePrompt modules allowed for importing a white_list, this functionality hadn't been made available directly inside ProgramofThought. This was causing repeated hinderance when language models would try to use any math packages that were not allowed like sympy etc, which makes for a bad dev UX.
This also updates the ProgramOfThought class to support dynamic input and output field names, improving user experience and flexibility. The changes include:
Modifying the __init__ method to store input and output fields from the provided signature
Updating the generation of input and output field names in the instruction strings
Refactoring the _generate_signature and _generate_instruction methods to handle dynamic field names
Modifying the forward method to use …
> feat(ProgramofThought): added support for custom whitelists and dynamic input and output field naming (continuation of #665)

- dspy/datasets/dataloader.py
A parquet file loader would be a convenient addition to the dataloader class. I particularly like that parquet files preserve types better than a csv file.
Here's the change:
```python
def from_parquet(self, file_path: str, fields: list[str] = None, input_keys: tuple[str] = ()) -> list[dspy.Example]:
dataset = load_dataset("parquet", data_files=file_path)["train"]
if not fields:
fields = list(dataset.features)
return [dspy.Example({field: row[field] for field in fields}).with_inputs(input_keys) for row in dataset]
```
Note, this PR was originally made in #483, but something with git hooks prevented test from being able to run.
> [feat] add from_parquet to dataloader

- dsp/modules/anthropic.py
This commit updates the `Claude` class to support additional models provided by the Anthropic API:
- claude-2.0
- claude-2.1
- claude-3-opus-20240229
- claude-3-haiku-20240307
- claude-3-sonnet-20240229
The `__init__` method of the `Claude` class has been modified to include a list of supported models. When creating an instance of the `Claude` class, the `model` parameter can be set to any of the supported model names. If an unsupported model is provided, a `ValueError` is raised with a message indicating the supported models.
This change allows users to utilize the newly added models for generating completions using the Anthropic API.
> feat: Add support for additional Anthropic models

- dspy/predict/retry.py
- tests/predict/test_retry.py
This simple PR aims to fix the errors and signature inconsistencies when using Assertions and Suggestions with modules with TypedPredictors.
> Fix Retry for TypedPredictors

- dsp/modules/hf_client.py
in `dsp.modules.HFClientVLLM` class the `kwargs` are supposed to be passed to the vllm openai endpoint (cf. the docs) but are discarded instead. This is related to the issue here : https://github.com/stanfordnlp/dspy/issues/718
In this PR, there are some modifications to the `dsp.modules.HFClientVLLM` class:
1.  In the `__init__` the `kwargs` were actually unused. In this PR those are attached to `self.` instead of being discarded.
2. The model of the payload was provided by the `kwargs` of `_generate` method, disregarding the value initialized in the `__init__`. This is fixed in this PR.
3. Two optional parameters were made mandatory (`temperature` and `max_tokens`) in the `_generate` method. Those were made mandatory because it was a direct `kwargs["<parameter>"]`, which would raise …
> fix(dsp): in `HFClientVLLM`, actually use `kwargs` in the payload instead of discarding them

- .devcontainer/devcontainer.json
- .devcontainer/interpreter_warning.py
- .devcontainer/post_create.sh
- CONTRIBUTING.md
* Builds the dev container Poetry venv within the workspace
* Includes VSCode setting to choose the poetry Python interpreter by default
* Includes additional warning about interpreter at the end of the dev container build to provide instructions on how to choose the correct interpreter if it's not already selected
* Updates contributing markdown file with these additional instructions
We got reports that people were not able to run the unit tests after building the dev container. After further investigation, I found that this is not due to the dev container itself but instead in the Python interpreter selected by the user. If the user has the OS default Python interpreter selected, that interpreter will not have access to the packages installed …
> Increase chances that VSCode dev container will use Poetry venv

- dsp/modules/azure_openai.py
Fixes issue #591 without re-creating issue #543
The problem was that `AzureOpenAI.copy` used `LM.copy`, but because `api_key` etc. aren't in the `AzureOpenAI.kwargs`, and `LM.copy` per default only propagates `self.__class__.kwargs`.
I now gave `AzureOpenAI` its own `copy`-method. This isn't really beautiful, but it seems to work pretty well.
> fix(dspy): add `copy` to AzureOpenAI to propagate `api_(key|version|...)`

- dsp/modules/hf_client.py
In HFClientVLLM attach the model string directly to instance
Fixes an error in https://github.com/stanfordnlp/dspy/pull/719
Closes #764
> hotfix(dsp): In HFClientVLLM get the model from the kwargs attached by the parent class

- dspy/primitives/example.py
- tests/primitives/test_example.py
This simple condition should fix #568  and #557 and prevents further class mismatch assuming only Example object will be compared to each other.
> add condition to prevent comparing Example with non-Example object

- dsp/modules/azure_openai.py
- dsp/modules/gpt3.py
I noticed that the docstring for `OpenAI` says that the default model value is davinci. However, the default value of the parameter in code is GT3 turbo instruct, which looks more reasonable.
I suspect the default changed a while ago and someone forgot to change the docstring.
* New docstring value for the model property of `OpenAI` and `AzureOpenAI` classes
Exactly because of these things (changing the parameter default value and forgetting to update the docs), I would consider not writing the default value in the docs at all. The IDE (I checked VS Code) anyway shows the available parameters and their default values, in addition to the docstring. So best case - it's written twice. Worst case - it's written twice AND one is incorrect.
> docs(dspy): Fixed docstring for OpenAI having wrong default model

- dspy/functional/functional.py
This change allows you to pass key word arguments such as the max_retries argument to the typed predictors while using the decorator method to construct them. Example:
```py
class MyModule(dspy.Module):
@dspy.cot(max_retries=5, explain_errors=True)
def my_cool_function(self, input: Input) -> Output:
"""Does some incredibly cool stuff up to five times with an explanation for errors"""
pass
... rest of module implementation
```
The arguments are optional, so `@dspy.cot` and `@dspy.cot(max_retries=1)` will both work under this patch.
> allow passing of kwargs to typed predictor decorators

- pyproject.toml
building from a non-poetry environment results in a build error with importing `structlog`. Added to `pyproject.toml` dependencies
> fix structlog dependency when building from source

- dspy/retrieve/qdrant_rm.py
A bug in QdrantRM.forward signature implementation prevents it to be called without providing the argument `k`.
This was observed while using the `dspy.ReAct` module:
```
(dspy/predict/react.py:95), in ReAct.act(self, output, hop)
[92](dspy/predict/react.py:92)     return action_val
[94](dspy/predict/react.py:94) try:
---> [95](dspy/predict/react.py:95)     output[f"Observation_{hop+1}"] = self.tools[action_name](action_val).passages
[96](dspy/predict/react.py:96) except AttributeError:
[97](dspy/predict/react.py:97)     # Handle the case where 'passages' attribute is missing
[98](dspy/predict/react.py:98)     # TODO: This is a hacky way to handle this. Need to fix this.
[99](dspy/predict/react.py:99)     output[f"Observation_{hop+1}"] = self.tools[action_name](action_val) …
```
> fix(qdrant_rm): forward can be called without specifying k

- dspy/evaluate/evaluate.py
This PR fixes the evaluation return results feature for multithreaded evaluation. previously it returned an unsorted results array and now it returns the desired ordered results
> Fix evaluation multithreaded results

- dsp/modules/hf_client.py
Previously, using `HFClientTGI` with `BootstrapFewShot` didn't work for `max_rounds` > 1. The culprit was:
```
File "<snip>/lib/python3.10/site-packages/dsp/modules/lm.py", line 84, in copy
model = kwargs.pop('model')
KeyError: 'model'
```
This PR makes sure the relevant kwargs are saved (all are necessary)
Thanks!
> Save kwargs for huggingface TGI model

- dspy/functional/functional.py
- tests/functional/test_functional.py
Add an argument for custom rationale type like:
```python
rationale_type = dsp.Type(
prefix="Take a deep breath and let's think step by step in order...",
desc="Based on the context...",
)
self.task = dspy.TypedChainOfThought(SomeTask, rationale_type=rationale_type)
```
> Add Custom Rationale Type option in TypedChainOfThought Module

- dsp/modules/__init__.py
- dsp/modules/dummy_lm.py
This fixes a bug with Phoenix instrumentation. Phoenix is currently wrapping calls to every LM in `LM.__subclasses__()`, and we have a DummyLM in dspy/utils/ that makes the team for this wrapper,
From https://github.com/Arize-ai/openinference/blob/main/python/instrumentation/openinference-instrumentation-dspy/src/openinference/instrumentation/dspy/__init__.py
Line 68
```
language_model_classes = LM.__subclasses__()
for lm in language_model_classes:
wrap_object(
module=_DSP_MODULE,
name=lm.__name__ + ".basic_request",
factory=CopyableFunctionWrapper,
args=(_LMBasicRequestWrapper(tracer),),
)
```
This PR moves the DummyLM to dsp/modules to work around this.
@mikeldking @axiomofjoy @isaacbmiller @thomasahle
> [Phoenix Patch] Move DummyLM to dsp/modules

- intro.ipynb
I get an error when trying to run this intro notebook. Removing the keyword argument makes the error go away.
Also, when running the setup / install, I get a note that `structlog` is missing. (I'm running this locally in a fresh Python 3.11.8 environment).
> Remove missing keyword argument

- docs/docs/faqs.md
Documents the latest way to address these two issues: 
- https://github.com/stanfordnlp/dspy/issues/213
- https://github.com/stanfordnlp/dspy/issues/578
Please also note that the disable cache feature is not available on the latest version of the dspy package available on [pypi](https://pypi.org/project/dspy-ai/2.4.5/#history). **See**: https://github.com/stanfordnlp/dspy/issues/805
> docs(faqs): update documentation for disabling the cache

- dspy/retrieve/databricks_rm.py
- There were two missing code lines that prevented the "text" column from being returned when the "froward" method was executed
> fixing issue in DatabricksRM preventing indexed text from being returned

- dspy/retrieve/databricks_rm.py
Setting the default value of the DatabricksRM.forward  "query_type" param to "text"
It is recommended to use the fully managed approach for Vector Search which covers getting the embeddings from the of the indexed column during the ingestion and the embeddings of the text query during inference
> Setting the default value of the DatabricksRM.forward  "query_type" 

- docs/docs/tutorials/simplified-baleen.md
The function gold_passages_retrieved is currently missing, without it the tutorial doesn't work. 
I copied the function from https://github.com/stanfordnlp/dspy/blob/eab1324d45aa1a723e187b2523e4d20bfc75356d/tests/examples/test_baleen.py#L98
I tested the code with this new function and I get similar numbers as in the tutorial
> Add missing gold_passages_retrieved function

- dspy/predict/predict.py
PR linked to issue described here:
https://github.com/stanfordnlp/dspy/pull/795#issuecomment-2057280084
Using Bedrock and claude3-haiku
```
bedrock = dspy.Bedrock(...)
haiku = dspy.AWSAnthropic(
aws_provider=bedrock,
model="anthropic.claude-3-haiku-20240307-v1:0",
)
class BasicQA(dspy.Signature):
"""Answer questions with short factoid answers."""
question = dspy.InputField()
answer = dspy.OutputField(desc="often between 1 and 5 words")
generate_answer_with_chain_of_thought = dspy.ChainOfThought(BasicQA)
pred = generate_answer_with_chain_of_thought(question=dev_example.question)
```
Error: TypeError: '>' not supported between instances of 'NoneType' and 'int'
The error is fixed when the change in the PR is introduced
> (dspy/predict): corrected temperature check for bedrock claude models

- docs/docs/deep-dive/retrieval_models_clients/Azure.mdx
- dspy/retrieve/azureaisearch_rm.py
- pyproject.toml
Feature Addition: Updating AzureAISearchRM Class
This pull request aims to enhance the functionality of the `AzureAISearchRM` class by introducing support for additional search capabilities. Specifically, the class is updated to enable `Vector Search`, `Hybrid Search`, and `Full Text Search` with `Semantic ReRanker`, providing users with more versatile and powerful search options.
Changes Included:
- Integration of `Vector Search`, `Hybrid Search`, and `Full Text Search` functionalities.
- Implementation of `Semantic ReRanker` to enhance search results with semantic understanding.
- Addition of necessary methods and attributes to support the new features.
- Updates to the documentation to reflect the expanded capabilities of the class.
Checks:
Pre-Commit checks are passing (locally and …
> feat(dspy): add vector, hybrid and fulltext search support in azure ai search module

- dsp/modules/hf_client.py
- dsp/modules/lm.py
Related to issue #778 #784 
- added vllm chat completion endpoints (support system_prompt)
- fixed an issue with .copy() with vllm client module. (need to include model, url, port into kwargs)
- fix inspect_histrory not respecting n/skip as mentioned in #784
> Add vllm chat completion endpoints and fix inspect_history

- dspy/__init__.py
- dspy/utils/logging.py
The `set_log_level` function has inconsistent outcomes, as such it was removed in favor of directly manipulating the log level:
````
dspy.logger.setLevel(logging.DEBUG)
````
> Small Fixes for Logging

- dsp/modules/anthropic.py
- dsp/modules/azure_openai.py
- dsp/modules/gpt3.py
- dsp/modules/groq_client.py
- dsp/utils/settings.py
- dspy/utils/logging.py
Deprecate the 'log_openai_usage' configuration option.
As we are now moving to proper logging, we now log all usage by default, and allow the user to specify how they want to handle the logs themselves.
This removes the setting, and all mentions of this settings across gpt3/anthropic/azure_openai/groq.
> Deprecate old logging

- dsp/modules/hf_client.py
Previously, the VLLM HFClient used different URLs for different requests, messing up the cache.  This PR copies the way that the HG TGI Client handles multiple URLs and ports, which is a wrapper call function that overrides the URL and port in kwargs to be the same for all calls to the LM from the instantiated class.  Since the specific URL/port for the request is now ignored (as the cache ignores the arg parameter), the cache will store the results of the call regardless of the specific URL it was routed to. This leads to significantly better performance with multi-host VLLM models!
> Fixed VLLM Cache

- dsp/modules/groq_client.py
This pull request addresses critical issues in the `groq_client` module that previously rendered the package non-functional. Specifically, it resolves an AttributeError that was blocking all operations within the module.
- Corrected attribute access within the `log_usage` function to use dot notation instead of attempting dictionary access on a Pydantic model object.
- Ensured proper error handling in scenarios where expected attributes are missing in the response object.
Prior to these changes, attempting any operation involving `groq_client` would lead to an immediate failure, thus preventing any functionality tests or further integration tests from being conducted. These changes restore basic operational capabilities to the `groq_client`.
- While full integration testing was not …
> fix(groq_client): corrected attribute access in log_usage

- dsp/modules/cohere.py
Adds another except statement to ensure that cohere can be imported correctly, regardless of version.
Missing:
Tests
Link to collab with repro/fix:
[Collab notebook](https://colab.research.google.com/drive/1yK0X0TEp_J2m9khQxbi8Ueh6nxfpSePo?usp=sharing)
Fixes: #893
> fix(cohere): Catch attribute error

- docs/api/modules/ChainOfThought.md
- docs/api/modules/ChainOfThoughtWithHint.md
This PR addresses issue #841.
- Modify API documentation for class ChainOfThought to reflect the correct rationale_type according to the up-to-date source.
- Provide a simple example to show how to specify a custom rationale
- Modify API documentation for class ChainOfThoughtWithHint to reflect correct rationale_type according to the up-to-date source.
Also please note that `git subtree pull` command provided in `docs/README.md` does NOT work, raising `fatal: refusing to merge unrelated histories`.
> fix #841, the issue with the api documentation.

- dspy/retrieve/chromadb_rm.py
Provide an optional chromadb client for ChromadbRM. I don't see a good way to override default options when use chromadb without default config.
Similar to weaviate_rm
> feat: Provide optional client for ChromadbRM

- docs/docs/building-blocks/1-language_models.md
- docs/docs/building-blocks/3-modules.md
- docs/docs/building-blocks/7-assertions.md
Minor edits based on typos found while going through the documentation :)
> 📝 Fix typos and missing hyperlinks in "Building Block" Docs

- dspy/functional/functional.py
`bool` was elevated into the top condition [here](https://github.com/stanfordnlp/dspy/commit/982db444322cbf6a545a2504ce162b15dafee975), so it can't be reached in the elif.
> fix(dspy): remove unreachable type condition in TypedPredictor

- dspy/__init__.py
dspy.Claude was a missing alias.  I checked through the others for consistency and this appears to be the only one left out.
Import move was a ruff fix.
> feat(dspy): add dspy.Claude helper

- dsp/modules/ollama.py
This problem is very similar to #769. `OllamaLocal.copy` uses `LM.copy`. However, `OllamaLocal`'s `kwargs` dict doesn't have `model` key, which means `model = kwargs.pop("model")` will create a `KeyError`. This fix added a `copy` method to `OllamaLocal` class so that it's own attributes like `model`, `model_type`, `base_url` and `timeout_s` can be copied.
> fix(dspy): added `copy` to `OllamaLocal` to propagate `model`, `model_type`, `base_url` and `timeout_s`.

- poetry.lock
- pyproject.toml
Right now, the requirement on the `datasets` package is `"datasets~=2.14.6,<3.0.0"`. Based on [Poetry's specifications for tilde requirements](https://python-poetry.org/docs/dependency-specification/#tilde-requirements), this means that only 2.14 patch releases can be used for the datasets package (and the `<3.0.0` part of the requirement isn't doing anything).
But this is needlessly restrictive, as the datasets package is now up to version [2.19.0](https://github.com/huggingface/datasets/tags). Additionally, restricting datasets to such a low version causes issues with resolution alongside other packages that require `datasets` as well.
The primary usage of datasets is to call `load_dataset`, which shouldn't be affected by this version constraint.
**Solution**: Change the `~=2.14.6` to …
> Loosen requirement on `datasets` package

- dsp/primitives/search.py
When invoking `retrieveRerankEnsemble` in  https://github.com/stanfordnlp/dspy/blob/d7dace6b51e1c0899fd798c575262310939f6deb/dsp/primitives/search.py#L52, it's missing `kwargs`
> add missing kwargs when invoking retrieveRerankEnsemble

- docs/api/retrieval_model_clients/FaissRM.md
- dsp/modules/aws_providers.py
Bedrock LM produces extraneous key error in unclear circumstances #365
> FIX Bedrock LM produces extraneous key error in unclear circumstances

- dspy/signatures/signature.py
- tests/signatures/test_signature.py
* Remove common indentations like it is done in docstring tools
* Fixes https://github.com/stanfordnlp/dspy/issues/986
> Remove common indentations in signature according to Python Docstring convention

- dspy/evaluate/evaluate.py
- tests/evaluate/test_evaluate.py
Obtained an error when `display_table=True` is provided for `Evaluate`. 
See simple reproducible example below:
```py
from dspy.evaluate.evaluate import Evaluate
from dspy.evaluate.metrics import answer_exact_match
from dspy.predict import Predict
def new_example(question, answer):
"""Helper function to create a new example."""
return dspy.Example(
question=question,
answer=answer,
).with_inputs("question")
devset = [new_example("What is 1+1?", "2")]
program = Predict("question -> answer")
ev = Evaluate(
devset=devset,
metric=answer_exact_match,
display_table=True,
)
ev(program)  # TypeError: cannot do positional indexing on RangeIndex with these indexers [True] of type bool
```
This stems from `isinstance(True, int) == True`. 
This PR contains a proposed fix with updated unit tests. Feel …
> fix(evaluate): `Evaluate` should not error when `display_table=True`

- dspy/predict/react.py
- tests/predict/test_react.py
When I use `ReAct` with `Signature`, I find that the `instructions` field in the given signature is ignored by the `ReAct` class, this behavior is not consistent with `Predict`. This fix provides a workaround for the issue.
> fix(react): `ReAct` doesn't use `instructions` from the given `Signature`

- dspy/predict/langchain.py
When running the [example](https://github.com/stanfordnlp/dspy/blob/main/examples/tweets/compiling_langchain.ipynb) I face this error:
```
{
"name": "AttributeError",
"message": "'FieldInfo' object has no attribute 'finalize'",
"stack": "---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[5], line 6
2 from dspy.predict.langchain import LangChainPredict, LangChainModule
4 # This is how to wrap it so it behaves like a DSPy program.
5 # Just Replace every pattern like `prompt | llm` with `LangChainPredict(prompt, llm)`.
----> 6 zeroshot_chain = RunnablePassthrough.assign(context=retrieve) | LangChainPredict(prompt, llm) | StrOutputParser()
7 zeroshot_chain = …
```
> Langchain integration bug fixed

- dspy/retrieve/vectara_rm.py
Minor update to support multiple Vectara corpora with the retriever.
> support multiple corpora in vectara retriever

- dsp/modules/hf_client.py
Can you just checkout and suggest any changes?
> bug(dspy): removed extra params from kwargs sent to vllm pydantic model

- dsp/modules/hf_client.py
This PR includes the proposed changes by @wolfsauge in https://github.com/stanfordnlp/dspy/issues/1025.
This makes https://github.com/stanfordnlp/dspy/pull/1029 unnecessary and reverses the changes from https://github.com/stanfordnlp/dspy/pull/1012.
Closes https://github.com/stanfordnlp/dspy/issues/974
> Filter vllm keywords

- docs/docs/cheatsheet.md
Does it make sense to remove the `dspy.` if a class is not actually accessible over it? In case that's wanted it might make sense to actually allow access with `dspy.`
> Update cheatsheet references

- dspy/retrieve/pinecone_rm.py
- examples/integrations/pinecone/pinecone_wikipedia_example.ipynb
source is from https://github.com/stanfordnlp/dspy/pull/342/files
- update had gotten stale. updates written by @DanielUH2019
> fix(pinecone_rm): refactored to use cloud_embed and fix pinecone init

- dsp/modules/hf_client.py
This simple PR just allows to configure Anyscale API in it's constructor, following the pattern on the others LMs.
> Allow to configure Anyscale API in constructor

- dspy/retrieve/pgvector_rm.py
When working with the [Tutorial](https://dspy-docs.vercel.app/docs/tutorials/simplified-baleen), using OllamaLocal and PgVectorRM, I found some mismatch below and fixed it.
- Fix `long_text` KeyError by added `content_filed` attr
- Fix `psycopg2.errors.UndefinedFunction: operator does not exist: vector <=> numeric[]` when `include_similarity=True`
- Fix `TypeError: PgVectorRM.forward() got an unexpected keyword argument 'k'` in the forward method
- Code reformat with Ruff
> Fix pgvector work with the tutorial

- dspy/functional/functional.py
- tests/functional/test_functional.py
Adds an attempt to use the function supplied to `from_json` before running string parsing. This allows users to modify the pydantic's `model_validate_json` to customise the deserialization of the generation.
Other changes were to satisfy ruff.
This PR gives users a route to inject code which can solve issues like https://github.com/stanfordnlp/dspy/issues/1024 and https://github.com/stanfordnlp/dspy/issues/1001
After this PR, the user could implement something like the following:
```python
class TaxField(BaseModel):
key: str = Field()
value: str = Field()
truthful: bool = Field(
description="is a tuple contains the extracted value and a boolean indicating if the inFieldsation is truthful and correct."
)
confidence: float = Field(ge=0, le=1, description="The confidence score for the …
```
> feat(dspy): try from json before applying formatting logic in typed predictor

- dspy/datasets/hotpotqa.py
Add context to details to make it easier to run evaluations.
We want want to make it easier to retrieve context outside of dspy retriever
> feature(dsp) Add context to details

- dspy/teleprompt/bootstrap.py
Sharing a quick patch for #1091 
Error seen while running https://github.com/stanfordnlp/dspy/blob/main/examples/tweets/compiling_langchain.ipynb
```
File ~/dspy/teleprompt/bootstrap.py:115, in BootstrapFewShot._prepare_predictor_mappings(self)
113 for (name1, predictor1), (name2, predictor2) in zip(student.named_predictors(), teacher.named_predictors()):
114     assert name1 == name2, "Student and teacher must have the same program structure."
--> 115     assert predictor1.signature.equals(
116         predictor2.signature,
117     ), (f"Student and teacher must have the same signatures. "
118         f"{type(predictor1.signature)} != {type(predictor2.signature)}"
119         )
120     assert id(predictor1) != id(predictor2), "Student and teacher must be different objects."
122 …
```
> fix(dspy): fix langchain predict (#1091)

- README.md
- setup.py
update setup.py and docs so it's clear how to include groq dependency
resolves https://github.com/stanfordnlp/dspy/issues/1022 and https://github.com/stanfordnlp/dspy/issues/955 (which are the same)
> fix: missing groq extra install option

- dsp/modules/lm.py
A small PR to refactor redundant logic within the `dspy.LM.inspect_history` method. 
I came across this when trying to integrate a custom LLM — `inspect_history` expects a particular schema from `self.history[i]['requests']` that isn't documented in the [docs](https://dspy-docs.vercel.app/docs/deep-dive/language_model_clients/custom-lm-client). These if/else statements indicate a deficiency of the existing interface. 
I'm happy to extend in the interface across all `LM` subclasses, cleaning up the if/else statement here and update the docs. However, I would first like to understand what is the concept of "choices" in `printed.append("<prompt>", "<choices>")`, and possibly some guidance on the proper interface if you have any. 
Thanks!
> refactor(inspect-history): Refactor providers

- dsp/modules/cohere.py
Increase from 150 to 2000. 
I think most people are using Command R / R+ for RAG tasks where 150 tokens are typically not enough. Very minor change to improve the UX a tiny amount.
> Very minor change - increase default on Cohere LLM module.

- docs/api/local_language_model_clients/vLLM.md
The markdown lines change toward the issue: https://github.com/stanfordnlp/dspy/issues/1136
> updated vLLM local client usage in docs markdown

- docs/docs/quick-start/minimal-example.mdx
Some small fixes, if you want them :)
- Made comments more consistent (full sentences).
- Typo: 'It simple'.
- Typo: 'the chain-of-thought reasoning'.
- Missing backticks from object name.
Thank you for this library!
> Fix small typos in minimal-example.mdx

- dspy/retrieve/deeplake_rm.py
This commit fixes a bug in the DeeplakeRM class, which is a retriever model that uses Deep Lake to return the top context for a given query. The following changes have been made:
- Updated the import of OpenAI errors.
- Updated the embedding function.
- Modified the vector store instance initialization: it was instantiated every time the user made a request, now it is instantiated only at the beginning.
> fix(dspy): fixed bug in deeplake_rm retriever part

- dsp/modules/premai.py
Due to this, all the workflows in DsPY like Predict etc was failing when using Prem. 
Additionally, this PR also adds `kwargs` in the constructor because in some of the examples, it does requires some additional parameters while we initialize the LLM before configuring it.
> Fix: Prem DsPY Basic Request Return type should be list not string 

- dsp/modules/aws_models.py
- dspy/teleprompt/random_search.py
- tests/modules/test_aws_models.py
EnsembledProgram can now be loaded/saved
~~Inference of programs (forward function) is now concurrent~~
Added checks for size = 0 or size > number of programs
> Fixed issue #894 and #858 (aws_models issues)

- dspy/teleprompt/mipro_optimizer_v2.py
Fixes #1190 . uses default valset behavior from  [BootstrapFewShotRandomSearch](https://github.com/stanfordnlp/dspy/blob/c65445f1fb3a08e51c65fdb15cea344476e3a2eb/dspy/teleprompt/random_search.py#L65)).
Tagging @XenonMolecule - potentially can close #1193 too?
> update default valset

- dspy/datasets/hotpotqa.py
Added trust_remote_code=True to hotpot_qa dataset to skip prompt for allowing custom code to be run when using the HotPotQA dataset.
> Add trust_remote_code arg to load hotpot_qa

- dspy/propose/dataset_summary_generator.py
The dataset summary generation was failing when log_file is None, as at line 76 it does not check if the log_file is None resulting in an exception.
I fixed the problem by adding the code to check if log_file is None before write operation.
> Bug - Dataset summary generation failing due to log file set to None

- .github/workflows/build_and_release.yml
- pyproject.toml
- setup.py
Leave default values in project files for installation from source. Default values get replaced by automation by using comments as markers instead of placeholders.
> Fix: package name and version in setup.py and pyproject.toml

- dsp/modules/googlevertexai.py
> Ensuring that candidate count for Gemini is always 1

- dspy/teleprompt/mipro_optimizer_v2.py
If program_aware_proposer parameter is set to False when compiling the program with MIPROv2 optimizer, it results in the following error - `AttributeError: 'MIPROv2' object has no attribute 'program_code_string'`. 
The error occurs on line no. 220 when program_code_string in GroundedProposer is assigned. It is due to program_code_string not set to None if program_aware_proposer is false.
> Fixed Bug - MIPROv2 fails when program_aware_proposer parameter set to False

- dsp/modules/aws_models.py
Refactors `AWSMeta` to work with Amazon SageMaker endpoints.
Fixes https://github.com/stanfordnlp/dspy/issues/1009
```python
import os
import boto3
import dspy
from sagemaker.jumpstart.model import JumpStartModel
region_name = boto3.session.Session().region_name
model = JumpStartModel(
model_id="meta-textgeneration-llama-3-70b-instruct",
model_version="2.0.2",
instance_type="ml.g5.48xlarge",
region=region_name
)
if os.environ.get('ENDPOINT_NAME'):
predictor = model.deploy(
accept_eula=input("Accept EULA? [y/n]") == "y"
)
sagemaker = dspy.Sagemaker(
region_name=region_name
)
lm_sagemaker = dspy.AWSMeta(
aws_provider=sagemaker,
model=os.environ.get('ENDPOINT_NAME', predictor.endpoint_name)
)
dspy.configure(lm=lm_sagemaker)
qa = dspy.ChainOfThought('question -> answer')
response = …
```
> fix: Support for Meta models provided by Amazon SageMaker

- dspy/retrieve/qdrant_rm.py
Add filter support for QdrantRM to support qdrant search filter like
https://qdrant.tech/documentation/concepts/filtering/
uses
> Add filter for QdrantRM

- dspy/propose/grounded_proposer.py
- dspy/teleprompt/mipro_optimizer_v2.py
**Scenario:** When compiling with MiproV2, my large trainset examples led to an error - `model context limit exceeded`. To address this, I set a custom view_data_batch_size. However, the error persisted as the parameter value was not reflected during dataset summary generation. 
**Problem:** The custom view_data_batch_size is not applied during the creation of the dataset summary in GroundedProposer. This occurs because the create_dataset_summary() function within the GroundedProposer defaults to a predefined batch size, ignoring the custom view_data_batch_size parameter value. 
**Solution:** The solution involves passing the view_data_batch_size parameter to GroundedProposer in MiproV2, ensuring it is utilized when create_dataset_summary() is called in GroundedProposer. 
**Testing:** …
> fix(MiproV2): custom view_data_batch_size for dataset summary creation

- docs/docs/faqs.md
- dsp/modules/anthropic.py
- dsp/modules/aws_providers.py
- dsp/modules/azure_openai.py
- dsp/modules/cloudflare.py
- dsp/modules/cohere.py
- dsp/modules/google.py
- dsp/modules/googlevertexai.py
- dsp/modules/gpt3.py
- dsp/modules/groq_client.py
- dsp/modules/hf_client.py
- dsp/modules/mistral.py
- dsp/modules/premai.py
- dsp/modules/snowflake.py
- dsp/utils/settings.py
- dspy/retrieve/chromadb_rm.py
- dspy/retrieve/mongodb_atlas_rm.py
- dspy/retrieve/neo4j_rm.py
- dspy/retrieve/pinecone_rm.py
allows for user-configurable backoff times across LM/RM providers.
Note that if you'd like to set individual backoff times for specific providers, you can do through the dspy context manager 
```
with dspy.context(backoff_time = ..):
dspy.OpenAI(...) # example
with dspy.context(backoff_time = ..):
dspy.AzureOpenAI(...) # example
```
> added configurable backoff max time

- pyproject.toml
- requirements.txt
This is meant to give users of this library more flexibility in the version of these dependencies that are used, as there does not appear to be a specific reason that they are pinned back currently.
The version in the lock files has not been updated.
> loosen joblib, backoff dependency restrictions

- dsp/modules/cache_utils.py
When using `dspy` in a docker without `HOME` folder, it causes a problem.  
Related to this https://github.com/stanfordnlp/dspy/issues/1115 issue as well. 
```
File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/home/app/api/main.py", line 10, in <module>
from api.routers import llm
File "/home/app/api/routers/llm.py", line 4, in <module>
import dspy
File "/usr/local/lib/python3.11/site-packages/dspy/__init__.py", line …
```
> cache:use temp dir by default

- dsp/modules/cache_utils.py
Reverts stanfordnlp/dspy#1278
@okhat @lsgrep temporarily reverting for now. will look back into how to add this PR to maintain backward compatibility with the cache soon!
> Revert "cache:use temp dir by default"

- docs/docusaurus.config.ts
This PR updates RunLLM's chat widget's script path. RunLLM switched to a new deployment framework that resolved multiple issues related to jscdn's caching. This update ensures the RunLLM's ask AI widget is more consistently up-to-date.
> Update RunLLM's chat widget script path

- dspy/propose/grounded_proposer.py
- dspy/teleprompt/utils.py
MIPROv2 was erroring out when using the latest changes on the repo (particularly  [Convert Predict and ChainOfThought into Modules, while retaining backward compatible .load()](https://github.com/stanfordnlp/dspy/commit/730fd1363f9d329db23cb2d88340268dd8cdf68d) and while using [`dspy.experimental`](https://github.com/stanfordnlp/dspy/commit/5e57bb27a8d88966c3793edd7d2001047ef1ae14))
Fixes:
1. [patches](https://github.com/stanfordnlp/dspy/pull/1280/files#diff-c76579dace3800072e78f8254f10e08dfc927275120b1127eeb8e3030e4b1eb4R394) error from [`inspect.getsource`](https://github.com/stanfordnlp/dspy/blob/b30bb8b631c106f1dc37d020c81e3ae819a92aaf/dspy/teleprompt/utils.py#L393) used in MIPROv2 to retrieve code definitions of uncompiled DSPy program. previously seeing`Error getting source code: …
> miprov2 patch for proper parsing

- dspy/teleprompt/mipro_optimizer_v2.py
I noticed weird behavior when I was using a custom metric function with MIPROv2 that returned ints rather than True/False. I realized that unlike the BootstrapFewShot optimizer, MIPROv2 didn't let you pass in a metric_threshold parameter.
This PR adds in the parameter and passes it on to the `create_n_fewshot_demo_sets` utility function.
> Add metric_threshold to MIPROv2

- dspy/primitives/module.py
- tests/primitives/test_program.py
The problem is illustrated as follows:
For a module such as the following I added to the tests:
```python3
class DuplicateModule(Module):
super().__init__()
self.p0 = dspy.Predict("question -> answer")
self.p1 = self.p0
```
Running its `named_parameters()` method would result in infinite recursion. This is due to that `Predict` is both a `Module` and a `Parameter`. Thus, according to the original arrangement of the if statements, suppose that `p0` is already visited. Then, by having the `Predict` instance already a member of the `visited` set and that it is a `Module`, the second condition would still execute when `p1` is visited.
I originally discovered this problem when using `assert_transform_module()`, which calls `Module.named_parameters()` at some point.
> Fix conditional in Module.named_parameters() to prevent infinite recursion

- dspy/retrieve/databricks_rm.py
- Extension to return extra columns in the result of the Vector Search
- Added extra error checks:  REST API error, ID column not in index, TEXT column not in index
- Docs, Doc_ids and extra columns are sorted by the search "score" in descending order
> databricks_rm: returning extra columns

- dsp/modules/hf_client.py
Fix on issue #1206.
Both mlc_chat and ChatModule are depreciated. Replaced with MLCEngine which will be suppoorted going forward.
A few considerations:
- Renaming the class to reflect the change from ChatModule
- Use EngineConfig when setting up the MLCEngine to have more control over configuration
> fix(mlc-llm): fix mlc-llm ChatModuleClient with MLCEngine

- dspy/retrieve/milvus_rm.py
I encountered the following issue while using MilvusRM. Through debugging, I found that the format of the passages returned seems incorrect. By comparing with other RM implementations, I discovered that the problem lies in the data structure returned by the forward method of MilvusRM.
This PR can address the aforementioned issue.
> fix: forward return in class MilvusRM

- dsp/modules/ollama.py
References https://github.com/stanfordnlp/dspy/issues/293#issuecomment-2270834347
Approach provided and used  by @INF800   (https://github.com/stanfordnlp/dspy/issues/293#issuecomment-1921965485  , https://github.com/stanfordnlp/dspy/pull/325 )
> fix(dspy): prompt_eval_count occasionally is None and causes TypeError

- dsp/modules/cohere.py
Simple fix to an issue where an exception is thrown when using the Cohere LLM (for prediction, with experimental=True). It was due to an extra parameter (`stop`) being passed to the API. This change checks for it and removes it.
> Fix (dspy) Remove extra argument passed to Cohere client

- dspy/evaluate/evaluate.py
Make the parameters `return_all_scores` and `return_outputs` of the Evaluate class more reasonable.
1. If I specify `return_outputs=False` when calling `__call__`, this value is not actually passed in, as `return_outputs` will take the value from `self.return_outputs` at that time.
2. Ensure that the `return_all_scores` parameter is passed in and initialized consistently with `return_outputs`.
> fix(dspy): `return_all_scores` and `return_outputs` in Evaluate class

- dsp/modules/hf.py
- dspy/retrieve/pinecone_rm.py
The error doesn't specify that you need torch (as `pip install transformers` is not the same as `pip install transformers[torch]`. This makes things a bit clearer
> feature(dspy): refined missing hf error

- dspy/predict/chain_of_thought.py
Use f-string instead of concat, and add some comments for readability.
Personally I find `signature.prepend()` a bit confusing, because in this case we are adding `rationale` to output signature, but prepend gives a feeling of adding things at the front, e.g., `question -> answer` becomes `rationale, question -> answer`.
> Minor readability fix

- docs/docs/dspy-usecases.md
Langtrace supports native tracing of DSPy:
Docs: https://docs.langtrace.ai/supported-integrations/llm-frameworks/dspy#dspy
Blogpost: https://langtrace.ai/blog/announcing-dspy-support-in-langtrace
> Include Langtrace as an adopter of Langtrace

- dspy/propose/grounded_proposer.py
Fixes the error where multiline __init__ definitions for modules are not properly parsed by the program aware regex.
Fixes #1460
> Bug Fix: Multiline init regex parsing (MIPROv2)

- docs/api/language_model_clients/Groq.md
**correction in Usage code part dspy.GROQ to dspy.GroqLM (same name as constructor is defined)**
> Correction in Usage of GroqLM in documentation

- dspy/primitives/assertions.py
Co-authored-by: chiragshah285
@chiragshah285
> Fix assertion bug with new_signature

- dspy/predict/langchain.py
- tests/predict/test_langchain.py
Before this change, if the chain has things like retriever, DSpy program will crash on `optimizer.compile()` call because the deep copy fails due to retriever not copy-able. This PR fixes the issue by only doing deep copy on `LangChainPredict`.
> Make langchain copy-able in Dspy

- docs/api/language_model_clients/Groq.md
dspy.GROQ() is working fine with recent update of dspy-ai==2.4.12. So revert the changes @okhat
> Revert "Correction in Usage of GroqLM in documentation"

- docs/docs/deep-dive/retrieval_models_clients/WeaviateRM.mdx
- dspy/datasets/dataloader.py
- dspy/retrieve/weaviate_rm.py
Load in a dataset of dspy.Example objects from the connected RM to DSPy.
This makes it easier to load in datasets for DSPy's optimizers.
Implement `from_rm` in the DataLoader with the arguments `num_samples`, `fields`, `input_keys` (similar interface as `from_json`, `from_pandas`, ...)
Add `get_objects` to RM with the arguments `num_samples` and `fields`.
Tested locally.
> Add `from_rm` to the DataLoader

- docs/docs/building-blocks/1-language_models.md
This PR contains the following changes:
1. Adds Claude direct to the Building Blocks dosc
2. Adds Claude and Llama3 from AWS to the docs.
> chore(docs): add Claude model providers to the list

- dspy/retrieve/azureaisearch_rm.py
In hybrid/vector search case, 
when calling client.search, get_embedding() is returning List[VectorQueries]: 
https://github.com/stanfordnlp/dspy/blob/main/dspy/retrieve/azureaisearch_rm.py#L380
It can directly passed to the client.search.
Currently, an extra '[]' is added when passing the vector_query to the client.search:
https://github.com/stanfordnlp/dspy/blob/main/dspy/retrieve/azureaisearch_rm.py#L258
Results in serialization error from AISearch library.
The fix is to remove that extra []. Test is done with positive result after fix.
> Fix AzureAISearchRM Error when doing vector/hybrid search

- dsp/modules/mistral.py
- pyproject.toml
Following the [mistralai package upgrade instructions](https://github.com/mistralai/client-python/blob/main/MIGRATION.md):
* change `.chat()` to `.chat.complete()`
* change `MistralClient` to `Mistral` (aliased as `MistralAI`)
Also corrected a problem with `@backoff.on_exception` where it needs object `mistralai_api_error` to exist.
> enh(mistral): Upgrade mistralai dependency from 0.4.2 to 1.0.2

- dspy/retrieve/milvus_rm.py
Problem: The MilvusRM object in our codebase is throwing an AttributeError due to a missing attribute k. This error occurs when attempting to access or use k, which has not been defined within the MilvusRM class.
Solution:
Replaced the existing attribute top_k with k.
error : AttributeError: 'MilvusRM' object has no attribute 'k'
> Fix AttributeError in MilvusRM: Add missing attribute 'k'

- dspy/functional/functional.py
- tests/functional/test_functional.py
- tests/functional/test_signature_opt_typed.py
- tests/functional/test_signature_typed.py
See  #1349
This uses pydantics [`TypeAdapter`](https://docs.pydantic.dev/latest/api/type_adapter/) to wrap objects into pydantic serializable instances.
This also eliminates the need to prepend single values with a value field in the JSON schema,, e.g. a field of type `list[int]` will now be expressed as `[1,2,3]` instead of `{"value": [1,2,3]}`. 
I also added tests for the most common field types to ensure that they are deserialized properly.
> fix(dspy): Allow `Union` with pydantic objects in `TypedPredictor` 

- dspy/teleprompt/random_search.py
- tests/teleprompt/test_random_search.py
Fix a few odds in the BootstrapFewShotWithRandomSearch optimizer:
- Zombie code should be deleted. 
- f-string for print/logging.
- variable names like `program2` are confusing.
Also added basic unit test case for BootstrapFewShotWithRandomSearch.
> Typo/nit fixes and add tests for BoostrapWithRandomSearch

- dspy/evaluate/evaluate.py
Related to issue https://github.com/stanfordnlp/dspy/issues/788
This prints out the example inputs and a stacktrace for the error that occurred. I understand that this change would add more excessive error messages that you have tried to avoid
> The current behavior was designed to limit excessive outputted error messages, partly handled through [how many errors can occur before completely halting execution](https://github.com/stanfordnlp/dspy/blob/5c5e8071916688f462b3b779e0c6adca42f660b8/dspy/evaluate/evaluate.py#L140)
But at least to me this has been the number 1 issue I have been experiencing when testing out dspy for the past week. This change works like a charm in my use case.
If the printed error message seems too excessive with large datasets, then another option would be to add …
> Improve error logging with a stacktrace

- dspy/primitives/module.py
- tests/primitives/test_module.py
The current solution has issues if `dspy.BaseModule` contains non-copyable instances. The proposed approach is:
1. Get all attributes, if it is a `BaseModule`, try deep copying, if failed then do recursive call.
2. If the attr is not a `BaseModule`, try deep copying, if failed try shallow copying, if still failed just copying over the reference. 
3. It won't hit infinite recursion because once a module has no attributes that is a `BaseModule`, the recursion stops.
Added unit tests to test it.
> Fix dspy Module's deepcopy

- docs/docs/deep-dive/optimizers/copro.mdx
- dspy/teleprompt/mipro_optimizer.py
Fixed Docstring in Deprecated MIPRO (v1) Optimizer.
Fixed trainset/devset confusion in COPRO Documentation.
Fixes #940 
Fixes #949
> Optimizer Doc Fixes

- dspy/clients/lm.py
Uses the "LITELLM_LOCAL_MODEL_COST_MAP" variable to turn off an API call when liteLLM is imported.
Set 'litellm.telemetry = False' as well.
https://docs.litellm.ai/docs/completion/token_usage#9-register_model
https://github.com/BerriAI/litellm/blob/main/litellm/__init__.py
Ran ruff this time, thanks for the heads up @okhat !
> lm.py: disable telemetry in litellm

- dspy/functional/functional.py
Main issue what the output was a BaseModel already so no need to create one, added:
```
if isinstance(dsp.settings.lm, dspy.LM):
parsing_result = output
else:
parsing_result = from_json(output)
```
Closes #1541
> Make output processing in typed Pred compatible to LM Module

- dspy/evaluate/evaluate.py
- dspy/teleprompt/copro_optimizer.py
Resolve #1286 
The warning was completely wrong, we should just remove it and let it error out. Made a few minor lint fixes along with the deletion.
A followup is to explicitly document how to change logging level for user. The `show_logging` util should work.
> Fix misleading warning

- dspy/teleprompt/signature_opt_typed.py
This adds a `num_retries` option to
`signature_opt_typed.optimize_signature()`. This is passed through to both `TypedChainOfThought` and `TypedPredictor`.
**Why?** Because I was stuck. I kept getting this error message:
> Value error, Never propose a signature already in the list above.: proposed_signature (error type: value_error)
I can get around this error by raising the model's temperature as well as setting this to `num_retries=10`.
Note: I see comments about not supporting temperature because it breaks parsing. While that's true, having temp be zero also leads to getting completely stuck because there's no simple solution for common errors like this. With high enough temperature and enough retries, I should be able to unstick myself from any situation.
> Add `num_retries` to signature_opt_typed

- dspy/propose/grounded_proposer.py
Fixes #1580 
When an exception occurs during bootstrapping demos, MIPROv2 switches to running without task demonstrations. However, MIPROv2 previously did not have support for running without demos. This PR adds checks so that running without demos will not cause MIPROv2 to crash and instead gracefully adds "No task demos provided." to the meta prompt.
> Fix MIPROv2 exception on demoless runs

- dspy/propose/grounded_proposer.py
This quick one-line fix switches a min to a max in the demo size check for MIPROv2.
This line is intended to ensure that at least one instruction is proposed, even if no demos are bootstrapped in MIPROv2. Instead, it caps the number of instructions proposed per module at one.
> [MIPROv2] Fixed min to max in demo check

- dspy/adapters/chat_adapter.py
- tests/functional/test_signature_typed.py
When fields are Pydantic objects, the chat_adapter was formatting them as python code, which led to some strange behavior (BootstrapFewShot would start off with JSON and then revert to unparseable python code after it started adding examples).
I'm not sure if I put the tests in the right spot, but it seemed convenient to leverage situations that were already being created. I also did `dataclasses` since they were right there.
> chat_adapter: Format fields as JSON

- dspy/clients/lm.py
As litellm becomes an official dependency of DSPy, we no longer need the hacky import handling code. 
Also reformat the code for better readability.
> Remove legacy code from client/lm.py and reformat

- dspy/predict/predict.py
- dspy/primitives/module.py
- dspy/signatures/signature.py
- tests/predict/test_predict.py
- tests/signatures/test_signature.py
resolve #1045 
Change summary:
- Add a `dump_state`/`load_state` pair to Signature class for better modularization.
- Remove the `save_verbose` option, as it doesn't make sense to change input fields to output fields at loading time. As we are doing "weights-only" saving, the signatures' architecture should match, i.e., input fields and output fields' number and name.  Only changeable attributes should be included with saving.
- Save prefix for every field as requested in #1045.
- Added unit testing.
> Fix signature saving at Predict saving

- dspy/teleprompt/finetune.py
Fixes #1631 
I think if you are somehow relying on the training data directory to exist but not using BSFT then thats a skill issue
Also this file will be irrelevant once #1594 is merged
> Move path creation to BSFS init

- dspy/primitives/module.py
- tests/retrieve/test_llama_index_rm.py
resolve #1634 
Basically we should only include the `use_legacy_saving` for `dspy.Module`.
> Fix saving/loading retriever

- pyproject.toml
- setup.py
The version in pyproject.toml and setup.py are wrong, we should use `2.5.13.dev0` for now. Basically we should write it as the next minor release + `.dev0`, which is a standard way (not officially documented though).
> Fix the package version and name

- dspy/predict/predict.py
- dspy/primitives/program.py
This PR introduces several helper methods for the `Module` and `Predict` classes in order to allow for convenient ways to:
1. Check if two modules (e.g. a student and a teacher program) are "structurally_equivalent", which is a precondition for many teleprompters to work properly,
2. Manage and ensure consistency of the LM(s) used by a program, either through `dspy.settings.lm` or predictor LMs.
Shared below are some example usages. These methods are meant to be used by the other, internal DSPy classes.
**Example use of the structural equivalency methods**
```
student._assert_structural_equivalency(teacher)
assert not student._assert_no_shared_predictor(teacher)
```
**Example use of the Module level LM methods**
```
program._assert_lm_consistency()
if dspy.settings.lm: …
```
> feature(dspy): Add helper methods to `Module` and `Predict` classes

- dspy/functional/functional.py
- tests/functional/test_functional.py
resolve #1644 
We don't need a standalone signature attribute in `TypePredictor`, because it's never actually used. We keep the `self.signature` to be valid for backward compatibility
> Fix the saving of TypePredictor

- dspy/adapters/chat_adapter.py
- dspy/predict/predict.py
- dspy/signatures/utils.py
- dspy/utils/dummies.py
- tests/functional/test_functional.py
- tests/functional/test_signature_typed.py
> Fix TypedPredictor formatting with list output values

- docs/mkdocs.yml
Added URL redirects to handle the legacy paths starting with `/docs/*` that were causing 404 errors for users. This fixes the broken links issue where users were trying to access URLs like `docs/tutorials/rag` instead of `tutorials/rag`.
- Added mkdocs-redirects plugin configuration to handle legacy URL patterns
- Implemented redirects for all tutorial pages:
- `/docs/tutorials/rag` → `/tutorials/rag`
- `/docs/tutorials/simplified-baleen` → `/tutorials/simplified-baleen`
- `/docs/tutorials/summarization` → `/tutorials/summarization`
- `/docs/tutorials/other_tutorial` → `/tutorials/other_tutorial`
- `/docs/tutorials/examples` → `/tutorials/examples`
- Verified redirects work locally using `mkdocs serve`
- Tested accessing old URLs to confirm proper redirection
- Ensured existing URLs …
> Add URL redirects for legacy /docs/* paths

- docs/mkdocs.yml
Added URL redirects to handle the legacy paths starting with `/docs/*` that were causing 404 errors for users. This fixes the broken links issue where users were trying to access URLs with the `docs/` prefix instead of directly accessing the pages.
* Added redirect configurations for all documentation sections in mkdocs.yml:
* Quick Start:
* `/docs/quick-start/installation` → `/quick-start/installation`
* `/docs/quick-start/getting-started-01` → `/quick-start/getting-started-01`
* `/docs/quick-start/getting-started-02` → `/quick-start/getting-started-02`
* Building Blocks:
* `/docs/building-blocks/solving_your_task` → `/building-blocks/solving_your_task`
* `/docs/building-blocks/1-language_models` → `/building-blocks/1-language_models`
* `/docs/building-blocks/2-signatures` → …
> Add documentation redirects to fix legacy /docs/* URLs

- dspy/evaluate/evaluate.py
- tests/evaluate/test_evaluate.py
If I write a DSPy module that returns an object that is not coercable to `dict`, I cannot currently call `Evaluate()` on the module with `display_table=True` because `display_table()` assumes that all outputs are dictionaries. This PR fixes the issue and adds a test.
> Fix error in Evaluate with display_table=True with outputs that cannot be converted to dict

- docs/mkdocs.yml
The assertions.md from the https://dspy-docs.vercel.app/deep-dive/modules/assertions.md
is removed and giving the 404 error..fix for that
> added the changes for missing assertion.md file in the modules

- dspy/clients/lm.py
- dspy/utils/__init__.py
- dspy/utils/callback.py
- tests/callback/test_callback.py
Some fixes to callbacks for better readability and usability, including:
- Rename Adapter-related callbacks to have `adapter` in the name for clarity, as `on_parse_start` is a bit ambiguous.
- Some code simplifications, e.g., reduce nesting levels.
- Docstring and error message improvements.
> Some minor fixes to the newly introduced callback

- docs/mkdocs.yml
Added redirects for non-numbered versions of Building Blocks documentation pages to their numbered counterparts. This ensures that URLs without version numbers in the path will correctly redirect to the current numbered versions.
For example:
- `docs/building-blocks/signatures.md` → `building-blocks/2-signatures.md`
- `docs/building-blocks/modules.md` → `building-blocks/3-modules.md`
- Added 8 new redirects in mkdocs.yml for all Building Blocks documentation pages
- Maintains consistent URL structure while supporting both numbered and non-numbered paths
- No content changes, only URL routing updates
- Verified all new redirect paths resolve to correct numbered versions
- Existing redirects remain unchanged and functional
This change improves documentation accessibility by supporting more …
> Add non-numbered version redirects for Building Blocks documentation

- dspy/adapters/__init__.py
- dspy/adapters/chat_adapter.py
- dspy/adapters/json_adapter.py
- dspy/predict/react.py
- dspy/retrieve/retrieve.py
- dspy/teleprompt/bootstrap.py
- dspy/teleprompt/utils.py
- tests/dsp_LM/predict/test_react.py
- tests/predict/test_react.py
- Redesigns dspy.ReAct
- Adjusts BootstrapFS: handle repeat calls to a module; transpose order for max_rounds
- Adjusts ChatAdapter: handle incomplete demos better
> Revamp ReAct, adjust Bootstrap, adjust ChatAdapter

- dspy/clients/lm.py
- tests/clients/test_lm.py
Add retries to LM calls with LiteLLM, and improve LM docstrings while we're here
> Add retries to LM calls with LiteLLM

- docs/mkdocs.yml
This pull request reorganizes the `nav` section in the `docs/mkdocs.yml` file to improve the structure and clarity of the documentation. The most important changes include moving the Tutorials section and renaming some community-related entries.
Reorganization of `nav` section:
* Moved the `Tutorials` section to a new position in the `nav` hierarchy. (`docs/mkdocs.yml` [[1]](diffhunk://#diff-7618337a88ea47f9b778a21f0e17d43eab2aba4880c6be2d95a7bf95e4b8b2dfL15-L20) [[2]](diffhunk://#diff-7618337a88ea47f9b778a21f0e17d43eab2aba4880c6be2d95a7bf95e4b8b2dfL84-R90)
Renaming and restructuring community-related entries:
* Renamed `Community Resources` and `Use Cases` to more descriptive names. (`docs/mkdocs.yml` [docs/mkdocs.ymlL84-R90](diffhunk://#diff-7618337a88ea47f9b778a21f0e17d43eab2aba4880c6be …
> Final Touch on restructure navigation in mkdocs.yml

- docs/mkdocs.yml
- tests/docs/test_mkdocs_links.py
Add test to validate markdown files referenced in mkdocs.yml
This PR adds a test to ensure all markdown files referenced in the navigation section of mkdocs.yml exist in the docs directory. This helps prevent broken links and ensures documentation integrity.
Changes:
- Added new test `test_nav_files_exist` that:
- Parses mkdocs.yml to extract markdown file paths
- Verifies each file exists in docs/docs directory
- Provides clear error message for any missing files
The test helps catch:
- Typos in file paths
- Missing documentation files
- Incorrect file references
Test location: tests/docs/test_mkdocs_links.py
> Add test to validate markdown files referenced in mkdocs.yml

- poetry.lock
- pyproject.toml
- requirements.txt
Add tenacity as a dependency to support LiteLLM retries
> Add tenacity as a dependency to support LM retries with LiteLLM

- dspy/__init__.py
- dspy/clients/anyscale.py
- dspy/clients/finetune.py
- dspy/clients/lm.py
- dspy/clients/lm_finetune_utils.py
- dspy/clients/openai.py
- dspy/evaluate/evaluate.py
- dspy/primitives/assertions.py
- dspy/retrieve/faiss_rm.py
- dspy/teleprompt/bootstrap.py
- dspy/teleprompt/copro_optimizer.py
- dspy/teleprompt/finetune_teleprompter.py
- dspy/teleprompt/mipro_optimizer_v2.py
- dspy/utils/__init__.py
- dspy/utils/logging.py
- dspy/utils/logging_utils.py
This PR replaces the current structlog-based logger by standard logging module-based logger. The proposed approach is simpler and more robust. Furthermore, it doesn't affect dependency package's logging setup, e.g., OpenAI's logger will remain at WARNING level. 
People can also enable or disable DSPy event logging by  calling `dspy.enable_logging()`/`dspy.disable_logging()`.
Sample logging (with this PR's change) from running MiproV2 optimizer:
```
(dspy) *[fix-logger][~/Documents/mlflow_team/dspy]$ python3 tmp.py
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 7473/7473 [00:00<00:00, 67228.69it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 1319/1319 …
```
> Rework dspy logger

- dspy/predict/predict.py
- tests/predict/test_predict.py
Currently, loading a predictor after optimization requires two separate lines:
```python
predictor = dspy.Predict("question -> answer")
predictor.load(saved_path)
```
This PR adds support for chainable loading to improve code ergonomics:
```python
predictor = dspy.Predict("question -> answer").load(saved_path, return_self=True)
```
- Modified `load_state()` and `_load_state_legacy()` to return `self` for chaining
- Added a new `return_self` parameter to `load()` method
- Added comprehensive tests for both traditional and chainable loading patterns
- Maintained backward compatibility with existing code by defaulting `return_self=False`
Added two new test cases:
- `test_chainable_load`: Verifies both traditional and chainable loading methods
- `test_load_state_chaining`: Ensures state …
> Add chainable loading for Predict modules

- dspy/clients/__init__.py
- dspy/clients/embedding.py
- dspy/clients/lm.py
- tests/clients/test_embedding.py
Very simple `dspy.Embedding` supports:
- Hosted embedding model, we use litellm to send the request, and only take the embedding fields from the response.
- Custom embedding model, users can pass a custom callable to `dspy.Embedding`, and the output is just the custom callable's output.
Added unit test for both scenarios. 
Confirmed that the cache works:
```
(dspy) *[dspy-embedding][~/Documents/mlflow_team/dspy]$ python3
Python 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 10:07:17) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dspy;import time;embedder = dspy.Embedding("openai/text-embedding-ada-002")
>>> start=time.time();geez = embedder(["oh my god", "holy geese and elephant", "ohhhh hoover dam"]);print("TOTAL …
```
> Add `dspy.Embedding`

- poetry.lock
- pyproject.toml
- requirements.txt
We've migrated from `structlog` to standard python logging module, as `structlog` is an overkill for DSPy now. This PR cleans up the dependency. 
Ran `poetry update structlog` to update the `poetry.lock` file.
> Remove `structlog` dependency

- dspy/clients/lm.py
- tests/clients/test_lm.py
Fixes for OpenAI / Azure OpenAI compatibility with LiteLLM router
> Fixes for OpenAI / Azure OpenAI compatibility with LiteLLM router

- dsp/utils/settings.py
- dspy/clients/lm.py
default behavior to suppress litellm logs to avoid logging for every dspy.LM call.
related to #1619 and https://github.com/BerriAI/litellm/issues/5598#issuecomment-2339245304
> add flag to suppress litellm logs in dspy.LM

- dspy/retrieve/neo4j_rm.py
I noticed that litellm has added an embedding module, which is a good integration, 
and neo4j_rm still does not support callback functions. 
This PR is here for this.
> neo4j_rm support litellm embedding model

- dspy/clients/databricks.py
- dspy/clients/lm.py
- dspy/clients/openai.py
- dspy/clients/provider.py
- dspy/teleprompt/bootstrap_finetune.py
- examples/finetune/databricks_finetuning.py
- tests/clients/test_databricks.py
Add Databricks finetuning support. 
Most of the complexity results from orchestrating the databricks jobs, this integration handles the following things:
- Create a directory in Databricks Unity Catalog and upload the training data to the directory.
- Kick off the finetuning job.
- After the finetuning is done, automatically create/update the endpoint on databricks model serving platform. 
- The create endpoint's name is returned, and used to override the original LM. 
Similar to OpenAI provider, we are making blocking calls in `finetune()` method, which means the method will block until the serving endpoint is successfully created (or crash in the middle). The blocking method is wrapped in the `LM.finetune()` method, which sends this blocking method into a background thread. But …
> Databricks finetuning integration

- dspy/adapters/chat_adapter.py
Using secure_ascii=False provides better support for Chinese characters directly
before:
```
[[ ## json_output ## ]]
[{"type": "narration", "content": "\u5c0f\u660e\u8d70\u51fa\u5bb6\u95e8\uff0c\u8ddf\u90bb\u5c45\u6253\u62db\u547c"}, {"type": "dialogue", "name": "\u5c0f\u660e", "reaction": "\u9ad8\u5174", "content": "\u4f60\u597d\u5440"}, {"type": "narration", "content": "\u90bb\u5c45\u5fae\u7b11\u671d\u4ed6\u70b9\u5934"}, {"type": "voiceover", "name": "\u90bb\u5c45", "reaction": "\u5185\u5fc3\u5947\u602a", "content": "\u8fd9\u5c0f\u5b50\u4eca\u5929\u600e\u4e48\u5bf9\u6211\u8fd9\u4e48\u6709\u793c\u8c8c"}]
[[ ## completed ## ]]
```
after:
```
[[ ## json_output ## ]]
[{"type": "narration", "content": "小明走出家门，跟邻居打招呼"}, {"type": "dialogue", "name": "小明", "reaction": "高兴", "content": "你好呀"}, …
```
> fix: prevent Chinese examples from being converted to Unicode encoding

- dsp/utils/settings.py
- dspy/clients/__init__.py
- dspy/clients/lm.py
We introduced litellm logging suppression in #1768, but we were configuring `litellm` inside the `__init__` call. So if users do:
```
lm = dspy.LM("...")
dspy.settings.configure(suppress_debug_info=False)
lm("some query")
```
Then the logging won't be turned on. In this PR I am introducing a pair of util functions: `dspy.clients.enable_litellm_logging()` and `dspy.client.disable_litellm_logging()` to turn on/off the litellm logging dynamically.
> Change the way of enable/disable litellm logging

- dspy/adapters/image_utils.py
- dspy/primitives/example.py
- tests/primitives/test_example.py
Printing DSPy Examples containing images creates problems because they flood the console / notebook outputs with massive base64-encoded strings. 
Base64-encoded images can be thousands of characters long, making it nearly impossible to read other important output or debug information.
> fix: No longer crashing notebooks & spamming console w image urls

- dspy/evaluate/evaluate.py
- tests/evaluate/test_evaluate.py
Fix additional evaluation display failures for non-dict objects
> Fix additional evaluation display failures for non-dict objects

- dspy/predict/knn.py
- dspy/teleprompt/knn_fewshot.py
Simple PR to make KNN compatible with the new dspy.Embedding class that features caching for LiteLLM embeddings
> Use dspy.Embedding for KNN

- dspy/teleprompt/bettertogether.py
Use logger.info instead of print for better tracking.
> Replace print by logger.info in BetterTogether optimizer

- poetry.lock
- pyproject.toml
hey there!
I wanted to install dspy in a project where I also use litellm more explicitly, but unfortunately I couldn't update litellm version independently, I'm then adding the caret^ to flexibilize the minor version of it
now, that may be a risk as indeed I've seen litellm having quite few breaking changes in the past, @krypticmouse you were the one to change that from ^ to a explicit version before, do you remember what was the reason for that? https://github.com/stanfordnlp/dspy/commit/f5a781ca1e443a445cf8cbab8e6f0c8580375fae
> Make litellm version more flexible

- dspy/datasets/dataloader.py
Minor style fix of `dataloader.py`
> Style fix for Dataloader

- dspy/adapters/chat_adapter.py
This PR is doing trivial style improvements for chat_adapter.py. A few callouts:
- Replace relative imports by absolute imports: https://google.github.io/styleguide/pyguide.html#224-decision
- Avoid variable name with ending `_`, e.g., `type_`.
- No two-space indent in the docstring.
> Style fix for chat_adapter.py

- docs/docs/learn/programming/signatures.md
Noticed a duplicate sentence in the docs for signatures.
> Removing duplicate sentence in signature docs

- dspy/predict/react.py
- tests/predict/test_react.py
The big reason for this is to pass parameters out-of-band, e.g. a user_id to ensure the LLM doesn't get the wrong data.
The unit test includes a usage, you can't use it as a decorator this way, but it works.
The alternative, of course, is to have a very long function and have all the tools be nested functions. It works, but can lead to some very long functions. I prefer long classes over long functions.
> Allow react.Tool to wrap methods

- dspy/adapters/chat_adapter.py
- dspy/adapters/json_adapter.py
- dspy/adapters/utils.py
- tests/functional/test_signature_typed.py
- tests/predict/test_predict.py
- tests/reliability/complex_types/generated/test_many_types_1/inputs/input1.json
- tests/reliability/complex_types/generated/test_many_types_1/inputs/input2.json
- tests/reliability/complex_types/generated/test_many_types_1/program.py
Fixes #1826
In addition to the unit tests introduced in this PR, I verified that generated integration tests for a program with enum inputs and enum outputs pass as well with `ChatAdapter` *and* `JSONAdapter` 
```
test_generated.py ..ssssssssssssssssssssssss                                        [100%]
…
=============== 2 passed, 24 skipped, 117 deselected, 4 warnings in 20.02s ================
```
```
test_generated.py ..ssssssssssssssssssssssss                                        [100%]
…
=============== 2 passed, 24 skipped, 117 deselected, 4 warnings in 41.69s ================
```
> Adapters: Support JSON serialization of all pydantic types (e.g. datetimes, enums, etc.)

- dspy/predict/react.py
Signed-off-by: myan <myan@redhat.com>
Resolve: https://github.com/stanfordnlp/dspy/issues/1836
> Include the Signature `__doc__` in the system message for the ReAct module.

- dspy/predict/__init__.py
- dspy/predict/react.py
- dspy/utils/callback.py
- tests/callback/test_callback.py
Update the `BaseCallback` class to handle `Tool` for tool calling.
> Add on_tool_start/end callbacks

- docs/docs/community/use-cases.md
- docs/docs/dspy-usecases.md
Hi Team, I am one of the maintainers of [OpenLIT](https://github.com/openlit/openlit) and we support Obserability for LLM apps built using DSPy, It is all OpenTelemetry-native so the traces and metrics can be sent to any platfrom like [Grafana](https://grafana.com/docs/grafana-cloud/monitor-applications/ai-observability/introduction/) or any [OSS OTel tools](https://opentelemetry.io/blog/2024/llm-observability/)
Figured the mention here might be useful for developers using DSPy hence adding the reference in documentation page.
> Add OpenLIT as integration in usecase docs

- dspy/clients/lm.py
- poetry.lock
- pyproject.toml
- requirements.txt
- tests/caching/test_caching.py
- tests/clients/test_lm.py
Integrate cachetools for in-memory LM caching, including unhashable types & pydantic
Fixes #1759
> Integrate cachetools for in-memory LM caching, including unhashable types & pydantic

- dspy/retrieve/databricks_rm.py
Make DatabricksRM compatible with Mosaic agent framework, which has some requirements on the return value, and require some extra setup code.
> Make DatabricksRM compatible with Mosaic agent framework

- dspy/clients/lm.py
- tests/caching/test_caching.py
- tests/clients/test_lm.py
- tests/test_utils/server/litellm_server_config.yaml
Caching: Use reentrant locks, don't discard callables (or any other unhashable object in the future) from the cache key
> Caching: Use reentrant locks, don't discard callables (or any other unhashable object in the future) from the cache key

- dspy/clients/lm.py
- tests/caching/test_caching.py
Caching fix - only try/cache key creation
> Caching fix - only try/cache key creation

- dspy/adapters/json_adapter.py
- dspy/clients/lm.py
- tests/reliability/test_pydantic_models.py
- tests/reliability/utils.py
- tests/test_json_adapter.py
Support structured outputs response format based on signature in JSON adapter
> Support structured outputs response format based on signature in JSON adapter

- dspy/adapters/base.py
- dspy/clients/lm.py
This PR allows `Predict` to return logprobs of each token as part of `Prediction`.
**If you want logprobs:**
Set `logprobs=True` and optionally `top_logprobs` (int between 0 and 20, see [openai doc](https://platform.openai.com/docs/api-reference/chat/create#chat-create-top_logprobs) for details):
```
import dspy
from dspy import Predict
predict_instance = Predict("question -> answer")
lm = dspy.LM("gpt-4o-mini", logprobs=True)
dspy.configure(lm=lm)
result = predict_instance(question="Where is the Eiffel Tower located?")
print(result)
```
Output:
```
Prediction(
answer='The Eiffel Tower is located in Paris, France, on the Champ de Mars near the Seine River.',
logprobs={'content': [{'token': '[[', 'bytes': [91, 91], 'logprob': -2.1008714e-06, 'top_logprobs': []}, {'token': ' ##', 'bytes': …
```
> Support returning logprobs in Predictor

- dspy/retrieve/databricks_rm.py
As requested by Mosaic agent framework, we need to give users the flexibility to choose the column name for doc uri in order for agent framework to successfully render the trace. Previously we made a wrong assumption on the doc_uri format. 
We will also do the following in the future:
- Remove the `use_with_databricks_agent_framework` flag and the logic branch.
- Move the Document conversion logic into MLflow.
- Delete the `set_retriever_schema` call. 
This PR keeps it small to only unblock users, will have followup PRs for the other items.
> Add docs_uri_column_name to DatabricksRM

- docs/docs/learn/programming/signatures.md
Noticed two broken links at the bottom of https://dspy.ai/learn/programming/signatures/ so have updated the links accordingly. I've chosen the second broken link to redirect to https://dspy.ai/learn/optimization/optimizers/ rather than https://dspy.ai/learn/optimization/overview/ but this is equivocal.
> Fixed 404 error in docs links

- dspy/dsp/utils/settings.py
- dspy/utils/asyncify.py
- dspy/utils/parallelizer.py
1. Only one unique thread (which can be any thread!) can call `dspy.configure`.
2. It affects a global state, visible to all. As a result, user threads work, but they shouldn't be mixed with concurrent changes to dspy.configure from the "main" thread. (In the future, one can add warnings for this, if there are near-in-time accesses to the configuration followed by `.configure` calls.)
3. Any thread can use `dspy.context`. It propagates to child threads created with DSPy primitives: `Parallel`, `asyncify`, etc.
> Refined semantics for Settings thread-safety

- dspy/__init__.py
- dspy/adapters/__init__.py
- dspy/clients/__init__.py
- dspy/datasets/__init__.py
- dspy/evaluate/__init__.py
- dspy/experimental/__init__.py
- dspy/experimental/synthesizer/__init__.py
- dspy/predict/__init__.py
- dspy/predict/avatar/__init__.py
- dspy/primitives/__init__.py
- dspy/primitives/program.py
- dspy/primitives/python_interpreter.py
- dspy/propose/__init__.py
- dspy/propose/grounded_proposer.py
- dspy/retrieve/__init__.py
- dspy/retrievers/__init__.py
- dspy/signatures/__init__.py
- dspy/teleprompt/__init__.py
- dspy/teleprompt/bootstrap_finetune.py
- dspy/utils/__init__.py
- pyproject.toml
We are replacing all relative imports by absolute imports to get compatible with Google style guide. This is beneficial for automatic API reference generation, which we are adding now.
> Replace relative imports by absolute imports

- dspy/primitives/module.py
- dspy/utils/saving.py
- tests/primitives/test_module.py
- tests/utils/test_saving.py
Earlier we raise warning on micro version mismatch for python and cloudpickle, with this PR we only check the major version.
> Loose the version check between saving/loading

- docs/mkdocs.yml
We should use consistent 4 space, instead of mixing 2 space and 4 space in the same file. 
There is a caveat that the palette section cannot be forced to 4 spaces:
forcing toggle to indent by 4 spaces break the mkdocs.
> Fix indents in mkdocs.yml

- dspy/adapters/json_adapter.py
A few small fixes:
- Use absolute import instead of relative imports. 
- Consistently use 4-space indentations.
- `_logger` should be replaced by `logger`. This is weird at first glance because `_logger` seems to be a private member, however it is a standard approach to use `logger`.  https://realpython.com/python-logging/#instantiating-your-logger
> Small style fix for json_adapter

- dspy/teleprompt/bootstrap.py
- dspy/utils/asyncify.py
- dspy/utils/dummies.py
These docstring right now renders oddly on the API reference page, we need to fix them.
> [Doc PR Part 2] Fix docstring that renders oddly on mkdocs-powered API reference page

- docs/README.md
- docs/docs/stylesheets/extra.css
- docs/mkdocs.yml
- docs/scripts/generate_api_docs.py
- docs/scripts/generate_api_summary.py
- dspy/experimental/synthesizer/__init__.py
We add two scripts:
1. `generate_api_docs.py`: Generate an .md file for each public class/function.
2. `generate_api_summary.py`: Generate the index in `mkdocs.yml` to refer to the doc page for each public class/function.
At doc deployment time, these 2 scripts should be executed to generate the latest documentation. 
Some notes:
1. Many DSPy classes/functions can be accessed by multiple path, e.g., `dspy.ChainOfThought`, `dspy.predict.ChainOfThought`, `dspy.predict.chain_of_thought.ChainOfThought` all point to the same thing. We only generate doc for the top level `dspy.ChainOfThought`, which is our recommended path
2. We only generate API references for classes/functions that are exposed through `__all__` attribute in `__init__.py` files. Or say we only generate API reference for …
> [Doc PR Part 3] Add scripts to automatically generate API reference md files

- dspy/retrieve/databricks_rm.py
Right now in the following code, it's possible that key `data_array` doesn't exist, which leads to a opaque error to users. This happens when Databricks vector search index is not ready.  We should not fail when this happens, and just return empty results.
```
for _, data_row in enumerate(results["result"]["data_array"]):
item = {}
for col_name, val in zip(col_names, data_row):
item[col_name] = val
items += [item]
```
> Allow returning empty results when nothing is retrieved from DatabricksRM

- dspy/utils/streaming.py
Two small fixes in order to render correctly on API reference page:
- Empty line before "Returns" section
- Use code block for code example section.
Before:
After:
> Fix streamify docstring

- docs/docs/stylesheets/extra.css
- docs/requirements.txt
The previous font size is too big, we are making it smaller.
Effect:
> Make the code example more readable

- dspy/primitives/module.py
Prompt users to save by pickle when having issues with saving in json.
> Better error msg when failing to save state with json

- dspy/primitives/runner.js
PythonInterpreter support for imported libraries in code
helps resolve cases like #1004
> support for code imported libraries

- dspy/teleprompt/mipro_optimizer_v2.py
Simply updates the type definition of the auto parameter in MIPRO
> fix: types for the auto param in MIPRO

- docs/docs/api/index.md
- docs/mkdocs.yml
- docs/scripts/generate_api_docs.py
- docs/scripts/generate_api_summary.py
Add a landing page for DSPy api reference doc. right now the landing page is `dspy.Adapter`:
> Add landing page for api reference

- dspy/predict/react.py
- tests/predict/test_react.py
Currently we are not parsing the pydantic arg in dspy.ReAct, instead we are just feeding the dict as pydantic arg. This is problematic, see below for a simple reproduce:
```
from pydantic import BaseModel
import dspy
dspy.settings.configure(lm=dspy.LM("openai/gpt-4o-mini"))
class CalendarEvent(BaseModel):
name: str
date: str
participants: dict[str, str]
def write_invitation_letter(participant_name: str, event_info: CalendarEvent):
if participant_name not in event_info.participants:
return None
return f"It's my honor to invite {participant_name} to event {event_info.name} on {event_info.date}"
class InvitationSignature(dspy.Signature):
participant_name: str = dspy.InputField(desc="The name of the participant to invite")
event_info: CalendarEvent = dspy.InputField(desc="The information …
```
> Add arg parsing for dspy.ReAct

- docs/docs/stylesheets/extra.css
There is a font mismatch in linenos and code classed in the docs codeblocks, that lead to misalignment:
Proposing a fix to make linenos class font-size same as code, we can completely remove the font-size thing as well but that'll make some codeblock scrollable which I think is why this change was done in the first place. Hence adding a new CSS field.
> Make linenos font size same as code blocks

- dspy/datasets/math.py
Resolve #3358 
The original dataset has been taken down, and the replacement is `DigitalLearningGmbH/MATH-lighteval`. 
Tested manually:
```
(dspy) (base) [fix-math-dataset][~/Documents/mlflow_team/dspy]$ python3
Python 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 10:07:17) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from dspy.datasets import MATH
>>> dataset = MATH(subset='algebra')
Downloading readme: 100%|██████████████████████████████████████████████████████████████████████████████████████| 8.41k/8.41k [00:00<00:00, 80.2kB/s]
Downloading data: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 505k/505k [00:00<00:00, 1.00MB/s]
Downloading data: …
```
> Redirect math dataset to DigitalLearningGmbH/MATH-lighteval

- dspy/propose/grounded_proposer.py
- dspy/teleprompt/mipro_optimizer_v2.py
In some cases, only 1 demo was included in the meta-prompt. This occurred when few-shot examples were generated with a size of 1 (since the size is randomly chosen between 1: max_bootstrap_fewshot), and when max_bootstrap_fewshot is set to 1.
We wanted for the # of few-shot examples in the prompt to always equal 3 to avoid potential overfitting of the generated instruction to a single example.
We will essentially did the following: 
prompt_demos = (my_demos + all_other_demos)[:min(3, len(my_demos + all_other_demos))]
Which will give us 3 demos for all prompts, unless there are less than 3 demos total across all bootstrapped few-shot examples. Note that we keep the demos empty for a single instruction generation, just in case demos end up being counter productive in the meta prompt.
- …
> Enforcing 3 Demos in MIPROv2 Meta Prompt

- dspy/propose/grounded_proposer.py
if we set_tip_random to be False, selected_tip is not defined.
Fix by initializing with None
> Fix "name 'selected_tip' is not defined error"

- dspy/predict/predict.py
- tests/predict/test_predict.py
Simple fix for https://github.com/stanfordnlp/dspy/issues/3920
When dumping state check if the field is a list, and if so convert each item to a serializable dict if applicable. Lists of images are not handled.
I also changed it so that models are converted to dicts rather than a JSON string. This makes more sense to me as then the entire resulting object will be converted to a JSON string later.
I added a simple test case that passes.
> Handle lists of models in parameters

- dspy/clients/lm.py
- tests/clients/test_lm.py
This PR is to disable cache_in_memory when we run in production environment. 
While LRU cache is good for training and evaluation, we won't want the cache to be growing forever since it will crash the machine with Out of Memory after a while.
cc @okhat, @CyrusNuevoDia 
- Introduce cache_in_memory: True, so caller can disable the behavior of in memory caching but still be able to leverage litellm cache via redis or disk
> feat: separate the in memory cache from litellm cache

- dspy/clients/base_lm.py
- dspy/clients/lm.py
- dspy/dsp/utils/settings.py
This PR is to add setting to disable writing history when running in production.
Related discussion:
- https://github.com/stanfordnlp/dspy/issues/7262
> feat: allow to disable dspy write to history when running in prod

- dspy/dsp/cache_utils.py
Even if DSP_CACHEBOOL is set to false, the Memory context will still be initialized. 
This is not desirable in cases where the file system is not available or is read only. 
This code is run when the dspy package is imported, whether or not the caching is used. So, it's important to be able to completely opt out of filesystem access.
> Do not initialize the cache if DSP_CACHEBOOL is false

- dspy/predict/react.py
- tests/predict/test_react.py
When using functions without type hints as tools in ReAct, the code would throw an error when trying to access `arg_types[k]` since `arg_types` would be empty. This made it impossible to use simple functions without type annotations as tools, even for basic operations.
Modified the tool argument parsing logic to:
1. First check if the tool has `arg_types` attribute
2. Then check if the specific argument key exists in `arg_types`
3. Only attempt type validation for arguments that have explicit type hints
4. Pass through arguments without type hints as-is
Added a test case `test_tool_calling_without_typehint` that demonstrates:
- A simple function `foo(a, b)` without type hints can be used as a tool
- Arguments are correctly passed through without type validation
- The tool executes …
> Fix react bug in 2.6.0 that cause tools without type hint to fail

- dspy/dsp/cache_utils.py
This brings the various caching functionality of dspy into one parent dir (by default) and avoids the creation of a non-hidden cachedir_joblib directory in the user's home folder.
Implements #7628.
This is the most minimal change to address the above issue. 
I do believe that there might be a benefit in trying to clean up the organization of the cache directories in a more general sense. Just from doing a closer investigation, it seems that there are three areas within this library where some kind of disk caching occurs:
1. Joblib caching, which seems to be only used in the DSP submodule (after this change it will default to `.dspy_cache/cachedir_joblib`)
2. Finetuning, where by default a `.dspy_cache/finetune` directory is created
3. litellm cacheing, which is also added to `.dspy_cache` …
> Nest default joblib cache dir into .dspy_cache

- dspy/clients/lm.py
- tests/clients/test_lm.py
The OpenAI o3 model family deprecated `max_tokens` in favor of `max_completion_tokens`. Additionally, both o1 and o3 models (including their mini variants) are part of the same "reasoning model" family that require specific configuration (temperature=1.0, tokens >= 5000). This change is does this behind the scenes so that it wouldn't introduce any backward compatibility issues.
1. Updated model family detection to use regex pattern matching for all variations:
- Base models: `o1`, `o3`
- Mini variants: `o1-mini`, `o3-mini`
- Any other variants starting with o1/o3
2. Unified parameter handling for reasoning models:
- Use `max_completion_tokens` instead of `max_tokens` for all reasoning models
- Simplified error message to refer to "reasoning models" as a family
3. Added comprehensive …
> feat(lm): add support for o3-mini and openai reasoning models

- .github/workflows/run_tests.yml
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/reliability/test_generated.py
- tests/reliability/test_pydantic_models.py
Adds options into pydantic config to auto-skip reliability tests.
They can still be run with:
`pytest tests/ --reliability`
> feat: Add pytest option to skip reliability tests by default

- dspy/predict/__init__.py
- dspy/predict/react.py
- dspy/primitives/__init__.py
- dspy/primitives/tool.py
- tests/callback/test_callback.py
- tests/primitives/test_tool.py
Some changes to `dspy.Tool`:
1. Move it under `primitives` to separate it from `dspy.ReAct` definition.
2. Resolve relative model json schema with absolute schema, i.e., expanding all those `$ref`s. 
3. Provide a way for users to specify parameter description, which is proved to be useful for improving function calling quality.
> Improve `dspy.Tool`

- requirements.txt
This PR is to update litellm to make it works with uvicorn 0.29.
cc @CyrusNuevoDia since you did sth for the pyproject.yml previously
> fix: resolve litellm dependencies

- dspy/adapters/json_adapter.py
Pull request to implement solution to #1968 . in json_adapter.py , the parse_value function uses json_repair.loads() to load the structured output, so if theres slight errors or formatting issues, json_repair tries to fix it.
> Replacing json.loads with json_repair.loads

- dspy/clients/lm.py
- dspy/utils/__init__.py
- dspy/utils/asyncify.py
- dspy/utils/streaming.py
- tests/utils/test_streaming.py
One interesting and useful feature is status streaming, e.g., we tell users that "we are running the tool XXX", "we finished running the tool XXX" so that users don't wait endlessly until the final output. With callback system, the implementation is relatively straightforward. 
Below is a testing code:
``` 
import asyncio
from typing import Any
from pydantic import BaseModel
import dspy
from dspy.utils.streaming import StatusMessage, StatusMessageProvider
lm = dspy.LM("openai/gpt-4o-mini")
dspy.settings.configure(lm=lm)
class CalendarEvent(BaseModel):
name: str
date: str
participants: list[str]
def write_invitation_letter(participant_name: str, event_info: CalendarEvent):
if participant_name not in event_info.participants:
return None
return f"It's my honor to invite {participant_name} to …
```
> Support status streaming

- docs/docs/production/index.md
- docs/docs/stylesheets/extra.css
- docs/docs/tutorials/observability/index.md
- docs/mkdocs.yml
As discussed offline, adding a new page describes the production related topics about DSPy.
> Add 'DSPy in Production' page

- docs/docs/tutorials/agents/index.ipynb
- docs/docs/tutorials/classification_finetuning/index.ipynb
- docs/docs/tutorials/entity_extraction/index.ipynb
- docs/docs/tutorials/games/index.ipynb
- docs/docs/tutorials/math/index.ipynb
- docs/docs/tutorials/multihop_search/index.ipynb
- docs/docs/tutorials/rag/index.ipynb
Change tracing drop down title from "optional" to "recommended"
> Change drop down title

- dspy/adapters/base.py
- dspy/predict/react.py
- tests/predict/test_react.py
In the current implementation, we are accumulating the trajectory without an end, which in some cases cause context overflow, e.g., the tool is a retriever which fetches long context. With this PR we are providing a default way to truncate trajectory when detecting context window exceeding, and also provide a custom hook `truncate_trajectory` so that users can override to implement their own truncation logic.
> Add context truncation logic for react

- dspy/utils/streaming.py
It's uncommon but possible that "streamify" is called in a child thread, especially at model serving, e.g., MLflow serving. So in order to avoid errors we are using `dspy.context` instead of changing the global `dspy.settings`.
> Use context instead of settings for streamify

- dspy/signatures/__init__.py
- dspy/signatures/signature.py
- tests/signatures/test_signature.py
We are doing a rework of `dspy.Signature`. This is 98% internal code quality improvement, and our users don't need to be aware of this change at all. 
- We are now abusing the metaclass, which should be kept as small as possible to easy maintenance: https://google.github.io/styleguide/pyguide.html#2194-decision. At this point we cannot get rid of metaclass (and we don't need to), but we should make it as simple as possible. With this PR I am moving methods to `class Signature` with `@classmethod` decorator, which does the same job as before.
-  Remove the `replace` method and `update_signature` utility function. The history of these 2 methods can be found here: https://github.com/stanfordnlp/dspy/pull/1090. But reading the context it's unclear how this in-place swapping helps with i18n. …
> Signature rework

- docs/docs/deep-dive/retrieval_models_clients/WeaviateRM.md
- dspy/retrieve/weaviate_rm.py
The changes introduce multitenancy support to the WeaviateRM class. A new optional parameter tenant_id is added to the constructor, allowing the user to specify a tenant ID. This tenant ID can also be provided as a keyword argument during query execution. When a tenant ID is specified, all retrieval requests are scoped to the given tenant ID, ensuring tenant-specific data access within a multitenant Weaviate instance.
> Weaviate multitenancy support

- .pre-commit-config.yaml
Resolves a deprecation warning:
```
[WARNING] top-level `default_stages` uses deprecated stage names (commit) which will be removed in a future version.  run: `pre-commit migrate-config` to automatically fix this.
```
> Apply migrate-config to pre-commit config

- dspy/teleprompt/__init__.py
It's not exposed because it doesn't exist in __all__ before this PR.
> Expose InferRules optimizer

- dspy/adapters/chat_adapter.py
A few minor fixes in order to be able to turn on style check in the future:
- no overflowing line (max 120 chars)
- sort imports
- don't assign lambda to variables
- no trailing `_` for variable name
> Fix style issues for chat adapter

- dspy/teleprompt/bootstrap.py
- dspy/teleprompt/bootstrap_finetune.py
- dspy/teleprompt/mipro_optimizer_v2.py
Many lint fixes for optimizers in order to enable style check (probably in 3 weeks):
- line width should be less than 120
- docstring should follow google style 
- inline the code if possible
- other random stuff, like raise error instead of using assert. 
Mostly automated by ruff.
> Style fix for optimizers

- docs/docs/api/adapters/ChatAdapter.md
- docs/docs/api/primitives/Image.md
- docs/docs/api/primitives/Prediction.md
- docs/docs/api/signatures/Signature.md
- docs/scripts/generate_api_docs.py
This pull request adds support for class methods in the api documentation by replacing calls to `inspect.isfunction()` with the more inclusive `inspect.isroutine()`. In particular, the `Image`, `Prediction` and `Signature` primitives have several relevant functions that were not being captured by the previous method. 
It also excludes functions defined by external modules (e.g. Pydantic), but it seems there is some other mechanism that also filters them out somewhere, since they do not appear in the existing documentation despite being present in the generated markdown.
> docs: Add support for class methods in API reference

- docs/docs/learn/programming/signatures.md
This pull request adds an example of multi-modal image input to the signature documentation. It is based on the functionality introduced in https://github.com/stanfordnlp/dspy/pull/1495 
Ideally, it would also be accompanied by the changes introduced in https://github.com/stanfordnlp/dspy/pull/7841, since the existing documentation does not make any references to the functions used in the example.
> docs: Add multi modal classifier example to documentation

- poetry.lock
- pyproject.toml
**Issues**
* #7835 
---
This pull request includes changes to the `pyproject.toml` file to improve compatibility and functionality across different platforms. The most important changes include modifying the `litellm` dependency to handle different platforms.
Dependency updates:
* Modified the `litellm` dependency to specify different versions and extras based on the platform, ensuring compatibility with both Windows and other systems. (`pyproject.toml`, [[1]](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L140-R143) [[2]](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L159-R165)
> Fix RuntimeError: uvloop Incompatibility on Windows 

- pyproject.toml
fix for #7853  and #7490 
ensures all github files are in the dspy installation package so `runner.js` can be recognized. 
Tagging @chenmoneygithub for review on the proper pypi package installation.
> bundle files with dspy installation

- pyproject.toml
This PR fixes #7853 and #7490 without causing #7867.
Confirmed the behavior by running `python -m build` on a clean clone of the DSPy repo.
> Fix pyproject.toml to include package data

- dspy/__init__.py
- dspy/adapters/__init__.py
- dspy/adapters/base.py
- dspy/adapters/chat_adapter.py
- dspy/adapters/json_adapter.py
- dspy/adapters/types/__init__.py
- dspy/adapters/types/history.py
- dspy/predict/predict.py
- dspy/signatures/signature.py
- tests/predict/test_predict.py
We are letting users pass in the convesation history in DSPy program with this PR. From the LLM's viewpoint, conversation history is appended after the few-shot examples, please see code demo and example LLM history below.
Please note that DSPy doesn't help capture the conversation history, but you can easily capture it with custom code (as reflected in the code demo). Will write a tutorial in a followup PR. 
```
import logging
import dspy
dspy.settings.configure(lm=dspy.LM("openai/gpt-4o-mini"))
class MySignature(dspy.Signature):
question: str = dspy.InputField(description="The question to answer")
answer: str = dspy.OutputField(description="The answer to the question")
history: dspy.History = dspy.InputField(description="The conversation history")
cot = dspy.ChainOfThought(MySignature) …
```
> Support multiturn history

- dspy/predict/predict.py
In #7851 we allowed history to be missing to avoid warnings during `compile()` call, but in fact we shouldn't do that
> Remove special case for dspy.Predict

- dspy/__metadata__.py
I accidentally removed the automatic version updating in the publish workflow, so I am manually updating it now.
After https://github.com/stanfordnlp/dspy/pull/7876, the workflow will handle version update in `__metadata__.py` again.
> fix version in metadata

- dspy/signatures/signature.py
- tests/predict/test_parallel.py
- tests/signatures/test_signature.py
Fix the issue mentioned here #7759 
When creating a Signature subclass, fields without type annotations would be reordered in the resulting class, causing the field order to differ from the order specified in the class definition. I added a test to check for this as well.
> Fix signature field order mismatch

- docs/docs/index.md
- dspy/clients/databricks.py
- dspy/clients/lm_local.py
- dspy/clients/openai.py
- dspy/clients/provider.py
- dspy/teleprompt/bootstrap_finetune.py
While `provider/model` format is used for most methods, this format does not work for fine-tuning user journey, which is confusing. This PR fixes the model name handling and fixes the tutorial for fine-tuning on the top page. Also fixes type/reference errors in the relevant provider codes.
> Fix model name error in finetune

- docs/docs/cheatsheet.md
- dspy/predict/knn.py
- dspy/teleprompt/knn_fewshot.py
- tests/predict/test_knn.py
- tests/teleprompt/test_knn_fewshot.py
Fixes and removes the now non-existent dependency on `dsp.SentenceTransformersVectorizer` from `KNN` and indirectly from `KNNFewShot`.
Also:
* Re-enables and fixes all relevant tests
* Removes `trainset` and `valset` params from the `KNNFewShot.compile` call as they were unused.
* Updates documentation to reflect new usage.
> Fixes and removes non-existent dependency on dsp.SentenceTransformersVectorizer from KNN and KNNFewShot 

- dspy/adapters/types/image.py
- tests/signatures/test_adapter_image.py
Added support for non-image mimes in image_url content.
As offputting as this sounds this is how some models -- eg Gemini[1] & Anthropic[2] -- work for giving non-image files to the LM.
[1] https://docs.litellm.ai/docs/providers/gemini#usage---pdf--videos--etc-files
[2] https://docs.litellm.ai/docs/providers/anthropic#usage---pdf
> feat: Added support for non-image mimes in image_url content

- dspy/predict/predict.py
> Change the LM check to BaseLM

- .github/workflows/build_and_release.yml
- dspy/utils/saving.py
- tests/metadata/test_metadata.py
We've been messing up releases between 2.6.6 and 2.6.9, which could've been prevented with a decent test before publishing to pypi. This PR adds the following check before publishing to pypi:
- Check the metadata is valid after the release.
- All tests in tests/predict should pass, which has a decent coverage over primitives, predict, adapters and LM.
See screenshot below for an example run (testpypi only) from my fork:
> Run test before publishing to pypi

- dspy/utils/parallelizer.py
- Added new parameters `timeout_seconds` (default 120) and `straggler_limit` (default 3) to control when slow tasks are re-executed.
- Modified multi-thread execution to record the actual start time of tasks inside the worker thread, ensuring accurate timeout detection even when tasks are queued.
- Updated the executor loop to poll for completed futures and, if only a few tasks remain and any exceed the timeout, resubmit them exactly once.
- Ensured that once a task’s result is returned (from either the original or resubmitted copy), it is recorded and the overall execution terminates immediately without waiting for the slow original.
- Maintained all existing behaviors including thread-local overrides, error handling, progress bar updates, and signal (SIGINT) interruption handling.
> Add timeout-based straggler resubmission in ParallelExecutor

- poetry.lock
- pyproject.toml
- requirements.txt
As part of making the DSPy package lighter, we can remove jinja2 from the dependency list.
```
$ git grep jinja2 dspy
-> no result
```
> Remove jinja2 from dependency list

- dspy/clients/base_lm.py
- dspy/clients/lm.py
- dspy/teleprompt/bootstrap_finetune.py
We are in an effort of simplifying `dspy.LM` for two goals:
- Make `dspy.BaseLM` more extensible, since we are seeing more request for that.
- Avoid mess when we implement the async call, which will increase our maintenance cost a lot.
This PR includes the following:
- Move `copy` method to `BaseLM`
- Delete the `infer_adapter`, which just defaults to ChatAdapter. 
- Minor cleanups, like the history entry creation.
> Simplify dspy.LM

- dspy/adapters/chat_adapter.py
The current parser fails to extract field content when it appears on the same line as the field header. This occurs with model outputs in the format:
`[[ ## field ## ]] content here`
The parser only works when the content starts on a new line after the header:
```
[[ ## field ## ]]
content here
```
I ran the following code:
```python
import dspy
lm = dspy.LM("openai/llava-hf/llava-onevision-qwen2-7b-ov-hf",
api_base="http://localhost:8000/v1",
api_key="local", model_type='chat')
dspy.configure(lm=lm)
class CaptioningSignature(dspy.Signature):
"""Generate a caption for an image."""
image: dspy.Image = dspy.InputField()
question: str = dspy.InputField()
description: str = dspy.OutputField()
class Captioning(dspy.Module):
def __init__(self) -> None:
self.predictor = …
```
> fix: allow field headers and content on same line in parser

- docs/docs/deep-dive/optimizers/miprov2.md
Code sample should read `gsm8k`, not `gms8k`.
> Docs: Fix typo in page on MIPROv2

- dspy/adapters/json_adapter.py
Add support for images in JSON mode, fix typos, and fix logging format for exception message
> add image support in JSON mode

- dspy/primitives/prediction.py
- Fix bug in `Completions.__getattr__` which would prevent pickling-unpickling as attempting to access `_completions` on an unitialized instance will lead to an infinite recursion error.
- This matters when attempting to serialize traces
```python
import pickle
from dspy.primitives.prediction import Completions
c = Completions([])
data = pickle.dumps(c)
pickle.loads(data)
```
In `main`, this will error with:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/path/dspy/dspy/primitives/prediction.py", line 71, in __getattr__
if name in self._completions:
File "/path/dspy/dspy/primitives/prediction.py", line 71, in __getattr__
if name in self._completions:
File "/path/dspy/dspy/primitives/prediction.py", line 71, in __getattr__
if name in self._completions: …
```
> Fix completion being unable to be deserialized by pickle

- dspy/adapters/chat_adapter.py
- dspy/adapters/json_adapter.py
Automatic ruff formatting, no logic change. 
We will enable strict style check by 04/10/2025
> Formatting ChatAdapter and JsonAdapter

- dspy/clients/__init__.py
- dspy/dsp/cache_utils.py
- tests/predict/test_predict.py
Right now if cache initialization fails, the whole package import crashes. This is ideal because users may work on a VM where they don't have write permission, such as AWS lambda. With this PR, we just disable the cache on initialization failure, and log a warning to prompt the user that cache will not be used.
> Don't crash dspy import when cache initialization fails

- dspy/predict/refine.py
The format doesn't work well with mkdocs:
Before fix:
After fix:
Also it has a logical bug on `return 1.0 if len(pred.answer) == 1 else 0.0`, which should be `return 1.0 if len(pred.answer.split()) == 1 else 0.0` to check for number of tokens instead of characters.
> Fix example in refine

- dspy/adapters/types/history.py
- dspy/predict/best_of_n.py
- dspy/predict/knn.py
- dspy/teleprompt/knn_fewshot.py
mkdocs require example section to be in the format of:
```
Examples:
```
{code}
```
```
Basically:
1. No empty line between the header and code.
2. Must indent.
We are making adjustments to code examples for correct rendering. For example:
Before:
After:
> Fix example rendering for multiple files

- dspy/primitives/python_interpreter.py
- tests/primitives/test_python_interpreter.py
Support context protocol in `PythonInterpreter` to enable usage such as:
```python
with dspy.PythonInterpreter() as interp:
result = interp(r"print('Hello, world!')")
```
This will automatically release the `deno` process and is better suited for one-shot executions. 
Tests are also refactored and passed.
> feat: support context protocol in `PythonInterpreter`

- dspy/primitives/python_interpreter.py
- dspy/primitives/runner.js
- tests/primitives/test_python_interpreter.py
- The code introduces a bridge function to forward exception arguments directly to the dspy side manager.
- Implement a `smolagents`-inspired `FinalAnswer` exception, allowing user code to call `final_answer()` for a clean, non-local exit. The manager captures this to produce a structured final output rather than relying on stdout, particularly beneficial for complex generated code. Add corresponding unit tests to cover new functionality.
- Minor enhancements included (see code for details).
> feat: refine PythonInterperter to proper take out the exception arguments

- dspy/evaluate/evaluate.py
- tests/evaluate/test_evaluate.py
We want to make `result_df` of the evaluate call available outside of the `Evaluate.__call__` method. In this PR, we refactored the logic flow and introduced `construct_result_table` method that will be patched by tracing tools.
> Refactor evaluate and introduce construct_result_table method

- dspy/teleprompt/teleprompt.py
- tests/teleprompt/test_teleprompt.py
Fix the bug in `get-params` method and change the test to capture the issue.
> Fix a bug in Teleprompter.get_params

- dspy/predict/program_of_thought.py
- dspy/primitives/python_interpreter.py
- tests/predict/test_program_of_thought.py
The original `ProgramOfThought` module was excellent but limited to a single output field. This PR refines the module to support multiple return values while incorporating improvements from PR #7992.
Changes include:
- Update the model to return a JSON object, enabling multiple output values.
- Utilize the `final_answer` function and eliminate the misuse of early `return` statements in #7992.
- General code clean-ups and refactoring.
Backward compatibility:
- The original one-line PoT answer style remains supported.
Tests:
- Added tests to cover these changes.
- Verified functionality with local models (qwen2.5-14b and deepseek-r1-14b).
> feat: `ProgramOfThought` supports multiple output fields and more

- dspy/teleprompt/simba.py
- dspy/teleprompt/utils.py
This PR does the following:
1. Allows SIMBA to run 0-shot - previously this was through a divide by 0 error.
2. Fixes a `maximum recursion depth exceeded` error resulting from saving an optimized SIMBA program with `save_program=True`. This was done by making sure that `winning_programs` and `candidate_programs` are deepcopy(s) of the original programs.
3. Adds in basic `trial_logs` to the optimized program, to allow for post hoc analysis of cost vs. performance
These changes were tested by running a 0-shot optimization run, saving the resulting program with `save_program=True`, and verifying that the returned `trial_logs` were as expected.
> SIMBA Improvements: Bug fixes + Adding Trial Logs

- poetry.lock
- pyproject.toml
We are specifying numpy to be <2.2 when python 3.9 is used to avoid breakage.
> Fix the numpy dependency for python 3.9

- docs/docs/learn/optimization/optimizers.md
Changes:
- Fixed localhost link in RAG example.
- Corrected link to NNFewShot example to actuall path ot outdated notebook.
- Added link to tutorial for Optimizing weights for Classification.
> Fixing links and /learn/optimization/optimizers/ documentation

- docs/docs/learn/programming/modules.md
- dspy/__init__.py
- dspy/clients/__init__.py
- dspy/clients/lm.py
- dspy/dsp/utils/settings.py
- dspy/predict/parallel.py
- dspy/primitives/prediction.py
- dspy/primitives/program.py
- dspy/utils/parallelizer.py
- dspy/utils/usage_tracker.py
- tests/primitives/test_module.py
- tests/utils/test_usage_tracker.py
Per community request, we are adding usage tracking for DSPy program. As an overview:
- We track the LM usage in the openai (litellm) format for each program call
- Local cache hit will cause no usage
- If multiple LMs are used in the process, they will be tracked separately. 
- The returned usage is a dictionary from lm name to openai-format usage data. The usage data is the merge result across all LM calls in one single program pass.
To use usage tracking, follow the code example below:
```
import dspy
dspy.settings.configure(lm=dspy.LM("openai/gpt-4o-mini", cache=False), track_usage=True)
predict = dspy.ChainOfThought("question -> answer")
output = predict(question="What is the capital of France?")
print(output.get_lm_usage())
```
This usage tracking also works for multi-module …
> Add usage tracking

- dspy/teleprompt/mipro_optimizer_v2.py
This PR includes the following changes:
1. **New defaults for running MIPROv2**. The specific changes included here are: `minibatch_size` 25 -> 35, `minibatch_full_eval_steps` 10 -> 5, `auto` default from `None` to `medium`, `max_labeled_demos` 14 -> 4. These are defaults that we've found to work better out of the box from experimentation overtime.
2.  **Fixing trial # logging.** There were previously a few off by one, etc. errors in tracking the current trial # and the total trial #s. This came from a past change in which we reported the scores from full evals as a trial, in addition to the mini batch trials. This should now be fixed, and was tested in a number of different settings (`auto=light, medium`, `minibatch=True, False`, etc.)
> MIPROv2 Updates: New defaults, fixed Trial # Logging

- dspy/clients/lm.py
- tests/clients/test_lm.py
Some users reported that their programs were stuck due to Rate limit errors. This PR configures exponential backoff retry for LiteLLM completion call since LiteLLM uses constant backoff even for rate limits ([ref](https://github.com/BerriAI/litellm/blob/3ca34a181cae83b8b3c73e5937f07e36509a7f35/litellm/main.py#L3172)), which is ineffective.
One tradeoff here is that we will start using exponential backoff for other types of exceptions (e.g. internal server error) after this change. LiteLLM has a smart logic for async completion that it switches to exponential backoff only for RateLimitError ([ref](https://github.com/BerriAI/litellm/blob/17ad8a04175402b71bbb3f67c9d8e5ff248c5228/litellm/utils.py#L1415)), but this does not exist for sync completion. Therefore, another solution is that we file …
> Use exponential_backoff_retry for completion call

- dspy/predict/predict.py
There is a wrong comment in predict.py, we are fixing it with this PR.
Also replace `print` by `logging` for consistency across DSPy modules, and I made a mistake of using f-string for logging earlier, which is supposed to use formatted string: https://google.github.io/styleguide/pyguide.html#3101-logging
> Fix wrong comments in predict.py

- dspy/adapters/base.py
- dspy/adapters/chat_adapter.py
- dspy/adapters/json_adapter.py
- dspy/adapters/utils.py
- dspy/predict/predict.py
- dspy/predict/react.py
- dspy/predict/refine.py
- dspy/teleprompt/simba_utils.py
- dspy/utils/callback.py
- dspy/utils/dummies.py
We are reworking DSPy adapters for extensibility. For most users this change shouldn't cause backward compatibility issues, but if your workflow explicitly calls child methods of DSPy adapters, you need to make adjustments. 
The goal here is with DSPy 3.0, we want Adapter to be a customizable interface rather than some tribal knowledge. We acknowledge that it will be common for users willing to write their own adapter to adjust to their LLMs and workflows. However, the current adapter doesn't have a decent abstraction, and to write a custom adapter users need to understand the source code, and go through a tedious debugging process without guidelines.
In this PR, we are trying to standardize the dspy Adapters, and open a few hooks for people to override during customization. We are aware …
> Refactor DSPy adapters to make it more extensible

- dspy/adapters/base.py
- dspy/adapters/chat_adapter.py
- dspy/adapters/json_adapter.py
- tests/adapters/test_json_adapter.py
Co-authored with @hmoazam . Fixes some regressions from (and other regressions exposed by) #7996.
Subsumes of #8024. We learned that open-ended `dict`s and `Any`s (either, not just both together) are not supported by structured outputs in OpenAI and seemingly a few other providers, if not everyone. This PR handles that too.
> Fix JSON Adapter's first attempt, all Adapters for ReAct trajectories

- dspy/propose/grounded_proposer.py
- tests/propose/test_grounded_proposer.py
Since https://github.com/stanfordnlp/dspy/pull/1964/files#diff-f3e5aef968c9221a83083549f056a0f64f66dbaba64d22a3e7758615b1d20eadL318, GroundedProposer has a bug that it cannot handle empty demos correctly.
Resolve #8048
> Handle empty demo case correctly in GroundedProposer

- docs/docs/learn/optimization/optimizers.md
fixes #8036, small docs fix:
getting a 404 on the optimizer deep-dive links
https://github.com/stanfordnlp/dspy/blob/281e1f3be73f3529ef888196923295d86d79a392/docs/docs/learn/optimization/optimizers.md?plain=1#L88
docs link [here](https://dspy.ai/learn/optimization/optimizers/) - see "`how to use an optimizer`"
> Detailed documentation for key optimizers can be found [here](https://dspy.ai/deep-dive/optimizers/vfrs),
direct link 404's and points to:
https://dspy.ai/deep-dive/optimizers/vfrs
NA
> fix: broken full optimizers hyperlink in docs

- dspy/dsp/utils/settings.py
- dspy/evaluate/evaluate.py
- dspy/predict/parallel.py
- dspy/primitives/program.py
- dspy/teleprompt/avatar_optimizer.py
- dspy/teleprompt/bootstrap_finetune.py
- dspy/teleprompt/infer_rules.py
- dspy/teleprompt/mipro_optimizer_v2.py
- dspy/teleprompt/random_search.py
- dspy/teleprompt/simba.py
- dspy/teleprompt/teleprompt_optuna.py
- dspy/utils/parallelizer.py
- tests/evaluate/test_evaluate.py
Currently, many classes have their own thread count settings. It makes it difficult to configure the thread count for all components. This PR introduces a new setting, num_threads, to configure the thread count globally.
> Move num_threads into global settings

- dspy/evaluate/evaluate.py
In the evaluation function, a dataframe `result_df` is constructed using the results. 
However, this dataframe is **_only needed_** when the user wants to display the table as output. 
Otherwise, this construction is computed without any further use. 
In this PR, I moved the `metric_name` and `result_df` computations to the `if` clause.
> Performance improvement of evaluate.py

- dspy/predict/react.py
- dspy/primitives/tool.py
- tests/predict/test_react.py
- tests/primitives/test_tool.py
Before this PR default arg information is lost when we convert functions to `dspy.Tool`. with this PR we are resolving the issue.
> Support default args in dspy.Tool

- dspy/primitives/tool.py
- tests/primitives/test_tool.py
resolve #8086 
The standard is mapping `Any` to empty json schema, no need to use a special string identifier `"Any"` to represent the situation where no type hint is provided.
> Fix default arg when type hints are not available

- dspy/adapters/json_adapter.py
Currently, there is this deprecation warning message:
```
/opt/venv/lib/python3.12/site-packages/dspy/adapters/json_adapter.py:198: PydanticDeprecatedSince20: The `schema` method is deprecated; use `model_json_schema` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/
schema = Model.schema()
```
Updated the file with the warning
> Fix Pydantic Deprecation warning

- dspy/adapters/base.py
- dspy/adapters/two_step_adapter.py
- dspy/clients/base_lm.py
- dspy/clients/embedding.py
- dspy/clients/lm.py
- dspy/predict/best_of_n.py
- dspy/predict/chain_of_thought.py
- dspy/predict/predict.py
- dspy/primitives/program.py
- dspy/utils/dummies.py
- tests/adapters/test_chat_adapter.py
- tests/adapters/test_json_adapter.py
- tests/adapters/test_two_step_adapter.py
- tests/clients/test_embedding.py
- tests/clients/test_lm.py
- tests/predict/test_chain_of_thought.py
- tests/predict/test_predict.py
We are working on supporting async in DSPy (true async, i.e., `async def` instead of `asyncio.to_thread`), and in this PR we are supporting async in the critical paths including:
- `dspy.LM`
- `dspy.Embedder`
- `dspy.Adapter`
- `dspy.Module`
- `dspy.Predict` and `dspy.ChainOfThought`
We will roll over the support to more APIs/Classes gradually.
> Support async in DSPy critical paths

- dspy/clients/lm.py
Currently, `LM.__call__` calls callback handlers twice since we apply with_callbacks to both `BaseLM.__call__ ` and `LM.forward`, which is confusing. This PR removes the decorator from `LM.forward`.
> Remove unnecessary LM callback

- dspy/predict/react.py
- tests/predict/test_react.py
Allow passing `max_iters` in the forward method to overwrite the default.
> Allow overwrite max_iter in ReAct

- dspy/predict/react.py
- dspy/primitives/tool.py
- tests/primitives/test_tool.py
Currently our arg parsing cannot handle composite type like `list[MyPydanticModel]`, so we make this PR to resolve the issue. 
The solution is creating a pydantic wrapper with one single dummy field `value` of the arg type, and utilize pydantic `model_validate()` to convert the LLM-generated args (json format) into the right type.
> Support composite arg type parsing in `dspy.Tool`

- dspy/primitives/tool.py
- tests/primitives/test_tool.py
Allow using callables that accept arbitrary keyword args.
```python
def a(**kwargs):
"""arguments are c:int and d:int"""
return kwargs.get("c", 1) * kwargs.get("d", 1)
tool = dspy.Tool(a)
tool(c=5, d=4)
```
> Support kwargs in dspy Tool

- tests/predict/test_predict.py
This test case is no longer needed because now at import time we set litellm cache to None.  We wrote this test case earlier to avoid causing the whole package to crash when litellm cache initialization fails.
> Delete unused test

- dspy/clients/base_lm.py
Fix for https://github.com/stanfordnlp/dspy/issues/8101
logprobs = True should return the log probabilities of the output tokens but they are missing.
This has been implemented in #1895 and looks like it worked in the past.
There is also a more recent feature request for it: #7967
> Fix: Make sure Base LM builds on self.kwargs

- dspy/clients/base_lm.py
- dspy/predict/predict.py
- dspy/primitives/program.py
- dspy/utils/callback.py
- tests/callback/test_callback.py
Based on #8103, but instead of using the generator, we break down the code.
> Add async callback 

- pyproject.toml
Recently, https://github.com/stanfordnlp/dspy/issues/8075 was opened to note that limiting openai to version 1.61.0 was causing problems.
This was fixed for 2.6.18 in https://github.com/stanfordnlp/dspy/pull/8084 . However that change only changed one of two entries in `pyproject.toml` that defines the openai range, as there were parallel configurations of dependencies for poetry and uv.
Then, just before 2.6.19, this PR removed the poetry-oriented dependencies, including the openai change:
https://github.com/stanfordnlp/dspy/commit/0363c2e72b24c0c0d65ba0d8cdfdef86049591be#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L36-L106
Now, `pyproject.toml` is left with the other copy which still has the version limit of 1.61.0: …
> Restore relaxation of openai version range, lost after refactor

- dspy/predict/react.py
- tests/predict/test_react.py
We've accumulated a few reports, sometimes with Google models (Gemma, Gemini) but also with Qwen, that when the model wants to `finish`, it fails to format that properly. This results in an unnecessary exception, instead of ending execution gracefully.
This PR refines the base instructions for `dspy.ReAct` and handles mid-trajectory failures more gracefully. The final extraction step is still responsible for processing. This results in better respect for the ReAct contract.
> Handle ReAct tool selection failures more gracefully

- tests/utils/test_unbatchify.py
Adding tests for Unbatchify util. Seemed to be the only Util missing a test
> Add tests for Unbatchify util

- tests/utils/test_parallelizer.py
This PR adds additional test cases for the ParallelExecutor:
- Ensures worker threads maintain independence.
- Validates parallel execution speed.
- Tests error handling with max_errors.
All tests are passed locally.
Fixes: #8122
> Add unit tests for ParallelExecutor class in dspy.utils.parallelizer

- dspy/clients/cache.py
- tests/clients/test_cache.py
Instead of tying the args to ignore to the cache instance, we just use it at call time.
> Fix cache thread unsafety

- docs/mkdocs.yml
Earlier our search bar doesn't identify the API references, this PR fixes it. 
See screenshots for the effect:
> Make doc site search bar able to identify the API references

- dspy/primitives/tool.py
- dspy/utils/mcp.py
- tests/utils/resources/mcp_server.py
- tests/utils/test_mcp.py
Currently if an MCP tool's arg is of custom type, then the `tool.args` doesn't reflect the json schema correctly. For example:
```
from mcp.server.fastmcp import FastMCP
from pydantic import BaseModel
mcp = FastMCP("test")
class Profile(BaseModel):
name: str
age: int
class Account(BaseModel):
profile: Profile
account_id: str
@mcp.tool()
def get_account_name(account: Account):
"""This extracts the name from account"""
return account.profile.name
if __name__ == "__main__":
mcp.run()
```
will have the args be like `{'account': {'$ref': '#/$defs/Account'}}`, which doesn't have sufficient information for the LM to generate right args. This PR fixes it by explicitly resolving the refs.
> Support args of custom types in dspy mcp tool

- dspy/predict/predict.py
- tests/predict/test_predict.py
fix #8145 
It actually indicates a bigger problem that our `dspy.Predict`'s `__call__` is not using the `Module.__call__`. We override the `__call__` in `dspy.Predict` to disallow positional args, but it should still utilize the parent's `__call__`.
We also improve the error message on users passing positional args to `dspy.Predict`. 
Before:
```
TypeError: Predict.__call__() takes 1 positional argument but 2 were given
```
After:
```
ValueError: Positional arguments are not allowed when calling `dspy.Predict`, must use keyword arguments that match your signature input fields. For example: dspy.Predict('question -> answer')(question='What is the capital of France?')
```
> Fix predict usage tracking

- docs/docs/tutorials/build_ai_program/index.md
- docs/docs/tutorials/core_development/index.md
- docs/docs/tutorials/index.md
- docs/docs/tutorials/optimize_ai_program/index.md
- docs/mkdocs.yml
We have a decent number of tutorials now, and it makes sense to me to break them down into a few sections for easy navigation. I am making 3 categories now:
> Break down DSPy tutorials for clarity

- docs/docs/tutorials/index.md
Need to use 4-space indents to have the list render correctly.
> Fix the tutorial list

- docs/README.md
The DSPy Docs are no longer being pulled from the subtree at https://github.com/krypticmouse/dspy-docs.
This PR updates the docs README to the current pipeline for locally building and serving the DSPy docs.
> Updated dspy docs README to better reflect current process of contribution

- dspy/adapters/__init__.py
- dspy/adapters/base.py
- dspy/adapters/chat_adapter.py
- dspy/adapters/json_adapter.py
- dspy/adapters/two_step_adapter.py
- dspy/adapters/types/image.py
- dspy/adapters/utils.py
- pyproject.toml
We are standardizing the coding style rules in #7885. Before checking in #7885, we are running through our directories to fix all broken rules. Afterwards we can turn on strict style checking in github actions.
> Fix coding style in dspy/adapters

- dspy/adapters/chat_adapter.py
- dspy/clients/lm.py
- tests/clients/test_lm.py
`retry_policy` is no longer a useful arg in `litellm.completion`, and we should use `num_retries` instead. 
According to litellm's doc page: 
```
num_retries: int (optional) - The number of times to retry the API call if an APIError, TimeoutError or ServiceUnavailableError occurs
```
so it is sufficient for DSPy need.
> Fix litellm retries

- dspy/clients/__init__.py
- dspy/clients/base_lm.py
- dspy/clients/cache.py
- dspy/clients/lm_local.py
- dspy/clients/openai.py
- dspy/clients/provider.py
- dspy/clients/utils_finetune.py
- pyproject.toml
We are standardizing the coding style rules in https://github.com/stanfordnlp/dspy/pull/7885. Before checking in https://github.com/stanfordnlp/dspy/pull/7885, we are running through our directories to fix all broken rules. Afterwards we can turn on strict style checking in github actions.
This PR handles `dspy/clients`. `lm.py` is not touched in this PR to avoid merging conflict with other pending PRs.
> Standardize coding style in dspy/clients

- tests/retrievers/test_embeddings.py
Added three unit tests for the embeddings.
1) test_embeddings_basic_search: Verifies that the retriever returns the correct top k relevant passages and their indices for a single query.
2) test_embeddings_forward_batch: Ensures the retriever handles batch queries correctly, returning the top k relevant passages and indices for each query.
3) test_normalization: Confirms that the embeddings are correctly normalized to have a norm close to 1 after processing.
> Adding unit tests for dspy.retrievers.Embeddings

- dspy/teleprompt/mipro_optimizer_v2.py
1. Updating MIPROv2 to have the following behavior:
- Auto is on by default (DONE)
- All auto-dependent kwargs are None by default
- If Auto is ON, raise error if any kwarg is set
- If Auto is OFF, raise error if any kwarg is not set
2. Changes the `log` base 2 in the `num_trials` calculation, as was originally intended.
3. Adds a time out to the cost user message to proceed after 20 seconds if no input is received
> MIPROv2 Updates

- dspy/streaming/__init__.py
- dspy/streaming/streamify.py
- tests/streaming/test_streaming.py
Introduce a util function `dspy.streaming.apply_sync_streaming()` which converts the async stream generator to a sync generator, for ease of use in scenarios that the caller is sync function. The implementation spins up a child thread to consume the async generator and write to a queue to create the sync generator. 
Sample usage:
```
import dspy
from dspy.streaming import StatusMessage
from dspy.streaming.streamify import apply_sync_streaming
lm = dspy.LM("openai/gpt-4o-mini", cache=False)
dspy.settings.configure(lm=lm)
class MyModule(dspy.Module):
super().__init__()
self.predict1 = dspy.Predict("question->answer")
self.predict2 = dspy.Predict("answer->simplified_answer")
def forward(self, question: str, **kwargs):
answer = self.predict1(question=question) …
```
> Utility that converts async stream to sync stream

- dspy/primitives/__init__.py
- dspy/primitives/example.py
- dspy/primitives/module.py
- dspy/primitives/prediction.py
- dspy/primitives/python_interpreter.py
- dspy/primitives/tool.py
- pyproject.toml
> Fix coding style in dspy/primitives

- docs/docs/tutorials/streaming/index.md
- dspy/streaming/streamify.py
- tests/streaming/test_streaming.py
Introduce a bool flag `async_streaming` to `dspy.streamify` so that users can switch easily between sync and async streaming.
> Make it easier to do sync streaming

- docs/docs/tutorials/async/index.md
- docs/docs/tutorials/index.md
- docs/mkdocs.yml
Add a tutorial of using async in DSPy.
> Async tutorial

- dspy/clients/lm.py
Revert #8098. This extra callback is useful to interpret the actual LM prompt and response. The callback on `BaseLM.__call__` only captures the processed output.
> Add back `LM.forward()`'s callback

- docs/docs/tutorials/rl_multihop/index.ipynb
We fixed this in the papillon tutorial but not this one
> Remove Unnecessary Comma in `arbor.yaml`

- dspy/predict/react.py
Default args of Tool are supported since https://github.com/stanfordnlp/dspy/pull/8082
> Remove completed todo comment for default args of tool

- dspy/adapters/chat_adapter.py
- dspy/adapters/json_adapter.py
- dspy/utils/__init__.py
- dspy/utils/exceptions.py
- tests/adapters/test_json_adapter.py
- tests/utils/test_exceptions.py
We have been throwing wildcard exception in Adapter, but in certain cases we need to be able to access the raw LM response together with intermediate parse result. To make it happen, we are introducing `dspy.utils.exceptions.AdapterParseError`, which captures:
- Adapter information
- Signature
- Raw LM response
- Intermediate parsed result (could have partial output fields from the signature)
- Predefined error message
A sample error looks like:
```
E           dspy.utils.exceptions.AdapterParseError: Adapter JSONAdapter failed to parse the LM response. 
E           
E           LM Response: {'answer1': 'Paris'} 
E           
E           Expected to find output fields in the LM response: [answer] 
E           
E           Actual output fields parsed from the LM response: []
```
And users …
> Add AdapterParseError to dspy

- dspy/signatures/__init__.py
- dspy/signatures/field.py
- dspy/signatures/signature.py
Based on rule: https://github.com/stanfordnlp/dspy/pull/7885
> Fix style errors of dspy/signatures

- docs/docs/learn/programming/signatures.md
- dspy/signatures/signature.py
- tests/signatures/test_custom_types.py
- tests/signatures/test_signature.py
Added support for custom type resolution in Signatures. Allows users to reference their own types in string-based signature definitions.
Added custom_types parameter to make_signature. Uses caller's frame to detect custom types.
> feat(dspy): custom type resolution in Signatures

- dspy/adapters/types/audio.py
`dspy.Audio` has a conflicting attr field named `format`, which is causing the warning when importing dspy:
```
>>> import dspy
/Users/chen.qian/miniconda3/envs/dspy/lib/python3.12/site-packages/pydantic/_internal/_fields.py:192: UserWarning: Field name "format" in "Audio" shadows an attribute in parent "BaseType"
```
> Fix audio attr name

- dspy/datasets/dataloader.py
- ensure input keys are expanded when loading parquet data
- `pre-commit run --files dspy/datasets/dataloader.py` *(fails: command not found)*
> Fix DataLoader input key bug

- dspy/clients/lm.py
- dspy/predict/predict.py
- tests/predict/test_predict.py
Support the predicted output feature: https://platform.openai.com/docs/guides/predicted-outputs. The implementation is based on litellm's predicted output: https://github.com/chenmoneygithub/dspy
To avoid the edge case that user input field has `prediction`, I am adding a check on the format of `prediction`, and only when it's a valid predicted output format, I am piping it to the LM call kwargs.
> Support predicted output in DSPy

- dspy/clients/provider.py
- correctly assign the LM instance in `ReinforceJob.__init__`
- `ruff check dspy/clients/provider.py`
- `pytest -q` *(fails: command not found)*
> Fix ReinforceJob LM reference

- tests/adapters/test_chat_adapter.py
Fixes for https://github.com/stanfordnlp/dspy/issues/8120
Adds 3 new tests to ChatAdapter: 
* **test_chat_adapter_with_pydantic_models()**: Validates and ensures that ChatAdapter can use Pydantic models as inputs and outputs, nested or basic
* **test_chat_adapter_signature_information()**: Ensures that the signature information sent with ChatAdapter follows an expected structure and format
* **test_chat_adapter_exception_raised_on_failure()** : Ensures that a specific error is called upon failure
All tests were passed. If there are any changes you'd like me to make, please let me know! More than happy to contribute.
> Increased test coverage for ChatAdapter

- docs/docs/learn/programming/language_models.md
Added more clarity on how to initialize Azure OpenAI models. I also added tips on how to debug initializing external models. With these new changes, users can more easily get started and implement Azure Open AI models. 
Here are some clarifications I added:
- I clearly added that the parameters names need to be saved as environment variables. If the user prefers to directly pass the parameters in the code, then I added an updated example. 
- I added that if users run into errors they should look at the LiteLLM documentation to confirm if the initialization protocol is correct.
> Updated instructions on how to use AzureOpenAI models.

- docs/docs/tutorials/saving/index.md
- tests/primitives/test_module.py
Follow up with #8286 , somehow I cannot push directly to the PR.
> Add unit test for saving extra modules

- docs/docs/tutorials/core_development/index.md
Tutorial link on tracking optimizers is missing on the right.
> Fix missing doc link

- .github/workflows/run_tests.yml
We used to only run test on 3.11, but we should run tests on all supported python versions, i.e., 3.10 - 3.13 inclusive.
> Enable CI testing for all supported python versions

- dspy/adapters/types/base_type.py
- tests/adapters/test_base_type.py
Following up with #8318, this PR handles extracting custom field type from annotations like `list[MyPydanticType]`.
The unit tests passed on both on python 3.10 and 3.12. The original error results from the diff between python 3.10 and python 3.12
On python 3.12:
```
>>> isinstance(list[str], type)
False
```
but on python 3.10:
```
>>> isinstance(list[str], type)
True
```
> Fix the custom type extraction in dspy.BaseType

- dspy/adapters/types/tool.py
Two minor fixes:
- Wrap the code by asyncio.run() so that users can copy the code and run.
- Renaming the variable from `tool` to `dspy_tool` to avoid conflicting with the imported langchain `tool`.
> Wrap langchain tool code example by asyncio runner

- dspy/utils/logging_utils.py
This PR modifies how DSPy configures its loggers to prevent conflicts with OpenTelemetry logging handlers and avoid long blocking operations during logger configuration.
The current implementation uses `logging.config.dictConfig()` which triggers a full handler cleanup through `_clearExistingHandlers()`. This causes issues when OpenTelemetry logging handlers are present in the environment because:
1. The cleanup process attempts to flush and shutdown all existing handlers
2. OpenTelemetry handlers' flush operation can block for a long time (30+ seconds)
3. This affects any application using both DSPy and OpenTelemetry for logging
Here's an example that demonstrates the issue run with `opentelemetry-instrument`:
```python
import logging
import logging.config
logger = …
```
> Fix logging configuration to prevent OpenTelemetry handler conflicts

- .github/workflows/run_tests.yml
- dspy/clients/cache.py
On ruff failures it will show:
To prompt users to run `pre-commit run --all-files`
> Prompt users to run pre-commit when detecting ruff failures

- dspy/predict/react.py
> Add docstring for dspy.ReAct

- dspy/adapters/chat_adapter.py
- tests/adapters/test_chat_adapter.py
- tests/adapters/test_json_adapter.py
Fix #8261 
We accidentally omitted the `[[ ## Complete ##]]` identifier when formatting the assistant message for few-shot examples and conversation history, which could lead to inconsistency between demo/history and the actual prompt. 
We fix it in this PR and add missing unit tests.
> Fix missing [[ ## completed ## ]] in history and fewshot example

- dspy/utils/usage_tracker.py
- tests/utils/test_usage_tracker.py
fix #8265 
In some providers (only Bedrock for now), the value of certain keys in the usage dict can be `None`, this PR handles this case.
> Fix usage tracking when None exists as value

- dspy/dsp/utils/settings.py
It's more annoying than useful to forbid dspy.configure in ipython env.
> Allow configure() call in ipython 

- docs/docs/api/optimizers/MIPROv2.md
missing gsm8k init at repo docs/docs/api/optimizers/MIPROv2.md
docs at https://dspy.ai/api/optimizers/MIPROv2/#optimizing-instructions-only-with-miprov2-0-shot
> [update docs] init gsm8k = GSM8K()

- dspy/predict/predict.py
- tests/predict/test_predict.py
To have more explicit prompt for users on different cases of invalid LM setup. 
Specifically, we prompt users to wrap the string by dspy.LM when they use string as the LM. This is a common case, ironically I still occasionally get trapped by this.
> Improve error message on invalid lm setup

- docs/docs/tutorials/observability/index.md
We are missing a few hooks, this PR adds them to the doc: https://dspy.ai/tutorials/observability/#building-a-custom-logging-solution
> Add missing hooks to the tutorial of observability

- docs/docs/learn/programming/modules.md
- docs/docs/tutorials/build_ai_program/index.md
- docs/docs/tutorials/custom_module/index.ipynb
- docs/docs/tutorials/index.md
- docs/mkdocs.yml
We've been using custom modules everywhere in the doc, but we don't have a dedicated doc to walk through users how to write a custom module. This lightweight tutorial covers this missing piece.
> Add a tutorial on customizing modules

- dspy/primitives/program.py
Some small changes:
- Double quotes instead of single quote. 
- Avoid double negation, `if not called_via_call` -> `if forward_called_directly`.
- Use the polite tone, "please ..."
> Small style fix on forward call warning 

- dspy/adapters/utils.py
- dspy/primitives/python_interpreter.py
- dspy/propose/dataset_summary_generator.py
- dspy/propose/grounded_proposer.py
- dspy/propose/utils.py
- dspy/teleprompt/avatar_optimizer.py
- dspy/teleprompt/grpo.py
- pyproject.toml
- tests/predict/test_code_act.py
Add flake8-quotes (Q) so that we don't manually fix quote preference.
> Add quote rule to the lint rules

- dspy/primitives/module.py
Remove postprocess_parameter_name call which is no-op now
> Remove unused postprocess of param name

- pyproject.toml
We have removed the retrieve/ directory, no need to exclude them from ruff rules.
> Clean up unnecessary ruff exclude

- docs/docs/tutorials/saving/index.md
Update the dspy version described in docs/docs/tutorials/saving/index.md to 3.0.0 since we won't have 2.7
> Update the version to 3.0.0 in model saving doc

- .github/workflows/docs-push.yml
It's quite annoying that every time I sync from the main repo, it displays a red cross mark because the doc-push fails because it is supposed to fail.
I don't know why it took me this long to fix this either 🤨
> Disable doc-push on forked repo

- dspy/clients/cache.py
- tests/clients/test_cache.py
Resolves #8393 
Cache key is computed only for incoming request, therefore any modifications made to request by external calls (eg to LiteLLM.completion) does not impact cache.
> compute cache key once

- docs/docs/index.md
We are prompting users to install `datasets` for DSPy basic workflows, which is a bit misleading:
`datasets` is only required for running the 3rd part, where we run optimizers on the loaded Huggingface datasets.
> Remove datasets installation from the Getting Started I

- docs/docs/index.md
Gemini has been irrelevant until the recent gemini-2.5 launch. I have been seeing lots of Gemini users now, so we should include it in the LM setup. 
To be fair, gemini-2.5 is pretty good, definitely not a marketing thing. 
change preview:
> Add gemini to LM provider

- .github/workflows/docs-push.yml
- docs/docs/index.md
llama 3.1 is an old model, we should ping users to a newer one for robust experience. Things move too fast in GenAI, cheers!
> change the default model to llama-4 for databricks provider

- dspy/dsp/utils/settings.py
- tests/utils/test_settings.py
Earlier we introduced a strict rule on `dspy.configure` in async task, which forces people to use `dspy.context` in the second call. This approach is safe but terrible because that ruins the developer experience. In this PR, we are relaxing the constraint so that configure is allowed to be called in the same task.
The unit test below should clarify things:
```
@pytest.mark.asyncio
async def test_dspy_configure_allowance_async():
def bar1():
with pytest.raises(RuntimeError) as e:
dspy.configure(lm=dspy.LM("openai/gpt-4o"))
assert "dspy.settings.configure(...) can only be called from the same async" in str(e.value)
async def foo1():
bar1()
await asyncio.sleep(0.1)
async def foo2():
with pytest.raises(RuntimeError) as e:
dspy.configure(lm=dspy.LM("openai/gpt-4o"))
assert …
```
> Relax configure allowance in async tasks

- dspy/clients/lm.py
Fixes token tracking when using streamified module when using AWS Bedrock as a provider.
closes #8416
> fix bedrock streaming token tracking

- dspy/adapters/json_adapter.py
- tests/adapters/test_json_adapter.py
resolve #8430 
We always capture the exception to turn it into a `RuntimeError`, but the wrapper provides less value than vagueness in reality. We are just letting the original exception to go through.
> Allow exception to pass through in JSONAdapter

- dspy/streaming/streamify.py
- dspy/streaming/streaming_listener.py
- tests/streaming/test_streaming.py
Add `allow_reuse` to stream listeners so that the same listener can be used multiple times. This feature is useful when streaming out the ReAct agent (or any programs that have a loop)
We turn it off by default because we don't want the stream chunk go to all listeners, which is not efficient. This downside is negligible with <5 listeners, but can be pretty bad if there are like 20 listeners configured in a complex system.
> Allow reusing the stream listener

- dspy/signatures/signature.py
This pull request fixes a bug where [PEP 604](https://peps.python.org/pep-0604/)-style union types in Class-based DSPy Signatures work when using `dspy.Predict`, but fail when using `dspy.ChainOfThought`.
This is due to PEP 604 Union Types being defined as a [types.UnionType](https://docs.python.org/3/library/types.html#types.UnionType), which was not included in the list of types to check in `make_signature` in `signature.py`. For reference, the original union type is defined as a [typing.Union](https://docs.python.org/3/library/typing.html#typing.Union)
```python
class SayTheRightType(dspy.Signature):
input: str = dspy.InputField()
output: str | int = dspy.OutputField()
input1 = "Say Hello World"
output = dspy.ChainOfThought(SayTheRightType)(input=input1).output
print(f"Output: {output} …
```
> Fix PEP 604 union types when using Class Signatures for ChainOfThought

- docs/docs/learn/programming/language_models.md
This PR fixes a small typo where the `print()` statement in the example contains "GPT-4o-mini" but the sample output displays "GPT-4o".
> Fix typo in language_models.md

- docs/docs/tutorials/build_ai_program/index.md
- docs/docs/tutorials/core_development/index.md
- docs/docs/tutorials/optimize_ai_program/index.md
- docs/docs/tutorials/rl_ai_program/index.md
Currently, the overview page of each tutorial category only has links. This PR introduces a brief explanation for each tutorial so that users can choose relevant tutorials easily.
> Add brief explanation for each tutorial in overview pages

- tests/clients/test_lm.py
.dict() is deprecated and will be removed in pydantic 3
> Use model_dump instead of dict

- dspy/adapters/base.py
- dspy/adapters/chat_adapter.py
- dspy/adapters/json_adapter.py
- dspy/adapters/two_step_adapter.py
- dspy/clients/lm.py
- tests/adapters/test_chat_adapter.py
- tests/adapters/test_json_adapter.py
A few changes:
- In the base adapter, we need to explicitly set the fields to None if they don't present in the response for consistency. This happens often with native function calling, because either the content or tool_calls will be missing.
- In the JSONAdapter, we fall back to json mode if native function calling is not used while ToolCalls are in the output fields. We do this because structured output performs very poorly on fields with type like `dict[str, Any]`, which is the `args` in `dspy.ToolCalls`.
- Add unit tests to cover the native function calling response parsing.
> Fix native function calling in adapters

- .github/workflows/run_tests.yml
- tests/conftest.py
- tests/primitives/test_base_module.py
- tests/streaming/test_streaming.py
- tests/utils/test_usage_tracker.py
This PR enables running unit tests that require real LLM calls, which have been skipped in CI.
The model for testing is configurable through `LLM_MODEL` env variable, and we use `ollama/llama3.2:3b` in the branch build to balance quality and latency. The Ollama model pulling only introduces ~13s latency, so this PR just enables real LLM tests in the branch build instead of nightly tests.
> Run unit tests with real LLM calls

- dspy/__init__.py
- dspy/teleprompt/bootstrap.py
- dspy/utils/__init__.py
- dspy/utils/syncify.py
- tests/utils/test_syncify.py
There two modes:
- in-place mode: return the same program instance, but patch the `forward` method. This is recommended, but may not work if users have a different sync forward already implemented, which is rare but yet possible.
- Wrapper mode: return a new DSPy module that wraps the original module. This would always work, but change the program architecture.
> Provide a `dspy.syncify` so that users can run optimizer on async dspy programs

- dspy/streaming/streaming_listener.py
- tests/streaming/test_streaming.py
Support XMLAdapter in `StreamListener`
This PR is generated by [OpenAI codex](https://openai.com/codex/), I am testing how deep it can understand DSPy codebase with this specific use case.
It passes on my tests:
```
import asyncio
import dspy
lm = dspy.LM("databricks/databricks-claude-3-7-sonnet", cache=False)
dspy.settings.configure(lm=lm, adapter=dspy.XMLAdapter())
class MyModule(dspy.Module):
super().__init__()
self.predict1 = dspy.Predict("question->answer")
self.predict2 = dspy.Predict("question, answer->judgement, score")
def forward(self, question: str, **kwargs):
answer = self.predict1(question=question)
judgement = self.predict2(question=question, answer=answer)
return judgement
predict = MyModule()
stream_listeners = [ …
```
> Add token streaming support for XMLAdapter

- dspy/__init__.py
- dspy/adapters/__init__.py
- dspy/adapters/types/__init__.py
- dspy/adapters/types/code.py
- tests/adapters/test_chat_adapter.py
- tests/adapters/test_code.py
- tests/adapters/test_json_adapter.py
- tests/adapters/test_xml_adapter.py
New type `dspy.Code`. Right now it's just a value holder with parser to get rid of the boilerplate like "```python".
We will incorporate this in dspy.CodeAct and dspy.ProgramOfThought after some benchmarking work. 
Sample usage (also available in the docstring):
Example 1: dspy.Code as output type in code generation:
```python
import dspy
dspy.configure(lm=dspy.LM("openai/gpt-4o-mini"))
class CodeGeneration(dspy.Signature):
'''Generate python code to answer the question.'''
question: str = dspy.InputField(description="The question to answer")
code: dspy.Code = dspy.OutputField(description="The code to execute")
predict = dspy.Predict(CodeGeneration)
result = predict(question="Given an array, find if any of the two numbers sum up to 10")
print(result.code)
```
Example 2: dspy.Code as input …
```
> add dspy.Code

- docs/docs/tutorials/streaming/index.md
Fixes issue - https://github.com/stanfordnlp/dspy/issues/8514
- Removed 'instance' parameter from the tool_end_status_message method as per documentation.
- Corrected stream_predict initialization to include status_message_provider.
> Fixes issue #8514: Issues in Tutorial Example with tool_end_status_message and stream_predict

- docs/docs/community/community-resources.md
- docs/docs/community/use-cases.md
The community pages contained some TODO comments or Wip comments that should not be displayed in the public website. This PR rephrased/removed these comments.
> Remove or rephrase todo comments in the community pages

- docs/docs/tutorials/build_ai_program/index.md
- docs/docs/tutorials/core_development/index.md
- docs/docs/tutorials/index.md
- docs/mkdocs.yml
This moves [Managing Conversation History](https://dspy.ai/tutorials/conversation_history/) from `Tools, Development, and Deployment` to `Build AI Programs with DSPy`, so it is easier for beginners to see it, since it is a basic tutorial.
ref issue https://github.com/stanfordnlp/dspy/issues/8531
> doc: Move Conversation History tutorial

- dspy/primitives/module.py
- dspy/propose/grounded_proposer.py
- dspy/teleprompt/mipro_optimizer_v2.py
- pyproject.toml
- tests/primitives/test_base_module.py
In the beta releases 3.0.0b1 and 3.0.0b2: If `datasets` wasn't installed, bootstrapping would fail silently. This made MIPRO runs much less effective for no good reason.
I published 3.0.0b3 *before* this PR with a patch that makes `datasets` a required dependency again. But this PR edits the pyproject.toml file just to record it here.
> Fixes for MIPRO: Don't fail silently on bootstrapping!

- dspy/evaluate/evaluate.py
- dspy/teleprompt/bootstrap.py
- dspy/teleprompt/random_search.py
Fix #8544   Along with some trivial automated style fix by the IDE.
> Remove legacy assertion code

- docs/docs/learn/programming/signatures.md
This PR fixes a breaking issue with the example used in the Programming Signatures page.  It changes the class name as to not conflict with the typing objects.
I give the details in this issue: https://github.com/stanfordnlp/dspy/issues/8543
> docs: Change class name as to not conflict 

- dspy/streaming/messages.py
- dspy/streaming/streaming_listener.py
- tests/streaming/test_streaming.py
It makes users' life easier if there is an explicit signal marking the end of the streaming of one field.
> Explicitly mark the end of streaming

- dspy/clients/cache.py
- dspy/predict/predict.py
- tests/predict/test_predict.py
Use json model when serializing Pydantic models to serialize pydantic special types like `pydantic.HttpUrl`
Resolve #8595
> Use json mode for serialization

- dspy/clients/base_lm.py
- dspy/dsp/utils/settings.py
- dspy/predict/predict.py
- dspy/utils/dummies.py
- tests/clients/test_lm.py
- tests/predict/test_predict.py
We introduced `disable_history` in the past, but `dspy.settings.trace` can still grow infinitely. Technically it's able to be disabled by `dspy.configure(trace=None)`, but we still need  a safeguard for the default path. 
fix #8604 
After this PR, even if users don't explicitly disable history and trace, the memory cost won't grow infinitely.
For e2e test, see the script below (this is mostly the same as reported in #8604, but I made a few edits):
```
#!/usr/bin/env python3
"""
Minimal reproduction of DSPy memory leak issue.
Each iteration creates a fresh ChainOfThought instance and deletes it,
but memory continuously grows and is never released.
"""
import gc
import asyncio
import os
from datetime import datetime
import dspy
import psutil
def get_memory():
"""Get memory info …
```
> Fix infinite growing trace and add tests

- pyproject.toml
This change fixes incorrect `build-system` requirements and resolves deprecation warnings thrown in CI when building using the latest setuptools versions. [[recent example](https://github.com/stanfordnlp/dspy/actions/runs/16390769890/job/46316448067#step:8:13)]
> ```
> /tmp/build-env-gfscc8yk/lib/python3.11/site-packages/setuptools/config/_apply_pyprojecttoml.py:82: SetuptoolsDeprecationWarning: `project.license` as a TOML table is deprecated
> !!
> 
>         ********************************************************************************
>         Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`. (Both options available on setuptools>=77.0.0).
> 
>         By 2026-Feb-18, you need to update your project and remove …
```
> Fix incorrect `build-system` requirements

- dspy/adapters/baml_adapter.py
- tests/adapters/test_baml_adapter.py
Closes #8613.
This PR provides a custom adapter named `BAMLAdapter` that subclasses the existing `JSONAdapter` to improve the quality of structured outputs generated by DSPy pipelines. The proposed adapter is inspired by another open source (Apache 2 licensed) project called [BAML](https://github.com/BoundaryML/baml), who created this format to improve upon JSON schema for their users based on the reasons they highlighted [in this blog post](https://boundaryml.com/blog/type-definition-prompting-baml).
The new adapter introduces no breaking changes, is non-intrusive, and is *purely opt-in* for those users (like myself) who need  better structured outputs from DSPy pipelines. So I figured it makes sense to allow the larger community to also benefit.
Introduces two new files:
- …
> Custom BAMLAdapter to improve structured outputs

- dspy/clients/utils_finetune.py
- dspy/teleprompt/bootstrap.py
- dspy/utils/hasher.py
- pyproject.toml
- uv.lock
This pull request aims to find a happy medium between removing the large dependency of `datasets` and having the ability to Bootstrap new examples via MIPROv2. (https://github.com/stanfordnlp/dspy/pull/8548)
Upon investigation, there are 2 locations within DSPy that use a function from `datasets` that is not `load_dataset`. Both of these happened to be `datasets.fingerprint.Hasher` and upon investigation, that class is extraordinarily simple. 
Due to those 2 facts, I went ahead and brought that code and the 1 required downstream dependency, `xxhash` into DSPy along with attribution to the `datasets` project. 
I'm open to any discussion, but this also resolves #8616.
> Vendor Hasher class from datasets library in order to remove larger dependency

- .github/workflows/build_and_release.yml
This change resolves deprecation warnings thrown during GitHub workflow runs. [[recent example](https://github.com/stanfordnlp/dspy/actions/runs/16390769890)]
> <img width="826" height="109" alt="image" src="https://github.com/user-attachments/assets/d723b602-f4f1-4ad6-8cb8-cd08378277b4" />
https://github.blog/changelog/2022-10-10-github-actions-deprecating-save-state-and-set-output-commands/
Thanks for your work on dspy!
> Migrate from `set-output` to `$GITHUB_OUTPUT` usage

- docs/docs/learn/optimization/optimizers.md
Remove doc content about the `save_field_meta` argument which was removed in 4be87efb2056378327b3572ddb222fcc202ff836 
Resolves #8618
> Remove instruction for save_field_meta

- dspy/evaluate/evaluate.py
Raises a TypeError when the now deprecated "return_output" is present in kwargs. If the user is using "return_output", the it will currently not crash, and instead return the string "outputs".
"return_outputs" is now on by default with the EvaluationResult object
> fix(evaluate): Raise TypeError on return_outputs in evaluate kwargs

- dspy/utils/usage_tracker.py
Add type hints to UsageTracker for internal consistency
> Add type hints for UsageTracker

- tests/primitives/resources/saved_program.json
- tests/primitives/test_module.py
Since 3.0, we want to ensure that a new release doesn't break loading a previously saved state.
With this purpose, we are storing a serialized state of an optimized ReAct program, which has demos and updated signature, and ensure that loaded program restores the state.
> Add test to ensure saving/loading backward compatibility

- dspy/primitives/module.py
- tests/primitives/test_base_module.py
This PR improves type inference in DSPy by adding explicit return type annotations to the `Module` class's `__call__` and `acall` methods. This enables IDEs and type checkers like pyright to correctly infer that DSPy modules return `Prediction` objects.
**Problem**
Previously, when using DSPy modules like `dspy.Predict` or `dspy.ChainOfThought`, type checkers would infer the return type as `object | Any`, making it difficult  for users to:
- Get proper IDE autocomplete for Prediction attributes
- Catch type-related errors at development time
- Understand the API without reading documentation
**Solution**
Added minimal, non-breaking type hints:
- Added Prediction import to `dspy/primitives/module.py`
- Annotated `Module.__call__` to return -> `Prediction`
- Annotated `Module.acall` to …
> Add type hints for Module.__call__ and Module.acall to return Prediction

- dspy/teleprompt/bootstrap_trace.py
Use a finally block to revert the patch inside `bootstrap_trace_data`.
> Revert bootstrap patch safely

- dspy/primitives/module.py
- tests/teleprompt/test_gepa.py
Fixes #8738 - Resolves AttributeError when using GEPA optimizer with `track_usage=True`.
GEPA's bootstrap tracing patches `module.forward` to return tuples `(prediction, trace)`, but the usage tracking code in `Module.__call__` expected only prediction objects, causing:
```
AttributeError: 'tuple' object has no attribute 'set_lm_usage'
```
Enhanced `Module` to safely handle both prediction objects and tuples:
- **Before**: `output.set_lm_usage(tokens)` (fails with tuples)
- **After**: Detects which part of the output is of type `Prediction` and extracts the object safely
**Key changes:**
1. **`dspy/primitives/module.py`**: Added tuple-safe usage tracking logic
2. **`tests/teleprompt/test_gepa.py`**: Added regression test with timeout protection
**Regarding test and timeout:**
1. The …
> Fix GEPA usage tracking with tuple outputs

- dspy/teleprompt/gepa/gepa.py
- dspy/teleprompt/gepa/gepa_utils.py
- dspy/teleprompt/gepa/instruction_proposal.py
- pyproject.toml
- tests/teleprompt/test_gepa_instruction_proposer.py
- uv.lock
Closes https://github.com/stanfordnlp/dspy/issues/8690
As proposed by @LakshyAAAgrawal, this PR makes GEPA’s instruction-proposal step pluggable. Users can supply a custom instruction proposer, enabling GEPA to handle dspy.Image and other custom types.
- **Custom Instruction Proposer Protocol**: New `InstructionProposerProtocol` for implementing custom instruction generation
- **MultiModalInstructionProposer**: Built-in proposer that handles multimodal inputs (text + images) during optimization
- **Structured Image Handling**: Preserves `dspy.Image` objects without serialization in reflection LM calls
- **Backward Compatibility**: Existing GEPA usage continues to work unchanged
```python
import dspy
from dspy.teleprompt.gepa.instruction_proposal import MultiModalInstructionProposer
lm = …
```
> Add custom instruction_proposer support to GEPA with multimodal (dspy.Image) handling

- docs/docs/tutorials/gepa_facilitysupportanalyzer/index.ipynb
There was a duplicate cell in the beginning of the GEPA information extraction tutorial. I removed it.
> fix: removed duplicate cell from GEPA information extraction tutorial

- dspy/adapters/utils.py
- tests/adapters/test_adapter_utils.py
This is my proposed fix for #8804
> Fix unexpected parsing of Optional[str] fields when string has brackets or braces

- dspy/teleprompt/gepa/gepa.py
- pyproject.toml
Added gepa_kwargs parameter for additional GEPA options.
> Introduce gepa_kwargs for passing custom kwargs to gepa.optimize

- dspy/primitives/module.py
- tests/primitives/test_base_module.py
Currently, dspy modules whose output is not `dspy.Prediction` fail to execute when the usage tracker is enabled. This PR fixes the crash by skipping the usage tracking for this type of modules. While returning objects other than dspy.Prediciton is not expected, this pattern has been found in several places.
Example:
```python
class MyProgram(dspy.Module):
self.predict = dspy.Predict("question -> answer")
def forward(self, question: str, **kwargs) -> str:
return self.predict(question=question).answer
program = MyProgram()
with dspy.context(track_usage=True):
program(question="What is the capital of France?")
```
> Fix the crash when usage tracker is enabled with non-prediction output

- dspy/retrievers/embeddings.py
- tests/retrievers/test_embeddings.py
> Add save/load to Embeddings

- dspy/clients/cache.py
- tests/clients/test_lm.py
When both memory and disk cache are disabled, we want to avoid creating a cache key that will not be used.
Creating the cache key is expensive for prompts with images in them.
Fixes #8856
> bug(lm): Avoid unnecessary cache key computation

- pyproject.toml
- tests/predict/test_react.py
- uv.lock
- add Pillow as a core dependency so PIL utilities are available for runtime features
- mark the ReAct test that depends on PIL as an extra test to match optional execution expectations
- import PIL lazily inside the ReAct test using `pytest.importorskip`
> Add Pillow dependency and adjust ReAct test import

- dspy/predict/parallel.py
- dspy/utils/parallelizer.py
- tests/predict/test_parallel.py
- tests/utils/test_parallelizer.py
> Fix error handling in dspy parallel

- docs/docs/learn/programming/tools.md
- dspy/adapters/types/tool.py
- tests/adapters/test_tool.py
This PR adds a helper function to ToolCall so that users can run tool calls with less boilerplate.
```python
import dspy
class ToolSignature(dspy.Signature):
"""Signature for manual tool handling."""
question: str = dspy.InputField()
tools: list[dspy.Tool] = dspy.InputField()
outputs: dspy.ToolCalls = dspy.OutputField()
def weather(city: str) -> str:
"""Get weather information for a city."""
return f"The weather in {city} is sunny"
def calculator(expression: str) -> str:
"""Evaluate a mathematical expression."""
try:
result = eval(expression)  # Note: Use safely in production
return f"The result is {result}"
except:
return "Invalid expression"
predictor = dspy.Predict(ToolSignature)
response = predictor(
question="What's the weather in New York?",
tools=[dspy.Tool(weather), …
```
> Add ToolCall.execute for smoother tool execution

- dspy/streaming/streamify.py
- dspy/streaming/streaming_listener.py
- tests/streaming/test_streaming.py
**Issue**
There is an issue that some text content chunks are lost when there are more than 10 chunks for a string field, and the native response, such as Anthropic Citation, is used.
**Root Cause**
This was caused by the assumption that at most one streaming listener returns a chunk for the same chunk. This assumption is not true when native response, such as citation API, is used because a streaming listener buffers 10 chunks for string output fields, and sometimes the string chunk and native response chunk are produced simultaneously.
**Fix**
This PR fixes the issue by allowing multiple listeners to return a chunk for the same response chunk.
> Fix chunk loss in the long streaming response with native response field

- dspy/clients/base_lm.py
- dspy/clients/lm.py
Remove trailing spaces, and use 120 max width as declared in pyproject.toml.
> Fix lint of LM

- dspy/streaming/streamify.py
- dspy/streaming/streaming_listener.py
- tests/streaming/test_streaming.py
Closes #8889
Strategy adopted:
When the stream ends, we finalize the listeners by emitting tokens that might still be in the buffer, returning a StreamResponse with is_last_chunk=True.
> fix: add fallback mechanism on missing end marker during streaming

- dspy/teleprompt/mipro_optimizer_v2.py
MIPROv2 doesn't actually use `task_model` anywhere in the code. It does pass `prompt_model` to `GroundedProposer`.
Manually validated that MIPRO runs e2e with no dspy.configure via the following script:
```python
import dspy
lm = dspy.LM("openai/gpt-5-nano", temperature=1.0, max_tokens=16000)
program = dspy.Predict("number_as_string: str -> number: int")
trainset = [
dspy.Example(number_as_string="123", number=123).with_inputs("number_as_string"),
dspy.Example(number_as_string="456", number=456).with_inputs("number_as_string"),
dspy.Example(number_as_string="789", number=789).with_inputs("number_as_string"),
]
def metric_dspy(e, p, t=None):
return 1 if p.number == e.number else 0
optimizer = dspy.MIPROv2(
metric_dspy, 
max_bootstrapped_demos = 3, 
max_labeled_demos = 3, 
prompt_model=lm, …
```
> fix(MIPROv2): select between task_model and prompt_model
